### ISSUE TITLE
Can't import Bestiary 2 - Crystal Dragon, Great Wyrm

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#100]
Can't import statblock:

Crystal Dragon, Great Wyrm      CR 18
XP 153,600
Male great wyrm crystal dragon (Pathfinder RPG Bestiary 2 98)
CG Gargantuan dragon (earth, extraplanar)
Init +3; Senses dragon senses, tremorsense 120 ft.; Perception +34
Aura frightful presence (360 ft., DC 31), scintillating aura (60 ft., DC 30)
--------------------
Defense
--------------------
AC 40, touch 5, flat-footed 40 (-1 Dex, +35 natural, -4 size)
hp 362 (25d12+200)
Fort +24, Ref +15, Will +20
DR 20/magic; Immune paralysis, sleep, sonic; SR 29
--------------------
Offense
--------------------
Speed 60 ft., burrow 30 ft., climb 30 ft., fly 250 ft. (clumsy)
Melee bite +34 (4d6+18/19-20), 2 claws +33 (2d8+12/19-20), tail slap +31 (2d8+18), 2 wings +31 (2d6+6)
Space 15 ft.; Reach 10 ft. (15 ft. with bite)
Special Attacks breath weapon (60-ft cone, 24d4 sonic, Reflex DC 30 half), crush (Medium creatures, DC 30, 4d6+18), tail sweep (30-ft., 2d6+18, DC 30)
Spell-Like Abilities (CL 25th; concentration +34)
   At will—color spray (DC 20), glitterdust (DC 21), rainbow pattern (DC 23)
   3/day—prismatic spray (DC 26), stone to flesh (DC 25)
   1/day—imprisonment (DC 28)
Sorcerer Spells Known (CL 13th; concentration +22)
   6th (5/day)—disintegrate (DC 25), true seeing
   5th (8/day)—feeblemind (DC 24), persistent image (DC 24), seeming (DC 24)
   4th (8/day)—dimension door, illusory wall (DC 23), phantasmal killer (DC 23), stoneskin
   3rd (8/day)—displacement, lightning bolt (DC 22), major image (DC 22), protection from energy
   2nd (8/day)—blindness/deafness (DC 21), eagle's splendor, invisibility, minor image (DC 21), mirror image
   1st (9/day)—alarm, feather fall, magic aura, silent image (DC 20), unseen servant
   0 (at will)—acid splash, arcane mark, detect magic, detect poison, ghost sound (DC 19), mage hand, message, read magic, touch of fatigue (DC 19)
--------------------
Statistics
--------------------
Str 35, Dex 8, Con 27, Int 22, Wis 23, Cha 28
Base Atk +25; CMB +41; CMD 50 (54 vs. trip)
Feats Critical Focus, Deceitful, Great Fortitude, Greater Vital Strike, Improved Critical (bite), Improved Critical (claw), Improved Initiative, Improved Vital Strike, Lightning Reflexes, Multiattack, Power Attack, Vital Strike, Weapon Focus (bite)
Skills Acrobatics -1 (+11 to jump), Appraise +34, Bluff +41, Climb +48, Disguise +38, Fly +13, Intimidate +37, Knowledge (dungeoneering) +34, Knowledge (geography) +34, Perception +34, Sense Motive +34, Stealth +15, Survival +34
Languages Common, Draconic, Dwarven, Elven, Terran, Undercommon
SQ ray reflection, razor sharp
--------------------
Ecology
--------------------
Environment any underground (plane of earth)
Organization solitary
Treasure triple
--------------------
Special Abilities
--------------------
Blindsense (60 feet) (Ex) Sense things and creatures without seeing them.
Breath Weapon (60-ft cone, 24d4 sonic, Reflex DC 30 half, usable every 1d4 rounds) As a standard action, affect an area with elemental damage (Ref half).
Burrow (30 feet) You have a Burrow speed.
Climb (30 feet) You have a Climb speed.
Critical Focus +4 to confirm critical hits.
Crush (Medium creatures, 4d6+18, DC 30) A flying or jumping Huge or larger dragon can land on foes as a standard action, using its whole body to crush them. Crush attacks are effective only against opponents three or more size categories smaller than the dragon. A crush attack affects as m
Damage Reduction (20/magic) You have Damage Reduction against all except Magic attacks.
Darkvision (120 feet) You can see in the dark (black and white only).
Dragon Senses (Ex) See four times as well as a human in dim light and twice as well in normal light.
Fly (250 feet, Clumsy) You can fly!
Frightful Presence (360 ft., 5d6 rounds, DC 31) Those in area of effect become frightened or shaken (Will neg.)
Immunity to Paralysis You are immune to paralysis.
Immunity to Sleep You are immune to sleep effects.
Immunity to Sonic You are immune to sonic damage.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -7/+14 You can subtract from your attack roll to add to your damage.
Ray Reflection (Ex) An ancient crystal dragon's scales reflect ray spells back upon the ray's source if the ray fails to overcome the dragon's spell resistance.
Razor Sharp All of a crystal dragon's natural attacks deal slashing damage.
Scintillating Aura (60 ft., DC 30) A great wyrm crystal dragon radiates an aura of scintillating color from its jeweled scales to a radius of 60 feet. All within this area must make a Will save each round to avoid being stunned (if the victim has 15 or fewer Hit Dice) or confused (if 
Spell Resistance (29) You have Spell Resistance.
Tail Sweep (30-ft., 2d6+18, DC 30) As a standard action, deal damage in half circle to foes 4+ sizes smaller (Ref half).
Tremorsense (120 feet) Sense creatures and objects in contact with ground or water.
Vital Strike Standard action: x2 weapon damage dice.

**Comment by adventuremagic123** [comment]
I used Hero Lab to produce this statblock.  For greater accuracy, you might want to use one of the online resources.  Hero Lab can truncate some of the text.  All the other statblocks from Bestiary 2 imported -- a total of more than 96% imported.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this morning.

**Comment by Lavaeolous** [comment]
Should import with v0.4.0 apart from

- [ ] Spell-Parse Errors (i'm entering these separately)
