### ISSUE TITLE
Can't import Bestiary 2 - Kelpie

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#101]
Can't import statblock:

Kelpie      CR 4
XP 1,200
Male kelpie (Pathfinder RPG Bestiary 2 172)
NE Medium fey (aquatic, shapechanger)
Init +7; Senses low-light vision; Perception +13
--------------------
Defense
--------------------
AC 17, touch 13, flat-footed 14 (+3 Dex, +4 natural)
hp 38 (7d6+14)
Fort +4, Ref +8, Will +6
Resist fire 10
--------------------
Offense
--------------------
Speed 40 ft., swim 40 ft.
Melee 2 slams +6 (1d6+2 plus grab)
--------------------
Statistics
--------------------
Str 15, Dex 16, Con 15, Int 8, Wis 12, Cha 17
Base Atk +3; CMB +5 (+9 grapple); CMD 18
Feats Alertness, Deceitful, Improved Initiative, Weapon Finesse
Skills Acrobatics +3 (+7 to jump), Bluff +15, Disguise +15, Perception +13, Sense Motive +13, Stealth +13, Swim +10
Languages Aquan, Common, Sylvan; telepathy (1 mile, previously touched creatures only)
SQ amphibious, captivating lure, change shape (hippocampus or horse; beast shape I), change shape (Small or Medium humanoid; alter self)
--------------------
Ecology
--------------------
Environment any water
Organization solitary or shoal (2-5)
Treasure standard
--------------------
Special Abilities
--------------------
Amphibious (Ex) You can survive indefinitely on land.
Captivating Lure (1/day, DC 16) (Su) Once per day, a kelpie can use a powerful mental attack to lure in a single creature within 60 feet. The target must make a DC 16 Will saving throw or become captivated by the kelpie, thinking it is a desirable woman in mortal danger or (if in hippoc
Change Shape (hippocampus or horse; beast shape I) (Su) You can change your form.
Change Shape (Small or Medium humanoid; alter self) (Su) You can change your form.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Grab: Slam (Medium) (Ex) You can start a grapple as a free action if you hit with the designated weapon.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Swim (40 feet) You have a Swim speed.
Telepathy (1 mile, previously touched creatures only) (Su) Communicate telepathically if the target has a language.

**Comment by adventuremagic123** [comment]
I used Hero Lab to produce this statblock.  For greater accuracy, you might want to use one of the online resources.  Hero Lab can truncate some of the text.  All the other statblocks from Bestiary 2 imported -- a total of more than 96% imported.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this morning.

**Comment by Lavaeolous** [comment]
Identified Issue: Parenthesis in languages, e.g. **Languages Aquan, Common, Sylvan; telepathy (1 mile, previously touched creatures only)**
