### ISSUE TITLE
Importing with parsing errors Bestiary 3 - Aghash (Div)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#117]
Importing statblock produces parsing errors:

Aghash (Div)      CR 4
XP 1,200
Male aghash (Pathfinder RPG Bestiary 3 83)
NE Medium outsider (div, evil, extraplanar)
Init +2; Senses darkvision 60 ft., see in darkness; Perception +11
--------------------
Defense
--------------------
AC 18, touch 12, flat-footed 16 (+2 Dex, +6 natural)
hp 42 (5d10+15)
Fort +4, Ref +6, Will +7
DR 5/good or cold iron; Immune fire, poison; Resist acid 10, electricity 10; SR 15
--------------------
Offense
--------------------
Speed 30 ft.
Melee 2 claws +8 (1d6+2)
Special Attacks cursed gaze, sandstorm
Spell-Like Abilities (CL 6th; concentration +10)
   At will—bestow curse (DC 18), detect good, detect magic, dimension door, minor image (DC 16), spectral hand
   1/day—suggestion (DC 17), summon (level 3, 1d2 dorus 25%)
--------------------
Statistics
--------------------
Str 14, Dex 15, Con 16, Int 13, Wis 13, Cha 18
Base Atk +5; CMB +7; CMD 19
Feats Alertness, Iron Will, Weapon Focus (claw)
Skills Bluff +10, Disguise +12, Intimidate +10, Knowledge (arcana) +7, Knowledge (planes) +7, Perception +11, Sense Motive +9, Spellcraft +9, Stealth +10
Languages Abyssal, Celestial, Infernal; telepathy 100 ft.
--------------------
Special Abilities
--------------------
Cursed Gaze (DC 16) (Su) Gaze in 30 ft, choice of confuse/shaken/stun 1 rd, or 1d4 dam (Fort neg).
Damage Reduction (5/cold iron or good) You have Damage Reduction against all except Good or Cold Iron attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Electricity (10) You have the specified Energy Resistance against Electricity attacks.
Immunity to Fire You are immune to fire damage.
Immunity to Poison You are immune to poison.
Sandstorm (1/day) (Su) Can create 100 ft radius sandstorm centered on self for 1 min/HD.
See in Darkness See perfectly in darkness of any kind, including magical darkness.
Spell Resistance (15) You have Spell Resistance.
Summon (level 3, 1d2 dorus 25%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.

**Comment by adventuremagic123** [comment]
I was wrong.  It imports with warning messages.

**Comment by adventuremagic123** [comment]
Actually, this is a good representative of NPC statblocks that produce parsing errors.  I've attached the messages.
![warning messages with parsing errors.  I'm seeing a lot of them for other NPCs, also.

![warning messages with parsing errors](https://user-images.githubusercontent.com/50708405/87258189-5bdb5d80-c467-11ea-8a92-c113e6157a89.JPG)

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
I've included these Notifications in the spell parsing section, because not all Spells are included in the compendium yet. But here it seems the Summons Feature is acting up.
