### ISSUE TITLE
Can't import Bestiary 3 - Axe Beak

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#119]
Can't import statblock:

Axe Beak      CR 2
XP 600
Male axe beak (Pathfinder RPG Bestiary 3 29)
N Large animal
Init +3; Senses low-light vision; Perception +9
--------------------
Defense
--------------------
AC 14, touch 12, flat-footed 11 (+3 Dex, +2 natural, -1 size)
hp 22 (3d8+9)
Fort +6, Ref +6, Will +1
--------------------
Offense
--------------------
Speed 50 ft.
Melee bite +5 (1d8+6)
Space 10 ft.; Reach 10 ft.
Special Attacks sudden charge
--------------------
Statistics
--------------------
Str 18, Dex 17, Con 16, Int 2, Wis 11, Cha 10
Base Atk +2; CMB +7; CMD 20
Feats Run, Skill Focus (Perception)
Skills Acrobatics +3 (+7 to jump with a running start, +11 to jump), Perception +9
--------------------
Ecology
--------------------
Environment temperate plains
Organization solitary, pair, or flock (3-6)
Treasure value 550 gp (shiny objects)
--------------------
Special Abilities
--------------------
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Run Run 5x your speed in light/medium armor or 4x speed in heavy armor and keep Dex when running.
Sudden Charge (Ex) On charge, if bite hits then make free trip attack.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
The Statblock seams malformed. The one from Archives of Nethys works
