### ISSUE TITLE
Can't import Bestiary 3 - Baluchitherium (Megafauna)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#120]
Can't import statblock:

Baluchitherium (Megafauna)      CR 8
XP 4,800
Male baluchitherium (Pathfinder RPG Bestiary 3 192)
N Huge animal
Init +0; Senses low-light vision, scent; Perception +16
--------------------
Defense
--------------------
AC 22, touch 8, flat-footed 22 (+14 natural, -2 size)
hp 114 (12d8+60)
Fort +15, Ref +8, Will +7
--------------------
Offense
--------------------
Speed 40 ft.
Melee 2 hooves +16 (2d8+9)
Space 15 ft.; Reach 10 ft.
Special Attacks trample (2d8+13, DC 25)
--------------------
Statistics
--------------------
Str 29, Dex 10, Con 21, Int 2, Wis 13, Cha 6
Base Atk +9; CMB +20 (+22 bull rush); CMD 30 (32 vs. bull rush, 34 vs. trip)
Feats Awesome Blow, Great Fortitude, Improved Bull Rush, Iron Will, Power Attack, Skill Focus (Perception)
Skills Acrobatics +0 (+4 to jump), Perception +16, Swim +15
--------------------
Special Abilities
--------------------
Awesome Blow As standard action, damage and move smaller foe 10 ft. +1d6 dam if collide with something.
Improved Bull Rush You don't provoke attacks of opportunity when bull rushing.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -3/+6 You can subtract from your attack roll to add to your damage.
Scent (Ex) Detect opponents within 15+ ft. by sense of smell.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
The one from the Archives of Nethys works
