### ISSUE TITLE
Foundry VTT hung while trying to import Bestiary 3 - Bugbear Bloodmage

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#124]
Trying to import the following statblock caused Foundry VTT to become hung:

Bugbear Bloodmage      CR 11
XP 12,800
Bugbear sorcerer 10 (Pathfinder RPG Bestiary 38)
CE Medium humanoid (goblinoid)
Init +6; Senses darkvision 60 ft., scent; Perception +0
--------------------
Defense
--------------------
AC 18, touch 13, flat-footed 15 (+2 Dex, +1 dodge, +5 natural)
hp 97 (13 HD; 10d6+3d8+49)
Fort +8, Ref +11, Will +9
Resist fire 20
--------------------
Offense
--------------------
Speed 30 ft.
Melee +1 quarterstaff +12/+7 (1d6+7)
Ranged mwk shortbow +6/+1 (1d6/×3)
Bloodline Spell-Like Abilities (CL 10th; concentration +13)
   6/day—elemental ray (1d6+5 fire)
   1/day—elemental blast (10d6 fire, DC 18)
Sorcerer Spells Known (CL 10th; concentration +13)
   5th (3/day)—fire snake[APG] (DC 18)
   4th (5/day)—black tentacles, elemental body I, fire shield
   3rd (7/day)—fireball (DC 16), howling agony[UM] (DC 16), protection from energy, rage, stinking cloud (DC 16)
   2nd (7/day)—alter self, invisibility, levitate, scorching ray (fire), see invisibility, touch of idiocy
   1st (7/day)—burning hands (fire) (DC 14), color spray (DC 14), enlarge person (DC 14), magic missile, ray of enfeeblement (DC 14), shield
   0 (at will)—acid splash, daze (DC 13), detect magic, detect poison, ghost sound (DC 13), mage hand, read magic, resistance, touch of fatigue (DC 13)
   Bloodline Elemental (fire)
--------------------
Tactics
--------------------
Before Combat The bloodmage casts invisibility and positions herself where she can hurl spells with impunity.
During Combat At the start of the battle, the bloodmage casts fire snake and fireball on her foes. She reserves spells such as fire shield and shield to protect herself when she becomes the target of attacks.
--------------------
Statistics
--------------------
Str 18, Dex 15, Con 16, Int 8, Wis 10, Cha 17
Base Atk +7; CMB +11; CMD 24
Feats Combat Casting, Dodge, Empower Spell, Enlarge Spell, Eschew Materials, Improved Initiative, Lightning Reflexes, Point-Blank Shot, Precise Shot
Skills Intimidate +7, Spellcraft +12, Stealth +12; Racial Modifiers +4 Intimidate, +4 Stealth
Languages Common, Goblin
SQ bloodline arcana (change energy damage spells to match bloodline energy), stalker
Combat Gear potion of cure moderate wounds; Other Gear +1 quarterstaff, mwk dagger, mwk shortbow with 20 arrows, amulet of natural armor +2, cloak of resistance +1, headband of alluring charisma +2, 117 gp
--------------------
Special Abilities
--------------------
Bloodline Arcana: Elemental (Ex) You may change any energy spell to use Fire energy.
Combat Casting +4 to Concentration checks to cast while on the defensive.
Darkvision (60 feet) You can see in the dark (black and white only).
Elemental Blast (10d6 fire, 1/day, DC 18) (Sp) As a standard action, deal dam in 20 ft. burst up to 60 ft. away (Ref half).
Elemental Ray (1d6+5 fire, 6/day) (Sp) As a standard action, ranged touch attack deals damage to foe.
Empower Spell Numeric effects of a spell are increased 50%. +2 Levels.
Energy Resistance, Fire (20) You have the specified Energy Resistance against Fire attacks.
Enlarge Spell Increase spell ranges. +1 Level.
Eschew Materials Cast spells without materials, if component cost is 1 gp or less.
Point-Blank Shot +1 to attack and damage rolls with ranged weapons at up to 30 feet.
Precise Shot You don't get -4 to hit when shooting or throwing into melee.
Scent (Ex) Detect opponents within 15+ ft. by sense of smell.
Stalker (Ex) Perception and Stealth are always class skills for members of this race.
--------------------
Arcane spellcasters among bugbears are typically sorcerers-few bugbears have enough interest or patience to follow arcane paths such as wizardry that require study or control. Bugbears call those with natural magical talent bloodmages, and treat their spellcasting ability the same as any skill-if it’s useful for hurting, it’s worth knowing. A typical bloodmage is interested in only spells that cause destruction and pain, plus a few supplemental spells to help her defend herself. Almost no bloodmages learn to create magic items.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
There was a "?" in the RegEx checking the class level that shouldn't be there. How and why that brought Foundry to crash i have no idea. But it should be fixed in 1.0.3
