### ISSUE TITLE
Can't import Bestiary 3 - Companion Leopard

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#128]
Can't import statblock:

Companion Leopard      CR –
Male leopard
N Medium animal
Init +6; Senses low-light vision, scent; Perception +7
--------------------
Defense
--------------------
AC 24, touch 16, flat-footed 18 (+6 Dex, +8 natural)
hp 39 (6d8+12)
Fort +7, Ref +11, Will +3 (+4 morale bonus vs. enchantment effects)
Defensive Abilities evasion
--------------------
Offense
--------------------
Speed 50 ft.; sprint
Melee bite +8 (1d6+4), 2 claws +8 (1d3+4)
--------------------
Statistics
--------------------
Str 18, Dex 22, Con 15, Int 2, Wis 12, Cha 6
Base Atk +4; CMB +8; CMD 24 (28 vs. trip)
Feats Improved Natural Armor, Improved Natural Armor, Improved Natural Armor
Skills Acrobatics +12 (+20 to jump), Perception +7, Stealth +6 (+10 in undergrowth); Racial Modifiers +4 Stealth in undergrowth
SQ devotion
--------------------
Special Abilities
--------------------
Devotion +4 (Ex) +4 morale bonus on Will saves vs. enchantment effects.
Evasion (Ex) No damage on successful reflex save.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Scent (Ex) Detect opponents within 15+ ft. by sense of smell.
Sprint (1/hour) (Ex) Can move ten times normal speed (500 feet) when you make a charge.
Trip (Ex) You can make a trip attempt on a successful attack.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
Statblock is missing CR. Works if its set to something or deleted.
