### ISSUE TITLE
Can't import Bestiary 3 - Diatryma (Axe Beak)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#131]
Can't import statblock:

Diatryma (Axe Beak)      CR 1
XP 400
Male diatryma (Pathfinder RPG Bestiary 3 29)
N Medium animal
Init +3; Senses low-light vision; Perception +8
--------------------
Defense
--------------------
AC 15, touch 13, flat-footed 12 (+3 Dex, +2 natural)
hp 19 (2d8+6)
Fort +6, Ref +6, Will +0
--------------------
Offense
--------------------
Speed 50 ft.
Melee bite +5 (1d8+6)
Special Attacks sudden charge
--------------------
Statistics
--------------------
Str 18, Dex 17, Con 16, Int 2, Wis 11, Cha 10
Base Atk +1; CMB +5; CMD 18
Feats Skill Focus (Perception)
Skills Acrobatics +3 (+11 to jump), Perception +8
--------------------
Special Abilities
--------------------
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Sudden Charge (Ex) On charge, if bite hits then make free trip attack.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
Hero Lab enters Low-Light Vision and other basics into the Special Abilities. The Converter can't really handle that. Apart from the import works.
