### ISSUE TITLE
Foundry VTT became hung when trying to import Bestiary 3 - Mizzinastre Vexidyre

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#144]
Foundry VTT became hung when trying to import statblock:

Mizzinastre Vexidyre      CR 18
XP 153,600
Female annis hag witch 15 (Pathfinder RPG Advanced Player's Guide 65, Pathfinder RPG Bestiary 3 16)
CE Medium monstrous humanoid
Init +4; Senses darkvision 60 ft.; Perception +16
--------------------
Defense
--------------------
AC 31, touch 16, flat-footed 26 (+4 armor, +1 deflection, +4 Dex, +1 dodge, +11 natural)
hp 145 (22 HD; 15d6+7d10+103)
Fort +8, Ref +9, Will +10
DR 5/bludgeoning; SR 17
--------------------
Offense
--------------------
Speed 40 ft.
Melee bite +9 (1d4+2), 2 claws +9 (1d4+2 plus grab)
Special Attacks hexes (blight[APG], cackle[APG], evil eye[APG], flight[APG], major healing[APG], misfortune[APG], retribution[APG], waxen image[APG]), rend (2 claws, 1d8+3)
Spell-Like Abilities (CL 7th; concentration +10)
   3/day—alter self, fog cloud
Witch Spell-Like Abilities (CL 15th; concentration +22)
   At will—feather fall (self only), fly (self only)
   1/day—levitate (self only)
Witch Spells Prepared (CL 15th; concentration +22)
   8th—horrid wilting (DC 25)
   7th—harm (DC 24), power word blind, reverse gravity
   6th—cone of cold (DC 23), greater dispel magic, mass fester[APG] (DC 23), mislead (DC 23)
   5th—feeblemind (DC 24), mind fog (DC 24), suffocation[APG] (DC 22), teleport, waves of fatigue
   4th—crushing despair (DC 23), cure serious wounds, dimension door, enervation, phantasmal killer (DC 21)
   3rd—bestow curse (DC 20), dispel magic, major image (DC 20), ray of exhaustion (DC 20), screech[APG] (DC 20), vampiric touch
   2nd—alter self, alter self, false life, mirror image, spectral hand, web (DC 19)
   1st—charm person (DC 20), chill touch (DC 18), ill omen[APG], mage armor, obscuring mist, ray of enfeeblement (DC 18)
   0 (at will)—bleed (DC 17), daze (DC 19), read magic, touch of fatigue (DC 17)
   Patron Trickery
--------------------
Statistics
--------------------
Str 14, Dex 18, Con 16, Int 24, Wis 12, Cha 16
Base Atk +14; CMB +2 (+6 grapple); CMD 24
Feats Arcane Strike, Craft Staff, Craft Wondrous Item, Dodge, Greater Spell Focus (enchantment), Improved Familiar, Spell Focus (enchantment), Toughness
Skills Acrobatics +4 (+8 to jump), Intimidate +21, Knowledge (arcana) +25, Knowledge (dungeoneering) +22, Knowledge (nature) +32, Knowledge (nobility) +22, Knowledge (planes) +32, Knowledge (religion) +22, Perception +16, Spellcraft +25, Swim +6
Languages Abyssal, Aklo, Dwarven, Elven, Necril, Terran, Undercommon
SQ witch's familiar (quasit named Malkasar)
Combat Gear staff of cackling wrath[APG]; Other Gear amulet of natural armor +1, headband of vast intelligence +4, ring of protection +1, spell component pouch, wooden unholy symbol of Shax, 158 pp
--------------------
Special Abilities
--------------------
Arcane Strike As a swift action, add +1 damage, +1 per 5 caster levels and your weapons are treated as magic for the purpose of overcoming damage reduction.
Blight (DC 24) (Su) Curse animals, plants, or land, causing it to wither and die.
Cackle (Su) As a move action, extend the duration of other hexes by 1 rd.
Damage Reduction (5/bludgeoning) You have Damage Reduction against all except Bludgeoning attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Deliver Touch Spells Through Familiar (Su) Your familiar can deliver touch spells for you.
Empathic Link with Familiar (Su) You have an empathic link with your Arcane Familiar.
Evil Eye -4 (10 rounds, DC 24) (Su) Foe in 30 ft takes penalty to your choice of AC, attacks, saves, ability or skill checks (Will part).
Familiar Bonus:  You gain the Alertness feat while your familiar is within arm's reach.
Grab: Claw (Medium) (Ex) You can start a grapple as a free action if you hit with the designated weapon.
Greater Spell Focus (Enchantment) +1 to the Save DC of spells from one school.
Major Healing (4d8+15) (Su) Use cure critical wounds once per day/person.
Misfortune (2 rounds, DC 24) (Su) Foe in 30 ft must take the lower of 2d20 for rolls (Will neg).
Retribution (7 rounds, DC 24) (Su) Foe in 60 ft suffers half the melee damage it deals, ignoring resist, for duration (Will neg).
Scry on Familiar (1/day) (Sp) You can scry on your familiar, as the spell.
Share Spells with Familiar Can cast spells with a target of "You" on the familiar with a range of touch.
Speak with Animals (Ex) Your familiar can communicate with animals similar to itself.
Speak with Familiar (Ex) You can communicate verbally with your familiar.
Spell Focus (Enchantment) Spells from one school of magic have +1 to their save DC.
Spell Resistance (17) You have Spell Resistance.
Waxen Image (7 uses, DC 24) (Su) As a full rd action, create wax figure used to force to specific actions (Will neg).
Witch's Familiar (Ex) Gain the services of a special familiar that stores spells.
--------------------
Mizzinastre has long worshiped Shax and considers herself a direct conduit of her lord’s murderous will. The irony of shedding a venerable but still beautiful drow body for a young but aged-looking hag’s body vexes the witch, so she often uses alter self to change back to a more beautiful form, similar to the one she bore in her previous life.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this afternoon at about 2:30pm.  I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text. All the other statblocks from Bestiary 3 imported -- a total of more than 86% imported!

**Comment by Lavaeolous** [comment]
Wow, that one is evil. No Error Message at all, but a complete freeze of Foundry.
That will take some time.

**Comment by Lavaeolous** [comment]
There was a "?" in the RegEx checking the class level that shouldn't be there. How and why that brought Foundry to crash i have no idea. But it should be fixed in 1.0.3
