### ISSUE TITLE
Can't import Bestiary 4 - Argus

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#164]
Can't import statblock:

Argus      CR 13/MR 6
XP 25,600
Argus (Pathfinder RPG Bestiary 4 13)
LN Gargantuan aberration (mythic)
Init +12; Senses arcane sight, darkvision 60 ft., detect scrying, limitless vision, mistsight, see in darkness, true seeing; Perception +29 (+37 on vision-based checks)
Aura frightful presence (40 ft., DC 16)
--------------------
Defense
--------------------
AC 30, touch 12, flat-footed 28 (+2 Dex, +4 insight, +18 natural, -4 size)
hp 184 (13d8+126)
Fort +10, Ref +6, Will +9; -4 penalty vs. effects that cause fascination, -4 penalty vs. effects that cause sleep
Defensive Abilities absolute readiness, all-around vision, rock catching; DR 10/epic; Immune blindness, dazzled; Resist cold 30, fire 30
Weaknesses vulnerability to fascination, vulnerability to sleep
--------------------
Offense
--------------------
Speed 40 ft.
Melee bite +19 (2d8+14), 2 claws +20 (3d6+14 plus grab)
Ranged rock +8 (3d6+21)
Space 20 ft.; Reach 20 ft.
Special Attacks accurate strikes, constrict (3d6+14), eye gouge, fascinating gaze, mythic power (6/day, surge +1d8), rend (2 claws, 3d6+21), rock throwing (200 ft.)
Spell-Like Abilities (CL 14th; concentration +14)
   Constant—arcane sight, detect scrying, true seeing
   At will—arcane eye, clairaudience/clairvoyance, status (DC 12), true strike
   3/day—quickened true strike
--------------------
Statistics
--------------------
Str 39, Dex 14, Con 23, Int 13, Wis 12, Cha 10
Base Atk +9; CMB +27 (+31 grapple); CMD 43
Feats Alertness[M], Combat Reflexes[M], Improved Initiative[M], Intimidating Prowess, Quicken Spell-Like Ability (true strike), Skill Focus (Perception), Weapon Focus (claw)
Skills Acrobatics +2 (+6 to jump), Climb +24, Handle Animal +6, Intimidate +30, Knowledge (history) +10, Perception +29 (+37 on vision-based checks), Sense Motive +23, Swim +24; Racial Modifiers +8 Perception on vision-based checks
Languages Aklo, Celestial, Common
--------------------
Ecology
--------------------
Environment any land
Organization solitary
Treasure standard
--------------------
Special Abilities
--------------------
Absolute Readiness (Ex) Never surprised or flat footed, and treats surprise rds as a normal rd.
Accurate Strikes (Ex) Ignore AC bonus/miss chance from anything less than total cover/concealment.
Alertness [Mythic] Use 1 power to treat your roll for Perception or Sense Motive as a natural 20.
All-Around Vision (Ex) You can see in all directions and cannot be flanked.
Combat Reflexes [Mythic] As a swift action, use 1 power for movement AoO vs. foes who already provoked one for moving.
Damage Reduction (10/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Cold (30) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Fire (30) You have the specified Energy Resistance against Fire attacks.
Eye Gouge (Ex) As a swift action on rend/pin, attempt dirty trick to blind foe (permanent if 10 greater than CMD).
Fascinating Gaze (40 feet, DC 16) (Su) Fascinate/daze foe for 5d6 rds (Will neg).
Frightful Presence (40 ft., 5d6 rounds, DC 16) Those in area of effect become frightened or shaken (Will neg.)
Grab: Claw (Gargantuan) (Ex) You can start a grapple as a free action if you hit with the designated weapon.
Immunity to Blindness You are immune to blindness.
Immunity to Dazzled You are immune to the dazzled condition.
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Limitless Vision (Ex) An argus takes no distance penalties on Perception checks.
Mistsight (Su) See through fog, mist and murky water without penalty
Quicken Spell-Like Ability (True Strike) Spell-like ability is cast as a swift action up to 3/day.
Rock Catching (Ex) You can catch rocks that are thrown at you with a successful Reflex save.
Rock Throwing (200 ft.) (Ex) You can throw big rocks. They hurt.
See in Darkness See perfectly in darkness of any kind, including magical darkness.
Surge (1d8) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Vulnerability to Fascination -4 penalty on saves vs. effects that cause fascination.
Vulnerability to Sleep -4 penalty on saves vs. effects that cause sleep.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!

**Comment by Lavaeolous** [comment]
- [ ] Added Support for Mythic Ranks
