### ISSUE TITLE
Can't import Bestiary 4 - Centaur Greenspeaker

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#165]
Can't import statblock:

Centaur Greenspeaker      CR 4
XP 1,200
Centaur shaman 2 (Pathfinder RPG Advanced Class Guide 35, Pathfinder RPG Bestiary 42)
NG Large monstrous humanoid
Init +6; Senses darkvision 60 ft.; Perception +11
--------------------
Defense
--------------------
AC 16, touch 12, flat-footed 13 (+3 armor, +2 Dex, +1 dodge, +1 natural, -1 size)
hp 39 (6 HD; 2d8+4d10+8)
Fort +2, Ref +6, Will +11
--------------------
Offense
--------------------
Speed 50 ft.
Melee mwk sickle +8 (1d6+3), 2 hooves +2 (1d6+1)
Ranged javelin +6 (1d6+3)
Space 10 ft.; Reach 5 ft.
Special Attacks channel positive energy 3/day (DC 13, 1d6), hex (ward[APG])
Shaman Spells Prepared (CL 2nd; concentration +6)
   1st—entangle (DC 15), goodberry, sleep (DC 15); detect undead[S]
   0 (at will)—detect poison, guidance, purify food and drink (DC 14), resistance
   S spirit magic spell; Spirit Life 
--------------------
Statistics
--------------------
Str 16, Dex 14, Con 12, Int 14, Wis 18, Cha 14
Base Atk +5; CMB +9; CMD 22 (26 vs. trip)
Feats Combat Casting, Dodge, Improved Initiative
Skills Acrobatics +2 (+10 to jump), Diplomacy +9, Handle Animal +9, Heal +10, Knowledge (geography) +3, Knowledge (nature) +9, Knowledge (planes) +7, Knowledge (religion) +7, Perception +11, Spellcraft +11, Survival +13
Languages Auran, Common, Elven, Sylvan, Terran
SQ spirit animal (owl named Spirit Animal), undersized weapons
Combat Gear wand of burning hands (CL 3rd, 11 charges), wand of charm animal (23 charges), healer's kit; Other Gear +1 leather armor, javelin (4), mwk sickle
--------------------
Special Abilities
--------------------
Combat Casting +4 to Concentration checks to cast while on the defensive.
Darkvision (60 feet) You can see in the dark (black and white only).
Empathic Link with Familiar (Su) You have an empathic link with your Arcane Familiar.
Familiar Bonus: +3 to sight-based Perception checks in shadows You gain the Alertness feat while your familiar is within arm's reach.
Shaman Channel Positive Energy 1d6 (3/day, DC 13) (Su) Positive energy heals the living and harms the undead; negative has the reverse effect.
Share Spells with Familiar Can cast spells with a target of "You" on the familiar with a range of touch.
Spirit Animal (spirit animal (owl named Spirit Animal)) If spirit animal is slain, cannot use spirit magic or prepare new spells.
Undersized Weapons (Ex) The creature uses manufactured weapons as if it were one size category smaller than the creature's actual size.
Ward +2 (1 at a time) (Su) Ward another, granting +2 to AC and saves until hit or fail a save.
--------------------
Hidden deep within the heart of most centaur lands lies their most sacred territory, a place these hybrid creatures call the First Pasture. Centaur greenspeakers hold sway in these spaces, delivering sermons in open fields under both the midday sun and the twilight sky. Here tribes celebrate weddings, harvests, and births under the sun's warm glow, and perform rites of adulthood, rituals to bring luck before a battle, and homages to the tribe's ancestors under the sparse light of the moon and stars. Of these celebrations, centaurs revere none more than the death rites their greenspeakers provide for fallen clan members. When the sun sets, the greenspeakers light a great pyre to release the deceased's spirit from her mortal flesh. After the pyre burns through the night and the sun's first rays crest the horizon, the fallen centaur's kin collect the ashes and fertilize the fields with them so that the dead may serve the world anew.

Centaur greenspeakers who cultivate the fields of the First Pasture are known as "Sowers of the Ash." Centaur clans trust these holy preachers to tend to the sacred meadows, where a kaleidoscope of wild flowers blooms from spring to the fading days of autumn. Centaurs use the blossoms as central decorations for their celebrations and ceremonies, and greenspeakers weave the remaining flowers into fragrant mantles that signal their rank in society; the more ornate a greenspeaker's mantle, the more experienced and venerated he is.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!

**Comment by Lavaeolous** [comment]
- [ ] Added Support for Spirits

- [ ] Reworked Parsing of Spellgroup Contexts (e.g. Spirit, Mystery, Domain etc.)
