### ISSUE TITLE
Can't import Bestiary 4 - Spirit Animal (Owl)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#166]
Can't import statblock:

Spirit Animal      CR –
Owl (Pathfinder RPG Bestiary 132)
N Tiny magical beast (animal)
Init +3; Senses low-light vision; Perception +13
--------------------
Defense
--------------------
AC 16, touch 15, flat-footed 13 (+3 Dex, +1 natural, +2 size)
hp 19 (1d8); fast healing 1
Fort +2, Ref +7, Will +9
Defensive Abilities improved evasion
--------------------
Offense
--------------------
Speed 10 ft., fly 60 ft. (average)
Melee 2 talons +10 (1d4-2)
Space 2 ft.; Reach 0 ft.
--------------------
Statistics
--------------------
Str 6, Dex 17, Con 11, Int 6, Wis 15, Cha 6
Base Atk +5; CMB +6; CMD 14
Feats Weapon Finesse[B]
Skills Acrobatics +3 (-5 to jump), Diplomacy +2, Fly +7, Handle Animal +2, Heal +5, Perception +13, Spellcraft +4, Stealth +15, Survival +8; Racial Modifiers +4 Perception, +4 Stealth
SQ empathic link
--------------------
Special Abilities
--------------------
Empathic Link (Su) You have an empathic link with your master.
Fast Healing 1 (Ex) Heal damage every round unless you are killed.
Fly (60 feet, Average) You can fly!
Improved Evasion (Ex) No damage on successful reflex save; half on failed save.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Share Spells Spells with a target of "You" can be delivered by a familiar with a range of touch.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!

**Comment by Lavaeolous** [comment]
Added Support for "CR -"
