### ISSUE TITLE
Can't import Bestiary 4 - Cernunnos (Empyreal Lord)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#167]
Can't import statblock:

Cernunnos (Empyreal Lord)      CR 30
XP 9,830,400
Cernunnos (Pathfinder RPG Bestiary 4 88)
CG Large outsider (azata, chaotic, extraplanar, good)
Init +16; Senses blindsense 60 ft., darkvision 60 ft., detect evil, detect poison, discern lies, low-light vision, true seeing; Perception +43
Aura primal aura (30 ft.)
--------------------
Defense
--------------------
AC 48, touch 22, flat-footed 35 (+12 Dex, +1 dodge, +26 natural, -1 size)
hp 663 (34d10+476); regeneration 10 (evil artifacts, effects, and spells)
Fort +25, Ref +31, Will +25
Defensive Abilities freedom of movement, lightning rod, unbound; DR 15/epic, 15/evil; Immune ability damage, ability drain, charm, compulsion, death effects, electricity, energy drain, petrification; Resist cold 30, fire 30; SR 41
--------------------
Offense
--------------------
Speed 40 ft., fly 60 ft. (average)
Melee +5 holy cold iron club +48/+43/+38/+33 (1d8+18 plus 2d6 vs. evil) or
   gore +43 (2d8+18)
Ranged +5 evil outsider-bane composite longbow +51/+46/+41/+36 (2d6+5/19-20/×3 plus 2d6 vs. evil outsider)
Space 10 ft.; Reach 10 ft.
Special Attacks greater slaying arrow, horned lord's charge, powerful charge (gore, 4d8+13 and horned lord's charge), wild shape (as a 20th level druid)
Spell-Like Abilities (CL 20th; concentration +25)
   Constant—detect evil, detect poison, discern lies (DC 19), freedom of movement, true seeing
   At will—greater teleport, haste[M], true strike[M]
   3/day—break enchantment[M], breath of life[M] (DC 19), dimensional anchor
   1/day—discern location, mage's disjunction[M] (DC 24), time stop[M]
Druid Spells Prepared (CL 20th; concentration +26)
   9th—elemental swarm, foresight, summon nature's ally IX (2)
   8th—control plants (DC 24), repel metal or stone, sunburst (DC 24), whirlwind (DC 24)
   7th—control weather, creeping doom (DC 23), heal, sunbeam (DC 23)
   6th—antilife shell, greater dispel magic (2), move earth, wall of stone
   5th—atonement, baleful polymorph (DC 21), death ward, transmute rock to mud, wall of thorns
   4th—cure serious wounds (2), freedom of movement, rusting grasp, true form[APG] (DC 20)
   3rd—call lightning (DC 19), cure moderate wounds, neutralize poison (2), remove disease
   2nd—chill metal (DC 18), fog cloud, heat metal (DC 18), resist energy (2), lesser restoration
   1st—calm animals (2, DC 17), cure light wounds (2), pass without trace (2)
   0 (at will)—create water, mending, purify food and drink (DC 16), read magic
   M Cernunnos can use the mythic version of this ability in his realm.
--------------------
Statistics
--------------------
Str 29, Dex 35, Con 39, Int 18, Wis 22, Cha 21
Base Atk +34; CMB +44; CMD 67
Feats Combat Reflexes, Deadly Aim, Dodge, Improved Critical (longbow), Improved Critical (scimitar), Improved Initiative, Improved Precise Shot, Mobility, Point-Blank Shot, Power Attack, Precise Shot, Quick Draw, Rapid Shot, Shot On The Run, Weapon Focus (club), Weapon Focus (gore), Weapon Focus (longbow)
Skills Acrobatics +46 (+50 to jump), Diplomacy +22, Disguise +22, Fly +10, Handle Animal +22, Intimidate +22, Knowledge (geography) +24, Knowledge (nature) +24, Knowledge (planes) +24, Knowledge (religion) +21, Perception +43, Ride +32, Sense Motive +43, Stealth +45, Survival +43, Swim +26
Languages Celestial, Draconic, Infernal, Sylvan; truespeech
SQ change shape (any humanoid; alter self), perfect archer, seed of life
Other Gear +5 evil outsider-bane composite longbow, +5 holy cold iron club
--------------------
Ecology
--------------------
Environment any forest or plain (elysium)
Organization unique
Treasure standard (+5 holy cold iron club, +5 evil outsider bane longbow, other treasure)
--------------------
Special Abilities
--------------------
Blindsense (60 feet) (Ex) Sense things and creatures without seeing them.
Change Shape (any humanoid; alter self) (Su) You can change your form.
Combat Reflexes (13 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (15/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Damage Reduction (15/evil) You have Damage Reduction against all except Evil attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Deadly Aim -9/+18 Trade a penalty to ranged attacks for a bonus to ranged damage.
Energy Resistance, Cold (30) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Fire (30) You have the specified Energy Resistance against Fire attacks.
Fly (60 feet, Average) You can fly!
Greater Slaying Arrow (DC 32) (Su) Can create any single greater slaying arrow over 1 min.
Horned Lord's Charge (DC 41) (Ex) Foe hit by powerful charge is exhausted, sickened, or stunned 1d4 rds (Fort neg).
Immunity to Ability Damage Immunity to ability damage
Immunity to Ability Drain Immunity to ability drain
Immunity to Charm You are immune to charm effects.
Immunity to Compulsion You are immune to compulsion.
Immunity to Death Effects You are immune to death effects.
Immunity to Electricity You are immune to electricity damage.
Immunity to Energy Drain Immune to energy drain
Immunity to Petrification You are immune to Petrification.
Improved Precise Shot Ignore AC bonuses and miss chance from anything less than total cover/concealment.
Lightning Rod (Su) Absorb & negate any electricity effect including him, then grant shock to all allies' weapons for 1 rd.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Mobility +4 to AC vs. AoO provoked by moving out of or through a threatened area.
Perfect Archer (Ex) No AoO for firing bows in melee, and threaten squares normally.
Point-Blank Shot +1 to attack and damage rolls with ranged weapons at up to 30 feet.
Power Attack -9/+18 You can subtract from your attack roll to add to your damage.
Powerful Charge (Gore, 4d8+13 and horned lord's charge) (Ex) Your charge attacks deal additional damage.
Precise Shot You don't get -4 to hit when shooting or throwing into melee.
Primal Aura (Su) Any summon nature's ally gives +4 Str & Con to summons in range and obeys Cernunnos over all.
Quick Draw Draw weapon as a free action (or move if hidden weapon). Throw at full rate of attacks.
Rapid Shot You get an extra attack with ranged weapons. Each attack is at -2.
Regeneration 10 (evil artifacts, effects, and spells) Heal HP quickly and cannot die.
Seed of Life (5/day) (Sp) Grant +2 bonus to save vs. neg energy & death effects. Can expend for heal on self, or mass cure serious wounds.
Shot on the Run When attacking with a ranged weapon, you can move - attack - move.
Spell Resistance (41) You have Spell Resistance.
Truespeech (Su) Speak with any creature that has a language.
Unbound (Su) Immune to any effect restricting or forcing extradimensional movement, unless allow it.
Wild Shape (as a 20th level druid, At will) (Su) Can take the form of an animal, plant, or elemental.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!

**Comment by Lavaeolous** [comment]
- [ ] Added Support for "Lesser" Spell Version
