### ISSUE TITLE
Can't import Bestiary 4 - Cthulhu (Great Old One)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#173]
Can't import statblock:

Cthulhu (Great Old One)      CR 30/MR 10
XP 9,830,400
Cthulhu (Pathfinder RPG Bestiary 4 138)
CE Colossal aberration (chaotic, evil, Great Old One)
Init +15; Senses darkvision 60 ft., true seeing; Perception +52
Aura unspeakable presence (300 ft., DC 40)
--------------------
Defense
--------------------
AC 49, touch 29, flat-footed 44 (+12 deflection, +5 Dex, +10 insight, +20 natural, -8 size)
hp 774 (36d8+612); fast healing 30
Fort +29, Ref +29, Will +33
Defensive Abilities freedom of movement, immortality, insanity (DC 40), non-euclidean; DR 20/epic, 20/lawful; Immune ability damage, ability drain, aging, cold, death effects, disease, energy drain, mind-affecting effects, paralysis, petrification; Resist acid 30, electricity 30, fire 30, sonic 30; SR 41
--------------------
Offense
--------------------
Speed 60 ft., fly 200 ft. (average), swim 60 ft.
Melee 2 claws +42 (4d6+23/19-20 plus grab), 4 tentacles +42 (2d10+34/19-20 plus grab)
Space 40 ft.; Reach 40 ft.
Special Attacks cleaving claws, constrict (3d6+23), dreams of madness, mythic power (10/day, surge +1d12), tentacles, trample (2d8+34, DC 51)
Spell-Like Abilities (CL 30th; concentration +42)
   Constant—freedom of movement, true seeing
   At will—astral projection, control weather[M], dream[M], greater dispel magic, greater teleport, insanity (DC 29), nightmare[M] (DC 29), sending[M]
   3/day—antipathy (DC 30), demand (DC 30), gate, quickened feeblemind (DC 27), weird (DC 31)
   1/day—implosion (DC 31), summon (level 9, 2d4 star-spawn of Cthulhu 100%), symbol of insanity (DC 30), wish[M]
   M mythic spell
--------------------
Statistics
--------------------
Str 56, Dex 21, Con 45, Int 31, Wis 36, Cha 34
Base Atk +27; CMB +58 (+60 bull rush, +62 grapple, +62 sunder); CMD 95 (97 vs. bull rush, 97 vs. sunder)
Feats Ability Focus (nightmare), Awesome Blow, Combat Reflexes, Craft Wondrous Item, Critical Focus, Flyby Attack, Greater Sunder, Greater Vital Strike, Hover, Improved Bull Rush, Improved Critical (claw), Improved Critical (tentacle), Improved Sunder, Improved Vital Strike, Power Attack, Quicken Spell-Like Ability (feeblemind), Staggering Critical, Vital Strike
Skills Acrobatics +5 (+17 to jump), Fly +36, Knowledge (arcana) +49, Knowledge (dungeoneering) +46, Knowledge (engineering) +46, Knowledge (geography) +46, Knowledge (history) +46, Knowledge (nature) +46, Knowledge (planes) +46, Knowledge (religion) +46, Perception +52, Sense Motive +49, Spellcraft +49, Swim +70, Use Magic Device +48
Languages Aklo; telepathy 300 ft.
SQ compression, greater starflight, otherworldly insight, powerful blows (tentacle)
--------------------
Ecology
--------------------
Environment any (r'lyeh)
Organization solitary (unique)
Treasure triple
--------------------
Special Abilities
--------------------
Awesome Blow As standard action, damage and move smaller foe 10 ft. +1d6 dam if collide with something.
Cleaving Claws (Ex) Each claw attack targets a 10 ft square, roll once vs. all in area.
Combat Reflexes (6 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Compression (Ex) Move through areas 1/4 normal space without squeezing or 1/8 while squeeze.
Critical Focus +4 to confirm critical hits.
Damage Reduction (20/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Damage Reduction (20/lawful) You have Damage Reduction against all except Lawful attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Dreams of Madness (DC 40) (Su) Target of nightmare with ranks in craft or perform gain an insanity (Will neg).
Energy Resistance, Acid (30) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Electricity (30) You have the specified Energy Resistance against Electricity attacks.
Energy Resistance, Fire (30) You have the specified Energy Resistance against Fire attacks.
Energy Resistance, Sonic (30) You have the specified Energy Resistance against Sonic attacks.
Fast Healing 30 (Ex) Heal damage every round unless you are killed.
Fly (200 feet, Average) You can fly!
Flyby Attack You can take a standard action during your move action while flying.
Grab: Claw or Tentacle (Colossal) (Ex) You can start a grapple as a free action if you hit with the designated weapon.
Greater Starflight (Su) Can fly through the void of space at incredible speed.
Greater Sunder When destroying an item, extra damage is transferred to the wielder.
Hover Can hover in place without Fly checks, and kick up dust cloud if within 20 ft of ground.
Immortality (DC 45) (Ex) If killed, become mist that nauseates d10 rds (Fort neg). Ressurect but staggered in 2d6 rds. Return to tomb if slain while staggered.
Immunity to Ability Damage Immunity to ability damage
Immunity to Ability Drain Immunity to ability drain
Immunity to Aging You are immune to aging effects.
Immunity to Cold You are immune to cold damage.
Immunity to Death Effects You are immune to death effects.
Immunity to Disease You are immune to diseases.
Immunity to Energy Drain Immune to energy drain
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Paralysis You are immune to paralysis.
Immunity to Petrification You are immune to Petrification.
Improved Bull Rush You don't provoke attacks of opportunity when bull rushing.
Improved Sunder You don't provoke attacks of opportunity when sundering.
Insanity (DC 40) (Ex) Those interacting with thoughts directly suffer insanity, or can focus telepathy as a standard action to force mental contact.
Non-Euclidean (DC 40) (Ex) All foes' attacks have a 50% miss chance unless use true seeing, which inflicts insanity (Will neg).
Otherworldly Insight (Ex) All Great Old Ones gain a +10 insight bonus on Initiative checks and to AC.
Power Attack -7/+14 You can subtract from your attack roll to add to your damage.
Powerful Blows (Ex) The specified attack adds 1-1/2 times your Str bonus on damage rolls
Quicken Spell-Like Ability (Feeblemind) Spell-like ability is cast as a swift action up to 3/day.
Spell Resistance (41) You have Spell Resistance.
Staggering Critical (DC 37) Critical hit staggers target
Summon (level 9, 2d4 star-spawn of Cthulhu 100%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Surge (1d12) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Swim (60 feet) You have a Swim speed.
Telepathy (300 feet) (Su) Communicate telepathically if the target has a language.
Tentacles (Ex) Cthulhu’s tentacles are a primary attack.
Unspeakable Presence (DC 40) (Su) Foes in range die of fear (Fort part), on save staggered d6 rds.
Vital Strike Standard action: x2 weapon damage dice.

**Comment by Lavaeolous** [comment]
I don't think the converter is Mythic compatible right now :)

**Comment by adventuremagic123** [comment]
Ok.  It takes a lot of effort on my end to do these one-by-one, so I'll let you filter out the one's that matter vs the ones that don't.

You guys have done a great job!  Your module is very much appreciated!

I can't use Foundry VTT without it!

⁣--
Mark​

**Comment by Lavaeolous** [comment]
Check this out: https://github.com/JamesDeVore/pf1_Bestiary
James created a tool to feed whole bestiaries into the converter mostly automated. A whole bunch should be included in the current version of the system.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!
