### ISSUE TITLE
Can't import Bestiary 4 - Drakainia

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#175]
Can't import statblock:

Drakainia      CR 25/MR 10
XP 1,638,400
Drakainia (Pathfinder RPG Bestiary 4 76)
NE Huge aberration (mythic)
Init +9; Senses darkvision 120 ft., lifesense 120 ft., true seeing; Perception +39
Aura gestation (30 ft.)
--------------------
Defense
--------------------
AC 48, touch 13, flat-footed 43 (+5 Dex, +35 natural, -2 size)
hp 642 (25d8+530); regeneration 10 (negative energy)
Fort +28, Ref +15, Will +21
DR 10/epic; Immune bleed, disease, poison, polymorph; SR 36
--------------------
Offense
--------------------
Speed 50 ft., climb 30 ft., swim 30 ft.
Melee 2 claws +32 (4d8+14/17-20/×4), gore +28 (4d6+7), 4 tentacles +29 (2d6+7)
Space 15 ft.; Reach 15 ft. (20 ft. with claws)
Special Attacks channel positive energy 18/day (DC 35, 10d6), impregnate surrogate, mythic power (10/day, surge +1d12), razor claws, well of life
Spell-Like Abilities (CL 20th; concentration +35)
   Constant—freedom of movement, true seeing
   At will—dimension door
   3/day—antilife shell, break enchantment, contagion (DC 29), dimension door, quickened cure serious wounds
   1/day—antimagic field, destruction (DC 32), regenerate[M]
--------------------
Statistics
--------------------
Str 38, Dex 20, Con 46, Int 29, Wis 21, Cha 41
Base Atk +18; CMB +34; CMD 49 (can't be tripped)
Feats Combat Casting, Combat Reflexes[M], Great Fortitude[M], Improved Initiative, Iron Will[M], Lightning Reflexes[M], Multiattack, Quick Channel[UM], Quicken Spell-Like Ability (cure serious wounds), Selective Channeling, Skill Focus (Perception), Weapon Focus (claw)[M], Weapon Focus (tentacle)
Skills Acrobatics +5 (+13 to jump), Bluff +40, Climb +45, Diplomacy +40, Handle Animal +20, Heal +30, Intimidate +43, Knowledge (arcana) +34, Knowledge (dungeoneering) +34, Knowledge (nature) +34, Perception +39, Sense Motive +30, Spellcraft +37, Swim +50, Use Magic Device +40
Languages Abyssal, Aklo, Aquan, Auran, Celestial, Common, Draconic, Ignan, Infernal, Terran
SQ birth spawn, invert birth, polymorphism, transfer suffering
--------------------
Ecology
--------------------
Environment any
Organization solitary
Treasure double
--------------------
Special Abilities
--------------------
Birth Spawn (21 CR/day) (Ex) As a full rd action, give birth to Large or smaller creature of choice with a mutation.
Climb (30 feet) You have a Climb speed.
Combat Casting +4 to Concentration checks to cast while on the defensive.
Combat Reflexes [Mythic] As a swift action, use 1 power for movement AoO vs. foes who already provoked one for moving.
Damage Reduction (10/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Darkvision (120 feet) You can see in the dark (black and white only).
Drakainia Channel Positive Energy 10d6 (18/day, DC 35) (Su) Positive energy heals the living and harms the undead; negative has the reverse effect.
Fortification 75% You have a chance to negate critical hits on attacks.
Gestation Aura (30 feet) (Su) Poisons/diseases have onset 1 rd & freq 1/min. Pregnancies gestate in 2d4 rds, and gain 1 mutation.
Great Fortitude [Mythic] Roll Fort save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Immunity to Bleed You are immune to bleed.
Immunity to Disease You are immune to diseases.
Immunity to Poison You are immune to poison.
Immunity to Polymorph You are immune to Polymorph effects.
Impregnate Surrogate (DC 40) (Su) Grapple check to impregnate pinned/helpless foe (mythic can save, Fort neg). Nauseated 2d4 rds, then 10d6 dam.
Invert Birth (Su) Can target dimension door to any spawn in 1 mi, destroying it.
Iron Will [Mythic] Roll Will save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Lifesense (120 ft.) (Ex) Sense living things and creatures without seeing them.
Lightning Reflexes [Mythic] Roll Ref save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Polymorphism (Ex) The spawn gestating inside the drakainia constantly alter her internal construction, making her immune to bleed, disease, poison, and polymorph effects. When she is subject to a critical hit or a sneak attack, this polymorphism grants her a 75% chanc
Quick Channel Channel energy faster by expending more uses
Quicken Spell-Like Ability (Cure Serious Wounds) Spell-like ability is cast as a swift action up to 3/day.
Razor Claws (Ex) A drakainia's claws are razor sharp with a critical threat range of 17-20 and a critical multiplier of x4.
Regeneration 10 (negative energy) Heal HP quickly and cannot die.
Selective Channeling Exclude targets from the area of your Channel Energy.
Spell Resistance (36) You have Spell Resistance.
Surge (1d12) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Swim (30 feet) You have a Swim speed.
Transfer Suffering (Su) As a swift action, transfer negative spell effect or condition to spawn in aura.
Weapon Focus [Mythic, Claw] 1 MP: As a swift action, add half tier to attack with selected weapon.
Well of Life (Su) When channeling positive energy, use 1 power to maximize healing.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!

**Comment by Lavaeolous** [comment]
MR
