### ISSUE TITLE
Can't import witchfire

### ISSUE THREAD

**Issue by grankless** [Lavaeolous/PF1-StatBlock-Converter-Module#18]
https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Witchfire 
https://i.imgur.com/HMmwQxx.png

Spits out this error. Yes, I *am* going to break your poor module constantly.

**Comment by grankless** [comment]
Upon further investigation - this seems to happen with any statblock that has a - for a stat.

**Comment by Lavaeolous** [comment]
That happens in the skills-section of parsing. I found the culprit: It's the Knowledge (any two) part.

I currently look for "subskill", "list of subskills" or "any" for knowledge. Seems i have to include "any "+string-that-i-have-to-convert-to-decimal as well ;)

Feel free to break it!

**Comment by grankless** [comment]
So silly that that's even a thing! I guess I just have bad luck in picking what to try and convert.

**Comment by Lavaeolous** [comment]
I've pushed v0.2.3 - Knowledge Skills with (any X) should be fixed. I'd appreciate it, if you could test that again!

**Comment by Lavaeolous** [comment]
There were quite a few other issues with the Witchfire, none the least that the converter always thought it would have the class "witch" :)

They should be fixed in the next update.
