### ISSUE TITLE
Can't import Bestiary 4 - Walkena

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#206]
Can't import statblock:

Walkena      CR 16
XP 76,800
Male mummified human oracle 12/Hierophant 9 (Pathfinder RPG Advanced Player's Guide 42, Pathfinder RPG Bestiary 4 196)
LE Small undead (humanoid, human)
Init +25; Senses darkvision 60 ft.; Perception +15
Aura frightful presence (30 ft., DC 20, 1 round)
--------------------
Defense
--------------------
AC 24, touch 17, flat-footed 19 (+3 armor, +1 deflection, +3 Dex, +2 dodge, +4 natural, +1 size)
hp 241 (12d8+180)
Fort +16, Ref +11, Will +14
Defensive Abilities hard to kill, mythic saving throws, unchanging[MA], unstoppable; DR 5/—; Immune undead traits; Resist fire 20
Weaknesses vulnerability
--------------------
Offense
--------------------
Speed 20 ft.
Melee +1 spear +13/+8 (1d6+4/×3) or
   slam +12 (1d4+3)
Special Attacks burst of vengeance, divine surge (inspired spell), dust stroke, faith's reach[MA], force of will, inspired spell[MA], mythic power (21/day, surge +1d10)
Oracle Spells Known (CL 12th; concentration +22)
   6th (5/day)—blade barrier[M] (DC 26), fire seeds, mass inflict moderate wounds (DC 26)
   5th (7/day)—greater command (DC 25), flame strike[M] (DC 26), mass inflict light wounds (DC 25), summon monster V
   4th (8/day)—freedom of movement, inflict critical wounds[M] (DC 24), summon monster IV, unholy blight (DC 24), wall of fire[M]
   3rd (8/day)—dispel magic[M], fireball[M] (DC 24), inflict serious wounds (DC 23), invisibility purge, prayer, searing light
   2nd (9/day)—death knell (DC 22), desecrate, hold person (DC 22), inflict moderate wounds (DC 22), communal protection from good[UC], resist energy, silence (DC 22)
   1st (13/day)—burning hands[M] (DC 22), divine favor[M], inflict light wounds (DC 21), obscuring mist, sanctuary (DC 21), shield of faith, sun metal[UC] (DC 22)
   0 (at will)—bleed (DC 20), create water, detect magic, guidance, light, purify food and drink (DC 20), read magic, resistance, spark[APG] (DC 20)
   Mystery Flame
   M mythic spell
--------------------
Statistics
--------------------
Str 14, Dex 17, Con —, Int 10, Wis 14, Cha 30
Base Atk +9; CMB +10; CMD 26
Feats Dodge[M], Elemental Focus (fire)[APG], Extra Revelation[APG], Extra Revelation[APG], Improved Initiative[M], Improved Natural Attack (slam)[B], Iron Will[M], Lightning Reflexes[M], Toughness[M]
Skills Acrobatics +3 (-1 to jump), Diplomacy +25, Heal +7, Intimidate +25, Knowledge (history) +12, Knowledge (planes) +8, Knowledge (religion) +8, Perception +15, Spellcraft +15, Stealth +12; Racial Modifiers +4 Stealth
Languages Ancient Osiriani, Common, Ignan, Polyglot; tongues (understand)
SQ amazing initiative, divine potency[MA], divine source[MA], divine source[MA], flexible counterspell[MA], immortal, mythic spellcasting[MA], oracle's curse (tongues [ignan, osiriani, ancient]), recuperation, revelations (fire breath, firestorm, gaze of flames, heat aura, molten skin, wings of fire)
Combat Gear scroll of inflict serious wounds, scroll of inflict serious wounds, scroll of inflict serious wounds, scroll of inflict serious wounds, scroll of mass cure moderate wounds, scroll of mass cure moderate wounds, scroll of mass cure moderate wounds, scroll of mass cure moderate wounds; Other Gear +2 padded armor, +1 spear, cloak of resistance +2, headband of alluring charisma +2, ring of protection +1
--------------------
Special Abilities
--------------------
Amazing Initiative (1/round) (Ex) As a free action, use 1 power to gain an extra standard action (can't be used to cast a spell).
Burst of Vengeance (2/day) (Su) As a swift action, act as if affected by a haste spell for 1 round.
Damage Reduction (5/-) You have Damage Reduction against all attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Divine Source (3 domains, 2 subdomains) (Su) You can grant divine spells to those who follow your cause.
Dodge [Mythic] Use 1 power to gain a +10 dodge bonus against one attack.
Dust Stroke (Su) Creatures killed by natural attacks disintegrate into a cloud of dust and ash.
Elemental Focus (Fire) +1 DC to spells that deal damage of the chosen energy.
Energy Resistance, Fire (20) You have the specified Energy Resistance against Fire attacks.
Faith's Reach (Su) Your touch divine spells have a range of 30 ft.
Fire Breath (15 ft. cone, 12d4, 3/day, DC 26) (Su) 15 ft. cone of flame deals 12d4 fire damage, Ref half.
Firestorm (12d6, 10 rd, 1/day, DC 26) (Su) Create 12 10' cubes of fire, dealing 12d6 fire damage, Ref. half, for 10 rds.
Flexible Counterspell (Su) As immediate action, use 1 power and spell of same or higher level to counterspell.
Force of Will (Ex) As an immediate action, use 1 power to reroll any d20, or force non-mythic to reroll.
Frightful Presence (30 ft., 1 round, DC 20) Those in area of effect become frightened or shaken (Will neg.)
Gaze of Flames (Clairvoyance 120 ft., 12 rounds/day) (Su) See through fire, fog, and smoke, or use a flame within 120 ft for clairvoyance.
Hard to Kill (Ex) Automatically stabilize when dying, and only die at neg Con x 2.
Heat Aura (6d4 fire damage, 10 feet, 3/day, DC 26) (Su) As a swift action, 6d4 fire dam to all in 10 ft (Ref half) and gain 20% concealment for 1 rd.
Immortal (Su) Ressurrect next day, unless killed by mythic foe's crit, or an epic weapon.
Immunity to Non-Mythic Petrification You are immune to non-mythic petrification.
Immunity to Non-Mythic Polymorph You are immune to non-mythic polymorph effects.
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Inspired Spell (Su) Use 1 power, cast one divine spell from your class spell list at +2 CL, it doesn't need to be known/memorized.
Iron Will [Mythic] Roll Will save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Lightning Reflexes [Mythic] Roll Ref save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Mythic Saving Throws (Ex) A successful save negates all effects from a non-mythic source.
Recuperation (Ex) Fully heal after 8 hrs rest, use 1 power and 1 hr to heal half and restore all non-mythic abilities.
Surge (1d10) (Su) Use 1 power to increase any d20 roll by the listed amount.
Tongues (Ignan, Osiriani, Ancient) You can only understand and speak two languages in combat.
Tongues (understand) (Ex) Understand any language.
Toughness [Mythic] Gain DR 10/epic when below 0 hit points.
Unchanging (Su) Immune to non-mythic polymorph and petrfication effects.
Undead Traits Undead have many immunities.
Unstoppable (Ex) As a free action, use 1 power to end one listed condition on yourself.
Vulnerability (Electricity) Vulnerable to the indicated type of energy.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of about 10:30 am. I used Hero Lab to produce this statblock. For greater accuracy, you might want to use one of the online resources. Hero Lab can truncate some of the text -- or inject errors due to a lack of data. All the other statblocks from Bestiary 4 imported -- a total of more than 85% imported!

**Comment by Lavaeolous** [comment]
- [ ] Add "Mystery" to Spellparsing (in addition to Domains, etc.)
