### ISSUE TITLE
Can't import Bestiary 5 - Ancient One

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#219]
Can't import statblock:

Ancient One      CR 24/MR 2
XP 1,228,800
Invincible hundun (Pathfinder RPG Bestiary 5 144, Pathfinder RPG Mythic Adventures 224)
CE Large aberration (chaotic, extraplanar)
Init +10; Senses blindsense 300 ft., detect law; Perception +36
--------------------
Defense
--------------------
AC 41, touch 23, flat-footed 35 (+8 deflection, +6 Dex, +18 natural, -1 size)
hp 380 (27d8+259)
Fort +18, Ref +23, Will +21; second save
Defensive Abilities block attacks, entropic mind, evasion, negative energy affinity, spacetime shifting; DR 10/epic, 15/lawful, 15/piercing; Immune aging, cold, disease, mind-affecting effects, petrification, poison; Resist acid 15, electricity 15, fire 30; SR 32
--------------------
Offense
--------------------
Speed 60 ft.; air walk
Melee unarmed strike +32/+32/+27/+27/+22/+22/+17 (4d8+12/19-20 plus 1d6 negative energy)
Space 10 ft.; Reach 10 ft.
Special Attacks befuddling strike (DC 29, 6/day), punishing kick (DC 29, 6/day), strange attractor
Spell-Like Abilities (CL 21st; concentration +29)
   Constant—air walk, detect law
   At will—chaos hammer (DC 22), dimension door, enervation, greater dispel magic, mass inflict moderate wounds (DC 24), plane shift (DC 25)
   3/day—disintegrate (DC 24), quickened dimension door, quickened mass inflict moderate wounds (DC 24), word of chaos (DC 25)
   1/day—orb of the void[UM] (DC 26)
--------------------
Statistics
--------------------
Str 34, Dex 22, Con 29, Int 18, Wis 23, Cha 27
Base Atk +20; CMB +33; CMD 57
Feats Befuddling Strike[ACG], Blind-fight, Combat Reflexes, Dimensional Agility[UC], Dimensional Assault[UC], Dimensional Dervish[UC], Greater Blind-fight[APG], Improved Blind-fight[APG], Improved Critical (unarmed strike), Improved Initiative, Improved Unarmed Strike[B], Punishing Kick[B, APG], Quicken Spell-Like Ability (dimension door), Quicken Spell-Like Ability (mass inflict moderate wounds), Weapon Focus (unarmed strike)
Skills Acrobatics +36 (+48 to jump), Climb +30, Escape Artist +36, Intimidate +38, Knowledge (planes) +22, Perception +36, Sense Motive +27, Spellcraft +22, Stealth +32, Swim +30
Languages Abyssal, Aklo, Protean (can't speak); telepathy 300 ft.
SQ faceless, no breath
--------------------
Ecology
--------------------
Environment any (material plane)
Organization solitary, pair, or mob (3–5)
Treasure none
--------------------
Special Abilities
--------------------
Befuddling Strike (6/day, DC 29) (Ex) When the rogue deals sneak attack damage against an opponent, that opponent takes a –2 penalty on attack rolls against the rogue for 1d4 rounds.
Befuddling Strike (DC 29) You can confuse an opponent for 1d4 rds with an unarmed attack.
Blind-Fight Re-roll misses because of concealment, other benefits.
Blindsense (300 feet) (Ex) Sense things and creatures without seeing them.
Block Attacks (1/round) (Ex) When hit by an attack, if you succeed with a melee attack at your highest bonus vs. the attack result, the attack misses.
Combat Reflexes (7 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (10/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Damage Reduction (15/lawful) You have Damage Reduction against all except Lawful attacks.
Damage Reduction (15/piercing) You have Damage Reduction against all except Piercing attacks.
Dimensional Agility May take any additional actions remaining after using dimension door or abundant step
Dimensional Assault May use dimension door or abundant step as part of a charge action
Dimensional Dervish During full-attack action, you may cast dimension door or use abundant step as a swift action
Energy Damage: Unarmed strike (1d6 negative energy) (Ex) The creature's attack or attacks deal the specified amount of energy damage in addition to their normal damage.
Energy Resistance, Acid (15) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Electricity (15) You have the specified Energy Resistance against Electricity attacks.
Energy Resistance, Fire (30) You have the specified Energy Resistance against Fire attacks.
Entropic Mind (DC 31) (Ex) Any foe attempting to use mind-affecting effect takes 1d4 temp neg levels (Will neg).
Evasion (Ex) If succeed on Reflex save for half dam, take none instead.
Faceless (Ex) Blind and deaf, and is immune to effects that depend on sight or hearing.
Greater Blind-Fight Total conceal is 20% miss, and pinpointed invisible foes gain no ranged att benefits.
Immunity to Aging You are immune to aging effects.
Immunity to Cold You are immune to cold damage.
Immunity to Disease You are immune to diseases.
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Petrification You are immune to Petrification.
Immunity to Poison You are immune to poison.
Improved Blind-Fight Ignore partial conceal, and pinpointed invisible foes in 30' gain no ranged att benefits.
Improved Unarmed Strike Unarmed strikes don't cause attacks of opportunity, and can be lethal.
Negative Energy Affinity (Ex) You are alive, but react to positive/negative energy as though you were undead.
No Breath (Ex) The monster doesn't breathe and is immune to effects that require breathing.
Punishing Kick (Push 20 ft, 6/day, DC 29) (Ex) A hungry ghost monk gains Punishing Kick as a bonus feat, even if he does not meet the prerequisites. At 10th level, and every five levels thereafter, the monk can push the target of his Punishing Kick an additional 5 feet (10 feet at 10th level, 15 
Punishing Kick (Push 25', 6/day, DC 29) You can push or knock down an opponent with an unarmed attack.
Quicken Spell-Like Ability (Dimension Door) Spell-like ability is cast as a swift action up to 3/day.
Quicken Spell-Like Ability (Inflict Moderate Wounds, Mass) Spell-like ability is cast as a swift action up to 3/day.
Spacetime Shifting (Ex) All attacks vs. this creature have a 20% miss chance.
Spell Resistance (32) You have Spell Resistance.
Strange Attractor (DC 31) (Sp) As a move action, item moves 60 ft, if in foe's square K.O. 1 rd (Will part). Foes must save to move away if in 60 ft.
Telepathy (300 feet) (Su) Communicate telepathically if the target has a language.
Unarmed Strikes (Ex) Unarmed strikes can flurry, and bypass DR as chaotic, magic, and adamantine weapons.

**Comment by Lavaeolous** [comment]
Combination of "Mass" Spell with Metamagic
