### ISSUE TITLE
Can't import Bestiary 5 - Anunnaki

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#220]
Can't import statblock:

Anunnaki      CR 18/MR 7
XP 153,600
Anunnaki (Pathfinder RPG Bestiary 5 28)
N Large monstrous humanoid (mythic, shapechanger)
Init +16; Senses darkvision 60 ft., lifesense, true seeing; Perception +31
--------------------
Defense
--------------------
AC 35, touch 22, flat-footed 30 (+8 deflection, +5 Dex, +13 natural, -1 size)
hp 320 (20d10+210); regeneration 10 (epic weapons)
Fort +15, Ref +17, Will +20; +8 vs. mind-affecting effects
Defensive Abilities morphic anatomy, psychic warding, unstoppable[MA]; DR 20/epic; Immune poison; Resist acid 20, cold 20, electricity 20, sonic 20
--------------------
Offense
--------------------
Speed 50 ft., fly 60 ft. (good)
Melee primal chisel +30/+25/+20/+15 (3d6+9/15-20 plus devolution), bite +26 (1d8+4), 4 wings +26 (1d6+4)
Space 10 ft.; Reach 10 ft.
Special Attacks devolution (DC 28), mythic magic 3/day, mythic power (9/day, surge +1d10)
Spell-Like Abilities (CL 20th; concentration +28)
   Constant—true seeing
   At will—etherealness, greater teleport (self plus 50 lbs. of objects only), mental block[OA] (DC 20), mindlink[OA]
   5/day—greater dispel magic
   3/day—primal regression[OA] (DC 24), quickened baleful polymorph (DC 23)
   1/day—divide mind[OA], overwhelming presence[UM] (DC 27)
--------------------
Statistics
--------------------
Str 29, Dex 20, Con 24, Int 27, Wis 27, Cha 26
Base Atk +20; CMB +30 (+32 bull rush); CMD 53 (55 vs. bull rush)
Feats Combat Casting, Extra Mythic Power[M], Great Fortitude[M], Improved Bull Rush, Improved Critical (primal chisel), Improved Great Fortitude, Improved Initiative[M], Multiattack, Power Attack[M], Quicken Spell-Like Ability (baleful polymorph), Weapon Focus (primal chisel)
Skills Acrobatics +5 (+13 to jump), Bluff +18, Diplomacy +23, Fly +25, Heal +28, Intimidate +26, Knowledge (arcana) +28, Knowledge (dungeoneering) +16, Knowledge (engineering) +16, Knowledge (geography) +13, Knowledge (history) +16, Knowledge (local) +28, Knowledge (nature) +28, Knowledge (planes) +13, Knowledge (religion) +13, Linguistics +23, Perception +31, Sense Motive +19, Spellcraft +28
Languages Aklo, Common, Draconic, Giant; truespeech
SQ bestow knowledge, lantern of civilization, mimetic memory, morphic body, mythic immortality, uplift
--------------------
Ecology
--------------------
Environment any
Organization solitary, pair, or cabal (6–10)
Treasure standard
--------------------
Special Abilities
--------------------
Bestow Knowledge (Su) Touched creature uses your skill ranks for one skill instead of it's own.
Combat Casting +4 to Concentration checks to cast while on the defensive.
Damage Reduction (20/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Darkvision (60 feet) You can see in the dark (black and white only).
Devolution (DC 28) (Su) As a standard action, touch imparts feeblemind, which can be passed to future progeny.
Energy Resistance, Acid (20) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Cold (20) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Electricity (20) You have the specified Energy Resistance against Electricity attacks.
Energy Resistance, Sonic (20) You have the specified Energy Resistance against Sonic attacks.
Fly (60 feet, Good) You can fly!
Great Fortitude [Mythic] Roll Fort save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Immunity to Poison You are immune to poison.
Improved Bull Rush You don't provoke attacks of opportunity when bull rushing.
Improved Great Fortitude (1/day) Can re-roll a Fort save, but must take the second result.
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Lantern of Civilization (Su) Lantern powers primal chisel and grants constant true seeing.
Lifesense (60 ft.) (Ex) Sense living things and creatures without seeing them.
Mimetic Memory (Ex) As a standard action, touch alters genetic memory as share thoughts.
Morphic Anatomy (Ex) Immune to critical hits, sneak attacks, and precision damage.
Morphic Body (Ex) Change appearance, but no mechanical effects.
Mythic Immortality (Su) Ressurrect next day, unless killed by mythic foe's crit, or an epic weapon.
Mythic Magic (3/day) (Su) When you cast spells, you can cast the mythic version instead
Power Attack [Mythic] Use 1 power to eliminate attack penalties of Power attack for 1 min.
Psychic Warding +8 (Su) Gain a bonus to saves vs. mind-affecting effects.
Quicken Spell-Like Ability (Baleful Polymorph) Spell-like ability is cast as a swift action up to 3/day.
Regeneration 10 (epic weapons) Heal HP quickly and cannot die.
Surge (1d10) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Truespeech (Su) Speak with any creature that has a language.
Unstoppable (Ex) Automatically end any negative conditions on self at end of turn.
Uplift (Su) As a full-rd action, awaken a wide variety of types, passing intelligence to progeny.

**Comment by Lavaeolous** [comment]
MR
