### ISSUE TITLE
Can't import Bestiary 5 - Apkallu

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#221]
Can't import statblock:

Apkallu      CR 23/MR 9
XP 819,200
Apkallu (Pathfinder RPG Bestiary 5 32)
LN Large outsider (extraplanar, lawful, mythic, water)
Init +21/+1, dual initiative; Senses darkvision 60 ft., detect chaos, low-light vision, mistsight, true seeing; Perception +38
Aura mythic presence[MA] (30 ft., DC 28)
--------------------
Defense
--------------------
AC 39, touch 12, flat-footed 36 (+7 armor, +3 Dex, +20 natural, -1 size)
hp 469 (23d10+343); regeneration 15 (chaotic spells and effects)
Fort +24, Ref +17, Will +21; second save
Defensive Abilities freedom of movement, scale surplice; DR 20/chaotic, 20/epic; Immune dazed, disease, electricity, petrification, poison; Resist cold 20; SR 39
--------------------
Offense
--------------------
Speed 40 ft., fly 80 ft. (average), swim 40 ft.
Melee +2 axiomatic keen potent bronze spear +34/+29/+24/+19 (2d6+17/19-20/×3 plus 2d6 vs. chaotic), bite +27 (1d8+5 plus mark of restraint)
Space 10 ft.; Reach 10 ft.
Special Attacks mythic power (9/day, surge +1d10), paralyzing gaze
Psychic Magic (CL 19th; concentration +28)
   24 PE—detect mindscape[OA] (2 PE, DC 21), divide mind[OA] (9 PE), enshroud thoughts[OA] (2 PE), greater create mindscape[OA] (6 PE, DC 25), hypercognition[OA] (2 PE), intellect fortress III[OA] (6 PE), mind probe[OA] (4 PE, DC 23), mindlink[OA] (1 PE), mindscape door[OA] (3 PE, DC 22), psychic asylum[OA] (5 PE), psychic reading[OA] (1 PE), thought shield V[OA] (6 PE), tower of iron will V[OA] (9 PE)
Spell-Like Abilities (CL 19th; concentration +28)
   Constant—detect chaos, freedom of movement, true seeing
   At will—control water, greater teleport (self plus 50 lbs. of objects only), major creation, order's wrath (DC 23), plane shift (DC 26)
   3/day—quickened order's wrath (DC 23)
   1/day—commune
Oracle Spells Known (CL 19th; concentration +28)
   9th (5/day)—miracle, overwhelming presence[UM] (DC 28)
   8th (7/day)—mass cure critical wounds, dimensional lock[M], shield of law (DC 27)
   7th (7/day)—destruction (DC 26), dictum[M] (DC 26), repulsion (DC 26)
   6th (7/day)—greater dispel magic, geas/quest, heal[M]
   5th (8/day)—greater command (DC 24), mass cure light wounds, greater forbid action[UM] (DC 24), wall of stone
   4th (8/day)—dimensional anchor, divination, restoration, sending[M]
   3rd (8/day)—create food and water, invisibility purge, speak with dead (DC 22), wind wall
   2nd (8/day)—calm emotions (DC 21), hold person (DC 21), silence (DC 21), sound burst (DC 21), zone of truth (DC 21)
   1st (9/day)—comprehend languages, divine favor[M], obscuring mist[M], sanctuary[M] (DC 20), shield of faith[M]
   0 (at will)—create water, detect magic, detect poison, guidance, light, mending, purify food and drink (DC 19), read magic, stabilize
   M mythic spell
--------------------
Statistics
--------------------
Str 30, Dex 26, Con 33, Int 26, Wis 27, Cha 29
Base Atk +23; CMB +34; CMD 52
Feats Combat Casting, Combat Reflexes, Craft Wondrous Item, Divine Interference[M], Eschew Materials, Flyby Attack, Improved Initiative[M], Lightning Reflexes[M], Maximize Spell, Mythic Crafter[M], Power Attack[M], Quicken Spell-Like Ability (order's wrath), Silent Spell
Skills Acrobatics +8 (+12 to jump), Craft (any) +31 (+36 when crafting non-mythic magic items), Craft (any) +31 (+36 when crafting non-mythic magic items), Craft (any) +31 (+36 when crafting non-mythic magic items), Diplomacy +34, Fly +29, Heal +31, Intimidate +32, Knowledge (engineering) +28, Knowledge (geography) +28, Knowledge (history) +28, Knowledge (planes) +28, Knowledge (religion) +28, Perception +38, Sense Motive +31, Spellcraft +31, Swim +41; Racial Modifiers +4 Perception
Languages Aquan, Auran, Celestial; telepathy 100 ft.
SQ archive, change shape (1 human form and 1 merfolk form; polymorph), mythic immortality, mythic presence[MA] (30 ft., DC 28), mythic spell-like abilities, mythic spellcasting[MA], mythic spellpower[MA] (2/day)
Other Gear +2 resonating scale mail, +2 axiomatic keen potent bronze spear
--------------------
Ecology
--------------------
Environment any (lawful planes)
Organization solitary
Treasure standard (+2 axiomatic keen potent[ma] bronze spear, other treasure)
--------------------
Special Abilities
--------------------
Archive (Su) As 1 minute action, create door to personal extradimensional library. Auto teleport there if incapacitated/killed.
Change Shape (1 human form and 1 merfolk form; polymorph) (Su) You can change your form.
Combat Casting +4 to Concentration checks to cast while on the defensive.
Combat Reflexes (9 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (20/chaotic) You have Damage Reduction against all except Chaotic attacks.
Damage Reduction (20/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Darkvision (60 feet) You can see in the dark (black and white only).
Divine Interference [Mythic] Double penalty to foe's att or use 1 power to triple the penalty.
Dual Initiative (Ex) You act a second time each round at -20 from your normal initiative
Energy Resistance, Cold (20) You have the specified Energy Resistance against Cold attacks.
Eschew Materials Cast spells without materials, if component cost is 1 gp or less.
Fly (80 feet, Average) You can fly!
Flyby Attack You can take a standard action during your move action while flying.
Immunity to Dazed You are immune to the dazed condition.
Immunity to Disease You are immune to diseases.
Immunity to Electricity You are immune to electricity damage.
Immunity to Petrification You are immune to Petrification.
Immunity to Poison You are immune to poison.
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Lightning Reflexes [Mythic] Roll Ref save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Maximize Spell All variable effects of a spell are maximized. +3 Levels.
Mistsight (Su) See through fog, mist and murky water without penalty
Mythic Crafter [Mythic] Can create mythic magic items & +5 on any checks when crafting non-mythic magic items.
Mythic Immortality (Su) Ressurrect next day, unless killed by mythic foe's crit, or an epic weapon.
Mythic Presence (30 ft., DC 28) (Su) Spend 1 mythic power to gain a frightful mien.
Mythic Spell-Like Abilities (Ex) Use 1 power to cast mythic version of order's wrath SLA.
Mythic Spellcasting (Ex) You can learn a number of mythic spells equal to your tier and can expend mythic power when casting them to enhance the results. To select a mythic spell, you must be able to cast the non-mythic version or have it on your list of spells known. Every 
Mythic Spellpower (2/day) (Sp) Cast a mythic spell without expending mythic power.
Paralyzing Gaze (30 feet, DC 30) (Su) Foes in 30 ft are paralyzed 1 rd or 1d6 rds/1 rd stagger if active (Fort neg/part). Lawful foes immune.
Power Attack [Mythic] Use 1 power to eliminate attack penalties of Power attack for 1 min.
Quicken Spell-Like Ability (Order's Wrath) Spell-like ability is cast as a swift action up to 3/day.
Regeneration 15 (chaotic spells and effects) Heal HP quickly and cannot die.
Scale Surplice (Su) Wear a set of scale mail with no ACP, grants swim speed and allows breath water.
Silent Spell Cast a spell with no verbal components. +1 Level.
Spell Resistance (39) You have Spell Resistance.
Surge (1d10) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Swim (40 feet) You have a Swim speed.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.

**Comment by Lavaeolous** [comment]
MR, Double Parenthesis in Skills
