### ISSUE TITLE
Can't import Bestiary 5 - Danava Pillar (Titan)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#228]
Can't import statblock:

Danava Pillar (Titan)      CR 24/MR 10
XP 1,228,800
Danava pillar (Pathfinder RPG Bestiary 5 246)
LN Colossal outsider (extraplanar, lawful, mythic)
Init +26/+6, dual initiative; Senses darkvision 60 ft.; Perception +38
--------------------
Defense
--------------------
AC 49, touch 24, flat-footed 36 (+9 deflection, +12 Dex, +1 dodge, +25 natural, -8 size)
hp 555 (26d10+412)
Fort +27, Ref +21, Will +24; +8 vs. mind-affecting effects; second save
Defensive Abilities fortification 50%, iron resilience, unstoppable[MA]; DR 20/epic; Immune aging, dazed, death effects, disease, divinations, staggered, stunning; SR 40
--------------------
Offense
--------------------
Speed 90 ft.
Melee +3 axiomatic tetsubo +40/+40/+35/+30/+25 (6d8+30/19-20/×5 plus 2d6 vs. chaotic) or
   3 slams +37 (2d8+27)
Space 30 ft.; Reach 30 ft.
Special Attacks devastator, mythic power (10/day, surge +1d12), rock throwing (120 ft.), trample (4d8+27, DC 41)
Spell-Like Abilities (CL 20th; concentration +32)
   Constant—air walk, haste, mind blank, true seeing, water walk
   At will—bestow curse (DC 26), break enchantment, divination, greater dispel magic, sending
   3/day—greater scrying (DC 29), harm (DC 28), heal (quickened), mass suggestion (DC 28), quickened chain lightning (DC 28), quickened heal
   1/day—greater planar ally, mass heal, soul bind (DC 31), tsunami[APG] (DC 31)
--------------------
Statistics
--------------------
Str 47, Dex 34, Con 35, Int 27, Wis 28, Cha 34
Base Atk +26; CMB +53 (+57 sunder); CMD 84 (86 vs. sunder)
Feats Combat Reflexes, Critical Focus, Dazing Assault[APG], Greater Sunder, Greater Vital Strike, Improved Critical[M], Improved Initiative[M], Improved Sunder, Improved Vital Strike, Power Attack[M], Quicken Spell-Like Ability (chain lightning), Quicken Spell-Like Ability (heal), Vital Strike[M]
Skills Acrobatics +12 (+36 to jump), Climb +44, Craft (any one) +35, Diplomacy +38, Intimidate +41, Knowledge (any one) +34, Knowledge (arcana) +34, Knowledge (engineering) +34, Knowledge (nature) +34, Knowledge (planes) +37, Perception +38, Sense Motive +38, Spellcraft +37, Swim +47, Use Magic Device +41
Languages Abyssal, Celestial, Common, Infernal; telepathy 300 ft.
SQ powerful blows (slam)
Other Gear +3 axiomatic tetsubo[UC]
--------------------
Ecology
--------------------
Environment any
Organization solitary
Treasure standard (~[!i]+3 axiomatic tetsubo~[!n]~[!^]ue~[!n], ~[!i]danava mantle~[!n], other treasure)
--------------------
Special Abilities
--------------------
Combat Reflexes (13 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Critical Focus +4 to confirm critical hits.
Damage Reduction (20/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Danava Mantle Mantle grants +9 deflection bonus to AC to mythic Colossal creatures.
Darkvision (60 feet) You can see in the dark (black and white only).
Dazing Assault (DC 36) -5 to all attacks and maneuvers but struck foes are dazed 1 rd (Fort neg).
Devastator (Su) Full-rd action bypasses all DR, hardness, can crit objects, sunder auto-threat. Counts as Vit. Strike.
Dual Initiative (Ex) You act a second time each round at -20 from your normal initiative
Fortification 50% You have a chance to negate critical hits on attacks.
Greater Sunder When destroying an item, extra damage is transferred to the wielder.
Immunity to Aging You are immune to aging effects.
Immunity to Dazed You are immune to the dazed condition.
Immunity to Death Effects You are immune to death effects.
Immunity to Disease You are immune to diseases.
Immunity to Divinations You are immune to divinations.
Immunity to Staggered Immune to staggered.
Immunity to Stunning You are immune to being stunned.
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Improved Sunder You don't provoke attacks of opportunity when sundering.
Iron Resilience (1/round) (Ex) Completely ignore an attack once per round, spend mythic power for extra uses.
Power Attack [Mythic] Use 1 power to eliminate attack penalties of Power attack for 1 min.
Powerful Blows (Ex) The specified attack adds 1-1/2 times your Str bonus on damage rolls
Quicken Spell-Like Ability (Chain Lightning) Spell-like ability is cast as a swift action up to 3/day.
Quicken Spell-Like Ability (Heal) Spell-like ability is cast as a swift action up to 3/day.
Rock Throwing (120 ft.) (Ex) You can throw big rocks. They hurt.
Spell Resistance (40) You have Spell Resistance.
Surge (1d12) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Telepathy (300 feet) (Su) Communicate telepathically if the target has a language.
Unstoppable (Ex) Automatically end any negative conditions on self at end of turn.
Vital Strike [Mythic] Vital Strike multiplies dam bonus by number of extra weapon dice rolled.

**Comment by Lavaeolous** [comment]
MR
