### ISSUE TITLE
Can't import Bestiary 5 - Devastator

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#229]
Can't import statblock:

Devastator      CR 22/MR 8
XP 614,400
Devastator (Pathfinder RPG Bestiary 5 77)
CE Gargantuan construct (extraplanar, mythic)
Init +6; Senses darkvision 60 ft., low-light vision, mythic sight[MA] (2) 30 ft.; Perception +34
Aura corruption (60 ft.), unholy aura (DC 24)
--------------------
Defense
--------------------
AC 44, touch 20, flat-footed 38 (+4 deflection, +6 Dex, +24 natural, +4 profane, -4 size)
hp 365 (30d10+200)
Fort +14, Ref +20, Will +18
Defensive Abilities absorb good magic, unchanging[MA]; DR 15/adamantine, 15/epic; Immune construct traits, acid, cold, electricity, fire; SR 33
--------------------
Offense
--------------------
Speed 50 ft., burrow 30 ft., fly 60 ft. (average)
Melee 2 wings +40 (2d6+11/19-20 plus bleed), 4 vile arms +45 (2d8+18/19-20)
Space 20 ft.; Reach 20 ft.
Special Attacks bleed (2d6), destroyer[MA], display of strength[MA], farwalker[MA], farwalker[MA], mythic power (10/day, surge +1d10), rend (2 claws, 2d8+24), vile strikes
Spell-Like Abilities (CL 20th; concentration +26)
   Constant—unholy aura
   At will—blade barrier (DC 22), dimensional anchor
   3/day—blasphemy (DC 23), plane shift (DC 23)
   1/day—destruction (DC 23), earthquake, implosion (DC 25)
--------------------
Statistics
--------------------
Str 37, Dex 23, Con —, Int 15, Wis 18, Cha 22
Base Atk +30; CMB +47 (+49 bull rush); CMD 71 (73 vs. bull rush)
Feats Awesome Blow, Blind-fight[M], Cleave, Combat Reflexes[M], Critical Focus[M], Great Cleave, Improved Bull Rush, Improved Critical (arm), Improved Critical (wing), Power Attack, Staggering Critical, Toughness[M], Vital Strike, Weapon Focus (arm), Weapon Focus (wing)
Skills Acrobatics +21 (+29 to jump), Climb +28, Fly +18, Intimidate +36, Knowledge (planes) +17, Perception +34
Languages Abyssal, Celestial
SQ always a chance[MA], extra mythic power[MA]
--------------------
Special Abilities
--------------------
Absorb Good Magic (Su) Whenever a spell with the good descriptor includes a devastator as a target or in its area or effect, the caster must succeed at a DC 38 caster level check or the devastator negates the entire spell and gains 5 temporary hit points per spell level of
Always a Chance (Ex) You don’t automatically miss when you roll a 1 on an attack roll.
Aura of Corruption (Su) Any chaotic evil outsider with 15 or more Hit Dice within 60 feet of a devastator gains a +10 enhancement bonus to Strength and Charisma, and its SR increases by 5 (if it doesn’t already possess SR, it gains SR equal to 11 + its CR).
Awesome Blow As standard action, damage and move smaller foe 10 ft. +1d6 dam if collide with something.
Bleed: Wing (Ex) Attack causes additional damage at the beginning of the target's turn.
Blind-Fight [Mythic] As a swift action, use 1 power to ignore concealment miss chance for 8 rds.
Blindsense (30 feet) (Ex) Sense things and creatures without seeing them.
Burrow (30 feet) You have a Burrow speed.
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Combat Reflexes [Mythic] As a swift action, use 1 power for movement AoO vs. foes who already provoked one for moving.
Construct Traits (+60 HP) Constructs have many immunities.
Critical Focus [Mythic] Auto confirm crits vs. non-mythic foes and roll fortification twice to negate, taking worse.
Damage Reduction (15/adamantine) You have Damage Reduction against all except Adamantine attacks.
Damage Reduction (15/epic) You have Damage Reduction against all except Epic attacks (weapons with a +6 bonus).
Darkvision (60 feet) You can see in the dark (black and white only).
Destroyer (Ex) Ignore hardness when attacking objects, but not objects that are creatures.
Display of Strength (Su) As a free action, use 1 power for +20 to a Str skill or check, longer for encumberance.
Farwalker (Sp) You can plane shift, using double your tier as your caster level.
Fly (60 feet, Average) You can fly!
Immunity to Ability Damage Immunity to ability damage
Immunity to Ability Drain Immunity to ability drain
Immunity to Acid You are immune to acid damage.
Immunity to Bleed You are immune to bleed.
Immunity to Cold You are immune to cold damage.
Immunity to Death and Necromancy effects You are immune to Death and Necromancy effects.
Immunity to Disease You are immune to diseases.
Immunity to Electricity You are immune to electricity damage.
Immunity to Energy Drain Immune to energy drain
Immunity to Exhausted You are immune to the exhausted condition.
Immunity to Fatigue You are immune to the fatigued condition.
Immunity to Fire You are immune to fire damage.
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Non-Mythic Petrification You are immune to non-mythic petrification.
Immunity to Non-Mythic Polymorph You are immune to non-mythic polymorph effects.
Immunity to Nonlethal Damage You are immune to Nonlethal Damage
Immunity to Paralysis You are immune to paralysis.
Immunity to Poison You are immune to poison.
Immunity to Sleep You are immune to sleep effects.
Immunity to Stunning You are immune to being stunned.
Improved Bull Rush You don't provoke attacks of opportunity when bull rushing.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Mythic Sight (Sp) See illusions and magical deceptions for what they truly are, as if using true seeing.
Power Attack -8/+16 You can subtract from your attack roll to add to your damage.
Spell Resistance (33) You have Spell Resistance.
Staggering Critical (DC 40) Critical hit staggers target
Surge (1d10) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Toughness [Mythic] Gain DR 10/epic when below 0 hit points.
Unchanging (Su) Immune to non-mythic polymorph and petrfication effects.
Vile Strikes (Ex) All of a devastator’s attacks are +5 unholy anarchic weapons that deal bludgeoning, piercing, and slashing damage.
Vital Strike Standard action: x2 weapon damage dice.

**Comment by Lavaeolous** [comment]
MR
