### ISSUE TITLE
Can't import Bestiary 5 - Dream Dragon, Great Wyrm

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#232]
Can't import statblock:

Dream Dragon, Great Wyrm      CR 22
XP 614,400
Great wyrm dream dragon (Pathfinder RPG Bestiary 5 90)
N Colossal dragon (extraplanar)
Init +2; Senses dragon senses, dreamsight; Perception +49
Aura frightful presence (360 ft., DC 33)
--------------------
Defense
--------------------
AC 39, touch 0, flat-footed 39 (-2 Dex, +39 natural, -8 size)
hp 420 (29d12+232)
Fort +24, Ref +16, Will +25
Defensive Abilities dream fortress; DR 20/magic; Immune paralysis, sleep; SR 33
--------------------
Offense
--------------------
Speed 40 ft., fly 250 ft. (clumsy)
Melee bite +35 (4d8+19), 2 claws +34 (4d6+13), tail slap +32 (4d6+19), 2 wings +32 (2d8+6)
Space 30 ft.; Reach 20 ft. (30 ft. with bite)
Special Attacks breath weapon (70-ft cone, 24d6 electricity, Reflex DC 32 half), crush (Large creatures, DC 32, 4d8+19), sleeping breath 3/day, tail sweep (40-ft., 2d8+19, DC 32)
Psychic Magic (CL 29th; concentration +38)
   23 PE—dream (4 PE), dream travel[OA] (6 PE, DC 25), euphoric cloud[ACG] (2 PE, DC 21), invisibility (2 PE), lullaby (0 PE, DC 19), maze (8 PE), mirror strike[UC] (1 PE), thought shield II[OA] (3 PE)
Spell-Like Abilities (CL 29th; concentration +38)
   At will—dream voyage[OA] (DC 28)
Psychic Spells Known (CL 19th; concentration +27)
   9th (4/day)—major mind swap[OA] (DC 27), wish
   8th (7/day)—clenched fist, greater possession[OA] (DC 26), power word stun
   7th (7/day)—antimagic field, limited wish, waves of exhaustion
   6th (7/day)—cloak of dreams[APG] (DC 24), dream council[OA] (DC 24), mental barrier V[OA]
   5th (7/day)—dismissal (DC 23), major creation, wall of force, waves of fatigue
   4th (8/day)—anti-incorporeal shell[ACG], create mindscape[OA] (DC 22), dimension door, freedom of movement
   3rd (8/day)—clairaudience/clairvoyance, deep slumber (DC 21), displacement, purge spirit[OA] (DC 21)
   2nd (8/day)—augury, aversion[OA] (DC 20), blindness/deafness (DC 20), calm emotions (DC 20), mind thrust II[OA] (DC 20)
   1st (8/day)—blurred movement[ACG], color spray (DC 19), shield, sleep (DC 19), true strike
   0 (at will)—arcane mark, dancing lights, daze (DC 18), detect magic, ghost sound (DC 18), mage hand, mending, message, resistance
--------------------
Statistics
--------------------
Str 37, Dex 7, Con 26, Int 26, Wis 25, Cha 28
Base Atk +29; CMB +50; CMD 58 (62 vs. trip)
Feats Alertness, Cleave, Cleaving Finish[UC], Flyby Attack, Hover, Improved Initiative, Iron Will, Lightning Reflexes, Multiattack, Power Attack, Skill Focus (Perception), Snatch, Vital Strike, Weapon Focus (bite), Wingover
Skills Acrobatics -2 (+2 to jump), Bluff +41, Diplomacy +41, Disguise +38, Fly +14, Intimidate +41, Knowledge (arcana) +40, Knowledge (dungeoneering) +40, Knowledge (history) +40, Knowledge (planes) +40, Knowledge (religion) +40, Perception +49, Sense Motive +43, Stealth +14, Survival +39
Languages Aklo, Auran, Celestial, Common, Draconic, Infernal
SQ change shape (any humanoid; polymorph), join dreamscape
--------------------
Ecology
--------------------
Environment any (dimension of dreams)
Organization solitary
Treasure triple
--------------------
Special Abilities
--------------------
Blindsense (60 feet) (Ex) Sense things and creatures without seeing them.
Breath Weapon (70-ft cone, 24d6 electricity, Reflex DC 32 half, usable every 1d4 rounds) As a standard action, affect an area with elemental damage (Ref half).
Change Shape (any humanoid; polymorph, 3/day) (Su) You can change your form.
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Cleaving Finish Make additional attack if opponent is knocked out
Crush (Large creatures, 4d8+19, DC 32) A flying or jumping Huge or larger dragon can land on foes as a standard action, using its whole body to crush them. Crush attacks are effective only against opponents three or more size categories smaller than the dragon. A crush attack affects as m
Damage Reduction (20/magic) You have Damage Reduction against all except Magic attacks.
Darkvision (120 feet) You can see in the dark (black and white only).
Dragon Senses (Ex) See four times as well as a human in dim light and twice as well in normal light.
Dream Fortress (Su) A juvenile or older young adult dream dragon is immune to dream, nightmare, and similar spells.
Dreamsight (Su) With a brief glance, a very young or older dragon can see a hazy image of the current dreams of sleeping creatures.
Fly (250 feet, Clumsy) You can fly!
Flyby Attack You can take a standard action during your move action while flying.
Frightful Presence (360 ft., 5d6 rounds, DC 33) Those in area of effect become frightened or shaken (Will neg.)
Hover Can hover in place without Fly checks, and kick up dust cloud if within 20 ft of ground.
Immunity to Paralysis You are immune to paralysis.
Immunity to Sleep You are immune to sleep effects.
Join Dreamscape (Su) An old or older dream dragon who sees a sleeping creature’s dream can enter that dream as a lucid body (Occult Adventures 241), while still acting with its physical body.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -8/+16 You can subtract from your attack roll to add to your damage.
Sleeping Breath (3/day) (Su) A limited number of times per day, a dream dragon can cause those who fail their saving throws against its breath attack to fall asleep for 1d4 rounds, as per the sleep spell. This is a mind-affecting sleep effect.
Snatch You can start a grapple if you hit with a claw or bite attack.
Spell Resistance (33) You have Spell Resistance.
Tail Sweep (40-ft., 2d8+19, DC 32) As a standard action, deal damage in half circle to foes 4+ sizes smaller (Ref half).
Vital Strike Standard action: x2 weapon damage dice.
Wingover (1/round) Can turn up to 180 degrees as a free action without a Fly check.

**Comment by Lavaeolous** [comment]
- [ ] Format "Major" Version of Spells so they can be found in the compenium (e.g. "major mind swap --> mind swap, major")

- [ ] Add a check to find spell versions if the formatting into ", major" versions leads to spells not being found (e.g. "major creation")
