### ISSUE TITLE
Can't import Bestiary 5 - Dream Dragon, Very Old

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#236]
Can't import statblock:

Dream Dragon, Very Old      CR 18
XP 153,600
Very old dream dragon (Pathfinder RPG Bestiary 5 90)
N Gargantuan dragon (extraplanar)
Init +3; Senses dragon senses, dreamsight; Perception +41
Aura frightful presence (270 ft., DC 28)
--------------------
Defense
--------------------
AC 35, touch 5, flat-footed 35 (-1 Dex, +30 natural, -4 size)
hp 287 (23d12+138)
Fort +19, Ref +14, Will +18
Defensive Abilities dream fortress; DR 10/magic; Immune paralysis, sleep; SR 29
--------------------
Offense
--------------------
Speed 40 ft., fly 250 ft. (clumsy)
Melee bite +30 (4d6+15), 2 claws +29 (2d8+10), tail slap +27 (2d8+15), 2 wings +27 (2d6+5)
Space 20 ft.; Reach 15 ft. (20 ft. with bite)
Special Attacks breath weapon (60-ft cone, 18d6 electricity, Reflex DC 27 half), crush (Medium creatures, DC 27, 4d6+15), sleeping breath 1/day, tail sweep (30-ft., 2d6+15, DC 27)
Psychic Magic (CL 23rd; concentration +30)
   17 PE—dream (4 PE), dream travel[OA] (5 PE, DC 22), euphoric cloud[ACG] (2 PE, DC 19), invisibility (2 PE), lullaby (0 PE, DC 17), mirror strike[UC] (1 PE), thought shield II[OA] (3 PE)
Psychic Spells Known (CL 13th; concentration +19)
   6th (5/day)—cloak of dreams[APG] (DC 22), dream council[OA] (DC 22)
   5th (7/day)—dismissal (DC 21), wall of force, waves of fatigue
   4th (7/day)—anti-incorporeal shell[ACG], dimension door, freedom of movement
   3rd (7/day)—clairaudience/clairvoyance, deep slumber (DC 19), displacement, purge spirit[OA] (DC 19)
   2nd (8/day)—augury, aversion[OA] (DC 18), blindness/deafness (DC 18), calm emotions (DC 18), mind thrust II[OA] (DC 18)
   1st (8/day)—blurred movement[ACG], color spray (DC 17), shield, sleep (DC 17), true strike
   0 (at will)—arcane mark, dancing lights, daze (DC 16), detect magic, ghost sound (DC 16), mage hand, mending, message, resistance
--------------------
Statistics
--------------------
Str 31, Dex 9, Con 22, Int 22, Wis 21, Cha 24
Base Atk +23; CMB +37; CMD 46 (50 vs. trip)
Feats Alertness, Flyby Attack, Hover, Improved Initiative, Lightning Reflexes, Multiattack, Power Attack, Skill Focus (Perception), Snatch, Vital Strike, Weapon Focus (bite), Wingover
Skills Acrobatics -1 (+3 to jump), Bluff +33, Diplomacy +33, Fly +11, Intimidate +33, Knowledge (arcana) +32, Knowledge (dungeoneering) +32, Knowledge (history) +32, Knowledge (planes) +32, Perception +41, Sense Motive +35, Stealth +13, Survival +31
Languages Aklo, Celestial, Common, Draconic, Infernal
SQ change shape (any humanoid; polymorph), join dreamscape
--------------------
Ecology
--------------------
Environment any (dimension of dreams)
Organization solitary
Treasure triple
--------------------
Special Abilities
--------------------
Blindsense (60 feet) (Ex) Sense things and creatures without seeing them.
Breath Weapon (60-ft cone, 18d6 electricity, Reflex DC 27 half, usable every 1d4 rounds) As a standard action, affect an area with elemental damage (Ref half).
Change Shape (any humanoid; polymorph, 3/day) (Su) You can change your form.
Crush (Medium creatures, 4d6+15, DC 27) A flying or jumping Huge or larger dragon can land on foes as a standard action, using its whole body to crush them. Crush attacks are effective only against opponents three or more size categories smaller than the dragon. A crush attack affects as m
Damage Reduction (10/magic) You have Damage Reduction against all except Magic attacks.
Darkvision (120 feet) You can see in the dark (black and white only).
Dragon Senses (Ex) See four times as well as a human in dim light and twice as well in normal light.
Dream Fortress (Su) A juvenile or older young adult dream dragon is immune to dream, nightmare, and similar spells.
Dreamsight (Su) With a brief glance, a very young or older dragon can see a hazy image of the current dreams of sleeping creatures.
Fly (250 feet, Clumsy) You can fly!
Flyby Attack You can take a standard action during your move action while flying.
Frightful Presence (270 ft., 5d6 rounds, DC 28) Those in area of effect become frightened or shaken (Will neg.)
Hover Can hover in place without Fly checks, and kick up dust cloud if within 20 ft of ground.
Immunity to Paralysis You are immune to paralysis.
Immunity to Sleep You are immune to sleep effects.
Join Dreamscape (Su) An old or older dream dragon who sees a sleeping creature’s dream can enter that dream as a lucid body (Occult Adventures 241), while still acting with its physical body.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -6/+12 You can subtract from your attack roll to add to your damage.
Sleeping Breath (1/day) (Su) A limited number of times per day, a dream dragon can cause those who fail their saving throws against its breath attack to fall asleep for 1d4 rounds, as per the sleep spell. This is a mind-affecting sleep effect.
Snatch You can start a grapple if you hit with a claw or bite attack.
Spell Resistance (29) You have Spell Resistance.
Tail Sweep (30-ft., 2d6+15, DC 27) As a standard action, deal damage in half circle to foes 4+ sizes smaller (Ref half).
Vital Strike Standard action: x2 weapon damage dice.
Wingover (1/round) Can turn up to 180 degrees as a free action without a Fly check.

**Comment by Lavaeolous** [comment]
- [ ] Splitting of Spells when these include an "-"
