### ISSUE TITLE
Can't import Bestiary 5 - Dream Dragon, Young Adult

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#238]
Can't import statblock:

Dream Dragon, Young Adult      CR 13
XP 25,600
Young adult dream dragon (Pathfinder RPG Bestiary 5 90)
N Huge dragon (extraplanar)
Init +4; Senses dragon senses, dreamsight; Perception +31
--------------------
Defense
--------------------
AC 26, touch 8, flat-footed 26 (+18 natural, -2 size)
hp 157 (15d12+60)
Fort +13, Ref +9, Will +12
Defensive Abilities dream fortress; DR 5/magic; Immune paralysis, sleep; SR 24
--------------------
Offense
--------------------
Speed 40 ft., fly 200 ft. (poor)
Melee bite +20 (2d8+9), 2 claws +19 (2d6+6), tail slap +17 (2d6+9), 2 wings +17 (1d8+3)
Space 15 ft.; Reach 10 ft. (15 ft. with bite)
Special Attacks breath weapon (50-ft cone, 10d6 electricity, Reflex DC 21 half), crush (Small creatures, DC 21, 2d8+9), sleeping breath 1/day
Psychic Magic (CL 15th; concentration +20)
   9 PE—euphoric cloud[ACG] (2 PE, DC 17), invisibility (2 PE), lullaby (0 PE, DC 15), mirror strike[UC] (1 PE), thought shield II[OA] (3 PE)
Psychic Spells Known (CL 5th; concentration +9)
   2nd (5/day)—aversion[OA] (DC 16), mind thrust II[OA] (DC 16)
   1st (7/day)—blurred movement[ACG], color spray (DC 15), shield, sleep (DC 15)
   0 (at will)—dancing lights, daze (DC 14), detect magic, ghost sound (DC 14), message, resistance
--------------------
Statistics
--------------------
Str 23, Dex 11, Con 18, Int 18, Wis 17, Cha 20
Base Atk +15; CMB +23; CMD 33 (37 vs. trip)
Feats Alertness, Flyby Attack, Hover, Improved Initiative, Multiattack, Power Attack, Skill Focus (Perception), Weapon Focus (bite)
Skills Acrobatics +0 (+4 to jump), Bluff +23, Diplomacy +23, Fly +10, Intimidate +23, Knowledge (arcana) +22, Knowledge (planes) +22, Perception +31, Sense Motive +25, Stealth +10, Survival +21
Languages Aklo, Common, Draconic
--------------------
Ecology
--------------------
Environment any (dimension of dreams)
Organization solitary
Treasure triple
--------------------
Special Abilities
--------------------
Blindsense (60 feet) (Ex) Sense things and creatures without seeing them.
Breath Weapon (50-ft cone, 10d6 electricity, Reflex DC 21 half, usable every 1d4 rounds) As a standard action, affect an area with elemental damage (Ref half).
Crush (Small creatures, 2d8+9, DC 21) A flying or jumping Huge or larger dragon can land on foes as a standard action, using its whole body to crush them. Crush attacks are effective only against opponents three or more size categories smaller than the dragon. A crush attack affects as m
Damage Reduction (5/magic) You have Damage Reduction against all except Magic attacks.
Darkvision (120 feet) You can see in the dark (black and white only).
Dragon Senses (Ex) See four times as well as a human in dim light and twice as well in normal light.
Dream Fortress (Su) A juvenile or older young adult dream dragon is immune to dream, nightmare, and similar spells.
Dreamsight (Su) With a brief glance, a very young or older dragon can see a hazy image of the current dreams of sleeping creatures.
Fly (200 feet, Poor) You can fly!
Flyby Attack You can take a standard action during your move action while flying.
Hover Can hover in place without Fly checks, and kick up dust cloud if within 20 ft of ground.
Immunity to Paralysis You are immune to paralysis.
Immunity to Sleep You are immune to sleep effects.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -4/+8 You can subtract from your attack roll to add to your damage.
Sleeping Breath (1/day) (Su) A limited number of times per day, a dream dragon can cause those who fail their saving throws against its breath attack to fall asleep for 1d4 rounds, as per the sleep spell. This is a mind-affecting sleep effect.
Spell Resistance (24) You have Spell Resistance.

**Comment by Lavaeolous** [comment]
- [ ] Splitting of Saves catches Keywords in other words (e.g. Fort in Fortress)
