### ISSUE TITLE
Broken for importing anything.

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#251]
For the latest version of the PF1-StatBlock-Converter-Module, it appears to be broken for everything.

The following statblock used to import:

Orc (CR 1/3)

XP 135
Orc warrior 1
CE Medium humanoid
Init +0; Senses darkvision 60 ft.; Perception –1
Weakness light sensitivity

DEFENSE

AC 13, touch 10, flat-footed 13 (+3 armor)
hp 6 (1d10+1)
Fort +3, Ref +0, Will –1
Defensive Abilities ferocity

OFFENSE

Speed 30 ft.
Melee falchion +5 (2d4+4/18–20)
Ranged javelin +1 (1d6+3)

TACTICS

Before Combat Orcs make few preparations before combat, preferring to charge headlong at any foe that presents itself.

During Combat Orcs prefer to use two-handed weapons to maximize the effectiveness of their great strength. They attack in ambushes from concealment to take an enemy off-guard and cause as much fear and confusion as possible.

Morale Orcs are bullies and cowards. They flee when the odds have turned against them and any nearby leaders are dead— or have already fled. They are prone to surrender and truces if such actions save their skins, although they honor such terms only as long as it is to their benefit to do so. Exceptions to this are dwarves and elves, from whom they neither ask nor give quarter.

STATISTICS

Str 17, Dex 11, Con 12, Int 7, Wis 8, Cha 6
Base Atk +1; CMB +4; CMD 14
Feats Weapon Focus (falchion)
Skills Intimidate +2
Languages Common, Orc
SQ weapon familiarity

SPECIAL ABILITIES

Ferocity (Ex)
An orc remains conscious and can continue fighting even if its hit point total is below 0. It is still staggered and loses 1 hit point each round. A creature with ferocity still dies when its hit point total reaches a negative amount equal to its Constitution score.

ECOLOGY

Environment temperate hills, mountains, or underground
Organization solitary, gang (2–4), squad (11–20 plus 2 sergeants of 3rd level and 1 leader of 3rd–6th level), or band (30–100 plus 150% noncombatants plus 1 sergeant of 3rd level per 10 adults, 1 lieutenant of 5th level per 20 adults, and 1 leader of 7th level per 30 adults)
Treasure NPC gear (studded leather armor, falchion, 4 javelins, other treasure)

Along with their brute strength and comparatively low intellect, the primary difference between orcs and the civilized humanoids is their attitude. As a culture, orcs are violent and aggressive, with the strongest ruling the rest through fear and brutality. They take what they want by force, and think nothing of slaughtering or enslaving entire villages when they can get away with it. They have little time for niceties or details, and their camps and villages tend to be filthy, ramshackle affairs filled with drunken brawls, pit fights, and other sadistic entertainment. Lacking the patience for farming and only able to shepherd the most robust and self-sufficient animals, orcs almost always find it easier to take what someone else has built than to create things themselves. They are arrogant and quick to anger when challenged, but only worry about honor so far as it directly benefits them to do so.

An adult male orc is roughly 6 feet tall and 210 pounds. Orcs and humans interbreed frequently, though this is almost always the result of raids and slave-taking rather than consensual unions. Many orc tribes purposefully breed for half-orcs and raise them as their own, as the smarter progeny make excellent strategists and leaders for their tribes.

Tribal Standards
Any orc fighting within 60 feet of his tribal standard gains a +1 morale bonus on attack rolls and Will saves against fear effects, just as if he had been the recipient of a bless spell. Conversely, the quickest way to rout an orc army is to capture or destroy its standard.

**Comment by adventuremagic123** [comment]
I have the latest game system and modules.  Only the statblock importer module is currently enabled.

**Comment by Lavaeolous** [comment]
Yeah, i had to change the parsing of special abilities to capture the ones without Ex, Su or Sp. That did break for different formattings of statblocks.

E.g. here there is a newline after "Ferocity (Ex)" thats normally not there. In some cases Ecology comes before the Special Abilities, in some after.

Should be fixed in the next update.

**Comment by adventuremagic123** [comment]
Thanks for the fix.  I'll resume testing shortly.

⁣--
Mark​
