### ISSUE TITLE
Importing from d20pfsrd.com, NPC names coming out with extra text

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#278]
An Orc from d20pfsrd comes out as "Orc()" and a Recycled Gearsman comes out as "Recycled GearsmanCR3".

However, notice that for Aasimar that there's no problem:

https://www.d20pfsrd.com/bestiary/monster-listings/outsiders/aasimar/

And this one also comes out right but for a bad reason:

https://www.d20pfsrd.com/bestiary/monster-listings/outsiders/elemental/elemental-air/elder-air-elemental/

**Comment by Lavaeolous** [comment]
Fixed in 2.0.7
