### ISSUE TITLE
Can't import Bestiary - Giant Octopus (does it work:  hero lab = no, d20pfsrd.com - no, aonprd.com - no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#284]
Can't import d20pfsrd.com statblock:

Giant OctopusCR 8

XP 4,800
N Large animal ( aquatic)
Init +6; Senses low-light vision; Perception +8

DEFENSE

AC 18, touch 11, flat-footed 16 (+2 Dex, +7 natural, –1 size)
hp 90 (12d8+36)
Fort +11, Ref +12, Will +7
Defensive Abilities ink cloud (30-foot-radius sphere)

OFFENSE

Speed 20 ft., swim 30 ft., jet 200 ft.
Melee bite +13 (1d8+5 plus poison), 8 tentacles +11 (1d4+2 plus grab)
Space 10 ft.; Reach 10 ft. (20 ft. with tentacle)
Special Attack constrict (tentacle, 1d4+2)

STATISTICS

Str 20, Dex 15, Con 17, Int 2, Wis 12, Cha 3
Base Atk +9; CMB +15 (+19 grapple); CMD 27 (can’t be tripped)
Feats Combat Reflexes, Improved Initiative, Iron Will, Lightning Reflexes, MultiattackB, Skill Focus (Stealth), Stealthy
Skills Escape Artist +18, Perception +8, Stealth +18, Swim +13; Racial Modifiers +10 Escape Artist, +8 Stealth

SPECIAL ABILITIES

Poison (Ex)
Bite—injury; save Fort DC 19; frequency 1/round for 6 rounds; effect 1d3 Str; cure 2 saves.

ECOLOGY

Environment any ocean
Organization solitary
Treasure incidental

**Comment by adventuremagic123** [comment]
Can't import aonprd.com statblock:

Giant Octopus CR 8
Source Pathfinder RPG Bestiary pg. 219
XP 4,800
N Large animal (aquatic)
Init +6; Senses low-light vision; Perception +8
Defense
AC 18, touch 11, flat-footed 16 (+2 Dex, +7 natural, –1 size)
hp 90 (12d8+36)
Fort +11, Ref +12, Will +7
Defensive Abilities ink cloud (30-foot-radius sphere)
Offense
Speed 20 ft., swim 30 ft., jet 200 ft.
Melee bite +13 (1d8+5 plus poison), 8 tentacles +11 (1d4+2 plus grab)
Space 10 ft., Reach 10 ft. (20 ft. with tentacle)
Statistics
Str 20, Dex 15, Con 17, Int 2, Wis 12, Cha 3
Base Atk +9; CMB +15 (+19 grapple); CMD 27 (can’t be tripped)
Feats Combat Reflexes, Improved Initiative, Iron Will, Lightning Reflexes, MultiattackB, Skill Focus (Stealth), Stealthy
Skills Escape Artist +18, Perception +8, Stealth +18, Swim +13; Racial Modifiers +10 Escape Artist, +8 Stealth
Ecology
Environment any ocean
Organization solitary
Treasure incidental
Special Abilities
Poison (Ex) Bite—injury; save Fort DC 19; frequency 1/round for 6 rounds; effect 1d3 Str; cure 2 saves.
Description
The giant octopus is a true monster capable of catching and eating sharks, humans, or anything else it can grab with its tentacles.

**Comment by adventuremagic123** [comment]
Can't import Hero Lab statblock:

Giant Octopus      CR 8
XP 4,800
Male giant octopus (Pathfinder RPG Bestiary 219)
N Large animal (aquatic)
Init +6; Senses low-light vision; Perception +8
--------------------
Defense
--------------------
AC 18, touch 11, flat-footed 16 (+2 Dex, +7 natural, -1 size)
hp 90 (12d8+36)
Fort +11, Ref +12, Will +7
Defensive Abilities ink cloud
--------------------
Offense
--------------------
Speed 20 ft., swim 30 ft.; jet 200 ft.
Melee bite +13 (1d8+5 plus poison), 8 tentacles +11 (1d4+2 plus grab)
Space 10 ft.; Reach 10 ft.
Special Attacks constrict (1d4+5)
--------------------
Statistics
--------------------
Str 20, Dex 15, Con 17, Int 2, Wis 12, Cha 3
Base Atk +9; CMB +15 (+19 grapple); CMD 27 (can't be tripped)
Feats Combat Reflexes, Improved Initiative, Iron Will, Lightning Reflexes, Multiattack[B], Skill Focus (Stealth), Stealthy
Skills Acrobatics +2 (-2 to jump), Escape Artist +18, Perception +8, Stealth +18, Swim +13; Racial Modifiers +10 Escape Artist, +8 Stealth
--------------------
Ecology
--------------------
Environment any ocean
Organization solitary
Treasure incidental
--------------------
Special Abilities
--------------------
Combat Reflexes (3 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Grab: Tentacle (Large) (Ex) You can start a grapple as a free action if you hit with the designated weapon.
Ink Cloud (30 ft. radius, 1/minute) (Ex) Emit an ink cloud, which provides total concealment.
Jet (200 ft.) Move in a straight line at 200, with no attacks of opportunity.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Poison (DC 19) (Ex) Bite—injury; save Fort DC 19; frequency 1/round for 6 rounds; effect 1d3 Str; cure 2 consecutive saves. The save DC is Constitution-based.
Swim (30 feet) You have a Swim speed.

**Comment by Lavaeolous** [comment]
The HeroLab one works, the others have a typo in the Speed Section, where the "Jet" Speed needs to be separated by a semicolon instead of a comma
