### ISSUE TITLE
Can't import Bestiary - Rakshasa (does it work:  hero lab - no, d20pfsrd.com - no, aonprd.com - no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#285]
Can't import d20pfsrd.com statblock:

RakshasaCR 10

XP 9,600
LE Medium outsider (native, shapechanger)
Init +9; Senses darkvision 60 ft.; Perception +14

DEFENSE

AC 25, touch 16, flat-footed 19 (+5 Dex, +1 dodge, +9 natural)
hp 115 (10d10+60)
Fort +9, Ref +12, Will +8
DR 15/good and piercing; SR 25

OFFENSE

Speed 40 ft.
Melee +1 kukri +16/+11 (1d4+4/15–20), claw +10 (1d4+1), bite +10 (1d6+1)
Special Attacks detect thoughts
Spells Known (CL 7th)

3rd (5/day)—lightning bolt (DC 16), suggestion (DC 16)
2nd (7/day)—acid arrow, invisibility, minor image
1st (7/day)—charm person (DC 14), mage armor, magic missile, shield, silent image
0th (at will)—dancing lights, detect magic, ghost sound (DC 13), mage hand, mending, message, prestidigitation

STATISTICS

Str 16, Dex 20, Con 22, Int 13, Wis 13, Cha 17
Base Atk +10; CMB +13; CMD 29
Feats Combat Expertise, Dodge, Improved Critical (kukri), Improved Initiative, Weapon Finesse
Skills Bluff +20, Diplomacy +16, Disguise +24, Perception +14, Perform +16, Sense Motive +14, Stealth +18; Racial Modifiers +4 Bluff, +8 Disguise
Languages Common, Infernal, Undercommon
SQ change shape (any humanoid, alter self)

SPECIAL ABILITIES

Detect Thoughts (Su)
A rakshasa can detect thoughts as per the spell of the same name (CL 18th). It can suppress or resume this ability as a free action. When a rakshasa uses this ability, it always functions as if it had spent three rounds concentrating and thus gains the maximum amount of information possible. A creature can resist this effect with a DC 18 Will save. The save DC is Charisma-based.

ECOLOGY

Environment any
Organization solitary, pair, or cult (3–12)
Treasure double (+1 kukri, other treasure)

**Comment by adventuremagic123** [comment]
Can't import aonprd.com statblock:

Rakshasa CR 10
Source Pathfinder RPG Bestiary pg. 231
XP 9,600
LE Medium outsider (native, shapechanger)
Init +9; Senses darkvision 60 ft.; Perception +14
Defense
AC 25, touch 16, flat-footed 19 (+5 Dex, +1 dodge, +9 natural)
hp 115 (10d10+60)
Fort +9, Ref +12, Will +8
DR 15/good and piercing; SR 25
Offense
Speed 40 ft.
Melee +1 kukri +16/+11 (1d4+4/15–20), claw +10 (1d4+1), bite +10 (1d6+1)
Special Attacks detect thoughts
Spells Known (CL 7th)
3rd (5/day)—lightning bolt (DC 16), suggestion (DC 16)
2nd (7/day)—acid arrow, invisibility, minor image
1st (7/day)—charm person (DC 14), mage armor, magic missile, shield, silent image
0—dancing lights, detect magic, ghost sound (DC 13), mage hand, mending, message, prestidigitation
Statistics
Str 16, Dex 20, Con 22, Int 13, Wis 13, Cha 17
Base Atk +10; CMB +13; CMD 29
Feats Combat Expertise, Dodge, Improved Critical (kukri), Improved Initiative, Weapon Finesse
Skills Bluff +20, Diplomacy +16, Disguise +24, Perception +14, Perform +16, Sense Motive +14, Stealth +18; Racial Modifiers +4 Bluff, +8 Disguise
Languages Common, Infernal, Undercommon
SQ change shape (any humanoid, alter self)
Ecology
Environment any
Organization solitary, pair, or cult (3–12)
Treasure double (+1 kukri, other treasure)
Special Abilities
Detect Thoughts (Su) A rakshasa can detect thoughts as per the spell of the same name (CL 18th). It can suppress or resume this ability as a free action. When a rakshasa uses this ability, it always functions as if it had spent three rounds concentrating and thus gains the maximum amount of information possible. A creature can resist this effect with a DC 18 Will save. The save DC is Charisma-based.
Description
The rakshasa is an evil spirit that cloaks itself in the guise of a humanoid creature that it might walk unseen among its prey. They embody what is taboo among most societies, and in the shape of those it seeks to defile, a rakshasa gorges itself on these hideous acts. Were they human, these acts of cannibalism, blasphemy, and worse would mark them as criminals condemned to the cruelest of hells.

When not disguised as a humanoid, the otherwise humanoid rakshasa has the head of an animal. Often, they possess the heads of great cats (such as a tiger or panther) or a snake (like a cobra or viper), yet other heads are not unknown—apes, jackals, vultures, elephants, mantises, lizards, rhinos, boars, and more are possible. In most cases, the type of head a rakshasa possesses speaks in some way to its personality—a tiger-headed rakshasa is stealthy and ravenous, while a boar-headed one might be gluttonous and crude. These changes rarely impact the rakshasa’s base statistics, although there are more powerful variants of the standard rakshasa that possess multiple heads, more potent spellcasting powers, and additional deadly and unusual special abilities.

Rakshasas scoff at religion—they understand the power of the divine, but see themselves as the only thing worthy of worship from the mortal races. Rakshasa clerics are thus quite rare. Although rakshasas are outsiders, they are also very much creatures of the Material Plane, and many believe the first rakshasas chose this exile over some other role offered them by a long-forgotten god. Although they usually work alone, it isn’t unheard of to find extended families of rakshasas working together to ruin a mortal civilization from the inside out over the course of many generations. A rakshasa is 6 feet tall and weighs 180 lbs.

**Comment by adventuremagic123** [comment]
Can't import Hero Lab statblock:

Rakshasa      CR 10
XP 9,600
Male rakshasa (Pathfinder RPG Bestiary 231)
LE Medium outsider (native, shapechanger)
Init +9; Senses darkvision 60 ft.; Perception +14
--------------------
Defense
--------------------
AC 25, touch 16, flat-footed 19 (+5 Dex, +1 dodge, +9 natural)
hp 115 (10d10+60)
Fort +9, Ref +12, Will +8
DR 15/good, 15/piercing; SR 25
--------------------
Offense
--------------------
Speed 40 ft.
Melee +1 kukri +16/+11 (1d4+4/15-20) or
   bite +10 (1d6+1), 2 claws +10 (1d4+1)
Special Attacks detect thoughts (DC 18)
Sorcerer Spells Known (CL 7th; concentration +10)
   3rd (5/day)—lightning bolt (DC 16), suggestion (DC 16)
   2nd (7/day)—acid arrow, invisibility, minor image (DC 15)
   1st (7/day)—charm person (DC 14), mage armor, magic missile, shield, silent image (DC 14)
   0 (at will)—dancing lights, detect magic, ghost sound (DC 13), mage hand, mending, message, prestidigitation
--------------------
Statistics
--------------------
Str 16, Dex 20, Con 22, Int 13, Wis 13, Cha 17
Base Atk +10; CMB +13; CMD 29
Feats Combat Expertise, Dodge, Improved Critical (kukri), Improved Initiative, Weapon Finesse
Skills Acrobatics +5 (+9 to jump), Bluff +20, Diplomacy +16, Disguise +24, Perception +14, Perform (Enter Choice) +16, Sense Motive +14, Stealth +18; Racial Modifiers +4 Bluff, +8 Disguise
Languages Common, Infernal, Undercommon
SQ change shape (any humanoid; alter self)
Other Gear +1 kukri
--------------------
Ecology
--------------------
Environment any
Organization solitary, pair, or cult (3-12)
Treasure double (+1 kukri, other treasure)
--------------------
Special Abilities
--------------------
Change Shape (any humanoid; alter self) (Su) You can change your form.
Combat Expertise +/-3 Bonus to AC in exchange for an equal penalty to attack.
Damage Reduction (15/good) You have Damage Reduction against all except Good attacks.
Damage Reduction (15/piercing) You have Damage Reduction against all except Piercing attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Detect Thoughts (DC 18) (Su) Detect thoughts as spell, always functions as if spent three rounds concentrating. (Will neg.)
Spell Resistance (25) You have Spell Resistance.

**Comment by Lavaeolous** [comment]
The HeroLab one works, the others are missing the Perform Type, e.g. "Perform +16" needs to be "Perform (Sing) +16".
