### ISSUE TITLE
Try to update to or install 1.0.9 via Foundry VTT and get "Installation failed: Not Found".

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#288]
There's something wrong with staging this version of the module.  Can't update or install via "Update All" or "Install Module".

**Comment by adventuremagic123** [comment]
This was found in the modules folder:

![zip file messed up](https://user-images.githubusercontent.com/50708405/89747269-a7dbeb00-da83-11ea-8592-707fd29fbae7.JPG)

**Comment by Lavaeolous** [comment]
Please try again, that error was there for a small timeframe yesterday
