### ISSUE TITLE
Add Support for Special Speeds when not separated correctly

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#291]
Special Speeds currently need to be separated by semicolon, otherwise sbc breaks when it can't find the speed type in the actor sheet.

**Comment by Lavaeolous** [comment]
Fixed in 2.0.7

**Comment by classicrp** [comment]
Just ran through an import with `Speed 40 ft., climb 20 ft.` and the import worked perfectly.
