### ISSUE TITLE
Save DC

### ISSUE THREAD

**Issue by Absum27** [Lavaeolous/PF1-StatBlock-Converter-Module#294]
When I import a character PC from Hero Lab save DC's are way off and unable to be corrected.

**Comment by Lavaeolous** [comment]
Could you post an example Statblock so i can test that on my side? I don't have HeroLab.

**Comment by Absum27** [comment]
Xur Bloodbane
Male half-orc cleric of Gorum 12
CN Medium humanoid (human, orc)
Init +1; Senses darkvision 60 ft.; Perception +6
--------------------
Defense
--------------------
AC 25, touch 12, flat-footed 25 (+11 armor, +2 deflection, +2 natural; +2 deflection vs. evil)
hp 106 (12d8+36) (currently 104)
Fort +12, Ref +7, Will +15; +1 morale vs. fear; +2 resistance vs. evil
Defensive Abilities orc ferocity; Resist acid 10
--------------------
Offense
--------------------
Speed 30 ft. (20 ft. in armor)
Melee +1 keen falchion +13/+8 (2d4+5/15-20) or
   mwk morningstar +14/+9 (1d8+3)
Ranged mwk light crossbow +11 (1d8/19-20)
Special Attacks channel positive energy 7/day (DC 18, 6d6), destructive smite (+6, 8/day), might of the gods (+12, 12 rounds/day)
Domain Spell-Like Abilities (CL 12th; concentration +17)
   8/day—strength surge (+6)
Cleric Spells Prepared (CL 12th; concentration +17)
   6th—greater dispel magic, heal, stoneskin[D]
   5th—communal air walk[UC], breath of life (DC 20), flame strike (DC 20), shout[D] (DC 20), summon monster V
   4th—blessing of fervor[APG] (DC 19), freedom of movement, inflict critical wounds[D] (DC 19), restoration (2)
   3rd—dispel magic, magic vestment[D], sacred bond[APG] (DC 18), searing light, searing light, wind wall
   2nd—bull's strength[D], delay poison, resist energy, lesser restoration, silence (DC 17), sound burst (DC 17)
   1st—ant haul[APG] (DC 16), bless, divine favor, protection from evil, remove fear, shield of faith, true strike[D]
   0 (at will)—create water, detect magic, guidance, stabilize
   D Domain spell; Domains Destruction (Rage[APG] subdomain), Strength
--------------------
Statistics
--------------------
Str 16, Dex 11, Con 14, Int 10, Wis 20, Cha 14
Base Atk +9; CMB +13; CMD 24
Feats Combat Casting, Extra Channel, Heavy Armor Proficiency, Scribe Scroll, Selective Channeling, Turn Undead
Traits deft dodger, veteran of battle
Skills Acrobatics -5 (-9 to jump), Appraise +4, Diplomacy +8, Heal +12, Intimidate +5, Knowledge (history) +5, Knowledge (religion) +9, Linguistics +4, Perception +6, Ride -1, Sense Motive +9, Spellcraft +4, Survival +6; Racial Modifiers +2 Intimidate
Languages Common, Orc, Undercommon
SQ orc blood, rage, rage power (energy resistance [cold][APG])
Combat Gear +1 seeking crossbow bolts (50), +1 shocking burst crossbow bolts (50), air elemental gem, minor crown of blasting, scroll of neutralize poison, remove curse, scroll of tongues, alchemist's fire (5), healer's kit, holy water (4), oil (5); Other Gear +2 holy reliquary full plate, +2 blinding buckler, +1 keen falchion, mwk light crossbow with 50 bolts, mwk morningstar, amulet of natural armor +2, belt of giant strength +2, cloak of resistance +2, handy haversack, minor ring of acid resistance, ring of protection +2, bedroll, blanket[APG], chalk, explorer's outfit, flint and steel, grappling hook (2), hammer, hemp rope (50 ft.), ink (2), iron spike[APG] (5), large tent[APG], piton (5), scroll case, scroll case, scroll case, silver holy symbol of Gorum, trail rations (10), vial (5), waterskin (2), heavy horse (combat trained), bit and bridle, block and tackle, feed (per day), flint and steel, large tent, military saddle, saddlebags, shovel, waterskin, winter blanket, 4,594 gp, 7 sp, 9 cp
--------------------
Special Abilities
--------------------
Cleric Channel Positive Energy 6d6 (7/day, DC 18) (Su) Positive energy heals the living and harms the undead; negative has the reverse effect.
Cleric Domain (Rage) Note: The effective level for the barbarian rage powers is currently equal to the cleric level. The rule that they should only count their effective barbarian level as 1/2 their cleric level has not been implemented yet.
Cleric Domain (Strength) Granted Powers: In strength and brawn there is truth–your faith gives you incredible might and power.
Combat Casting +4 to Concentration checks to cast while on the defensive.
Darkvision (60 feet) You can see in the dark (black and white only).
Destructive Smite +6 (8/day) (Su) Make a melee attack with morale bonus to damage.
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Energy Resistance: Cold (Ex) Cold Resistance while raging
Might of the Gods (12 rounds/day) (Su) Add your cleric level to your STR for checks.
Orc Blood Half-orcs count as both humans and orcs for any effect related to race.
Orc Ferocity (1/day) If brought below 0 Hp, can act as though disabled for 1 rd.
Rage (12 rounds/day) (Su) +4 Str, +4 Con, +2 to Will saves, -2 to AC when enraged.
Selective Channeling Exclude targets from the area of your Channel Energy.
Strength Surge (8/day) (Sp) Grant +6 to a melee attack or strength check.
Turn Undead (DC 18) Stnd act, 1 channel energy, undead in 30 ft. flee as if panicked for 1 min. (Will neg).

**Comment by Lavaeolous** [comment]
Fixed in v2.0.1

The bug was in the spellLevel, which was saved as a string instead of an integer.
So 5+10 became 510 instead of 5

**Comment by Absum27** [comment]
Thank you!
