### ISSUE TITLE
Can't import Bestiary 5 - Aether Wysp (hero lab = yes, aonprd.com = no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#296]
Statblock from aonprd.com doesn't import:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Aether%20Wysp

Get error:

![Capture](https://user-images.githubusercontent.com/50708405/91641091-cc264a00-e9e7-11ea-9411-c00eb734f910.JPG)

**Comment by adventuremagic123** [comment]
Another example is:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Air%20Veela

**Comment by adventuremagic123** [comment]
Another example is:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Earth%20Veela

**Comment by adventuremagic123** [comment]
Another example is:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Earth%20Wysp

**Comment by adventuremagic123** [comment]
Another example is:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Fire%20Veela

**Comment by adventuremagic123** [comment]
Another example is:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Fire%20Wysp

**Comment by adventuremagic123** [comment]
Another example is:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Water%20Wysp

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
The Error was in the way i searched for description data. The Line "There is no description for this monster."threw the converter off. Fixed in 2.0.2
