### ISSUE TITLE
Can't import Bestiary 5 - Cameroceras (hero lab = yes, aonprd.com = no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#298]
Doesn't import for aonprd.com:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Cameroceras

Error message:

![Capture](https://user-images.githubusercontent.com/50708405/91645176-8d54bc00-ea08-11ea-9ac8-7d70fef99222.JPG)

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Lusca

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
- [ ] Issue was with the Jet-Speed, which is not included in the default set of land, climb, swim, burrow and fly, but is also not separated from the rest via semi-colon. Fixed in 2.0.2
