### ISSUE TITLE
Can't import Bestiary 5 - Dark Empath (hero lab =  yes, aonprd.com = no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#299]
https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Dark%20Empath

Produces this error:

![Capture](https://user-images.githubusercontent.com/50708405/91663775-9dc07180-eab0-11ea-8110-2f3d8db3e209.JPG)

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Moon%20Dog

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Empyrean

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Lotus%20Tree

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Moon%20Dog

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Nulmind

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Gunpowder%20Ooze

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Papinijuwari

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Reborn%20Samsaran

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Reborn%20Samsaran

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MythicMonsterDisplay.aspx?ItemName=Sphinx%20Colossus

**Comment by adventuremagic123** [comment]
https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Lotus%20Tree

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Yangethe

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
Split into separate Issues
