### ISSUE TITLE
Can't import Bestiary 5 - Flytrap Leshy (hero lab = no, aonprd.com = no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#300]
Can't import Hero Lab statblock:

Flytrap Leshy      CR 4
XP 1,200
Flytrap leshy (Pathfinder RPG Bestiary 5 156)
N Small plant (leshy, shapechanger)
Init +6; Senses darkvision 60 ft., low-light vision; Perception +11
--------------------
Defense
--------------------
AC 17, touch 13, flat-footed 15 (+2 Dex, +4 natural, +1 size)
hp 39 (6d8+12)
Fort +7, Ref +4, Will +4
Immune electricity, sonic, plant traits; Resist fire 5
--------------------
Offense
--------------------
Speed 20 ft.
Melee bite +7 (1d4+1 plus 1d4 acid and digest), 2 bites +7 (1d3+1 plus 1d3 acid and digest)
Ranged acidic spittle +7 (1d4 acid plus digest)
Special Attacks digest, sneak attack +1d6
Spell-Like Abilities (CL 10th; concentration +12)
   Constant—pass without trace (cl 12th)
--------------------
Statistics
--------------------
Str 12, Dex 15, Con 14, Int 10, Wis 15, Cha 15
Base Atk +4; CMB +4; CMD 16
Feats Combat Reflexes, Improved Initiative, Weapon Focus (bite)
Skills Acrobatics +2 (-2 to jump), Intimidate +8, Perception +11, Stealth +6 (+10 in wetlands), Survival +2 (+6 in wetlands); Racial Modifiers +4 Stealth in wetlands, +4 Survival in wetlands
Languages Druidic, Plantspeech (flytraps), Sylvan
SQ amalgam, change shape (small flytrap; tree shape), verdant burst
--------------------
Ecology
--------------------
Environment warm marshes or wetlands
Organization solitary or cluster (4–8)
Treasure standard
--------------------
Special Abilities
--------------------
Amalgam (Ex) Up to 25 can combine into composite creature, with HD = # creatures - 1.
Change Shape (small flytrap; tree shape) (Su) You can change your form into a small plant of similar species.
Combat Reflexes (3 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Darkvision (60 feet) You can see in the dark (black and white only).
Digest (DC 15) (Ex) Sicken foe damaged by spittle or bite acid dam for 1d4 rds (Fort neg).
Energy Resistance, Fire (5) You have the specified Energy Resistance against Fire attacks.
Immunity to Electricity You are immune to electricity damage.
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Paralysis You are immune to paralysis.
Immunity to Poison You are immune to poison.
Immunity to Polymorph You are immune to Polymorph effects.
Immunity to Sleep You are immune to sleep effects.
Immunity to Sonic You are immune to sonic damage.
Immunity to Stunning You are immune to being stunned.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Plant Traits Plants have many immunities.
Sneak Attack +1d6 Attacks deal extra dam if flank foe or if foe is flat-footed.
Verdant Burst (Su) If slain, plant types in 30 ft heal 1d8+HD, diff terrain if can support plant growth.

**Comment by adventuremagic123** [comment]
The following error is displayed:
![Capture](https://user-images.githubusercontent.com/50708405/91665499-a7030b80-eabb-11ea-906d-4e15b876d205.JPG)

**Comment by adventuremagic123** [comment]
The same exact error message is produced via:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Flytrap%20Leshy

**Comment by adventuremagic123** [comment]
Another example (hero lab = no, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Flytrap%20Leshy

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Maharishi%20Manu

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Manu

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Rishi%20Manu

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Putrid%20Ooze

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Penguin

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Putrid%20Ooze

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MythicMonsterDisplay.aspx?ItemName=Solar%20Pitri%20(Agnishvatta)

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Twilight%20Pitri%20(Barhisad)

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Rishi%20Manu

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MythicMonsterDisplay.aspx?ItemName=Solar%20Pitri%20(Agnishvatta)

**Comment by adventuremagic123** [comment]
Another example (hero lab = yes, aonprd.com = no):

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Twilight%20Pitri%20(Barhisad)

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
These all should work in 2.0.7
