### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by bnp800** [Lavaeolous/PF1-StatBlock-Converter-Module#301]
Thank you for this amazing time-saving mod!
I'm a chinese so I'm using chinese localization mod for Foundry and for PF1e.
When I'm trying to import a character from stat-block, any translated race will cause 
![image](https://user-images.githubusercontent.com/69395973/91702478-771e3b80-eb81-11ea-990c-ad2c1f87a862.png)

Here's the original stat-block:

Nadya Petska CR 2
XP 600
Female human (Ulfen) ranger 3
CG Medium humanoid (human)
Init +2; Senses Perception +5

But if I change human to 人类(human in chinese), everything works great.

**Comment by Lavaeolous** [comment]
Could you post the complete statblock for testing purposes?
I'm currently not able to reproduce the error.

**Comment by bnp800** [comment]
Nadya Petska CR 2
XP 600
Female human (Ulfen) ranger 3
CG Medium humanoid (human)
Init +2; Senses Perception +5
DEFENSE
AC 15, touch 12, flat-footed 13 (+3 armor, +2 Dex)
hp 24 (3d10+3)
Fort +4, Ref +5, Will +0
OFFENSE
Speed 30 ft.
Melee handaxe +3 (1d6+1/x3) and light pick +3 (1d4/x4) or
handaxe +5 (1d6+1/×3) or
light pick +5 (1d4+1/×4)
Ranged composite longbow +5 (1d8+1/×3)
Special Attacks favored enemy (animals +2)
TACTICS
During Combat Nadya tries to keep her distance in battle, firing
her bow at adversaries before they can close on her. When
faced with more dangerous foes, especially those attuned to
cold, Nadya hurls a flask of alchemist’s fire to hinder them.
Morale Nadya fights with conviction, but recognizes
overwhelming odds and surrenders when necessary. In the
face of truly uncompromising evil, she fights to the death.
STATISTICS
Str 12, Dex 15, Con 13, Int 12, Wis 8, Cha 14
Base Atk +3; CMB +4; CMD 16
Feats Endurance, Point-Blank Shot, Skill Focus (Survival),
Two-Weapon Fighting, Weapon Finesse
Skills Acrobatics +5, Climb +5, Handle Animal +6, Heal +5,
Knowledge (geography) +7, Knowledge (local) +4,
Knowledge (nature) +7, Perception +5, Ride +6, Stealth +8,
Survival +8
Languages Common, Skald
SQ favored terrain (cold +2), track +1, wild empathy +5
Combat Gear potion of cure moderate wounds, alchemist’s
fire (2); Other Gear mwk studded leather, composite
longbow (+1 Str) with 20 arrows, dagger, handaxe, light
pick, snowshoes of northern pursuit (see page 61), backpack,
bedroll, cold-weather outfit, flint and steel, hooded lantern,
oil (2), rations (10 days), tindertwigs (3), traveler’s outfit,
waterskin, winter blanket, 36 gp, 27 sp, 41 cp

If I switch the core language to english, this error won't occur.

**Comment by Lavaeolous** [comment]
Is this the localization module you use?
https://gitlab.com/xtlcme/foundry-vtt-pf1e-chn

**Comment by bnp800** [comment]
yes

**Comment by Lavaeolous** [comment]
No real way to fix this i guess
