### ISSUE TITLE
Can't import Bestiary 5 - Psychic Vampire (hero lab = no, aonprd.com = 

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#302]
Hero Lab statblock:

Psychic Vampire      CR 8
XP 4,800
Human psychic vampire slayer 7 (Pathfinder Campaign Setting: Occult Bestiary 58, Pathfinder RPG Advanced Class Guide 53)
LE Medium undead (augmented humanoid, human)
Init +7; Senses darkvision 60 ft., thoughtsense 60 ft.; Perception +22
--------------------
Defense
--------------------
AC 22, touch 14, flat-footed 18 (+4 armor, +3 Dex, +1 dodge, +4 natural)
hp 85 (7d10+42); fast healing 5
Fort +10, Ref +9, Will +7
Defensive Abilities channel resistance +4; DR 10/cold iron, 10/magic; Immune undead traits; Resist cold 10, fire 10
Weaknesses psychic vampire weaknesses
--------------------
Offense
--------------------
Speed 30 ft.
Melee slam +14 (1d4+9 plus drain psychic energy)
Special Attacks drain psychic energy (DC 19), possession, sneak attack +2d6, studied target +2 (2nd, swift action)
Psychic Magic (CL 7th; concentration +11)
   7 PE—burst of adrenaline[OA] (1 PE), haste (3 PE), mental block[OA] (2 PE, DC 16), spider climb (2 PE)
--------------------
Statistics
--------------------
Str 22, Dex 16, Con —, Int 16, Wis 14, Cha 19
Base Atk +7; CMB +13; CMD 27
Feats Ability Focus (drain psychic energy), Alertness[B], Combat Expertise[B], Dodge[B], Improved Feint, Improved Initiative[B], Iron Will[B], Power Attack, Skill Focus (Bluff), Toughness, Weapon Focus (slam)
Skills Acrobatics +12, Bluff +25, Climb +15, Disguise +14, Knowledge (local) +13, Knowledge (nature) +10, Perception +22, Sense Motive +22, Stealth +20, Survival +12; Racial Modifiers +8 Bluff, +8 Perception, +8 Sense Motive, +8 Stealth
Languages Common, Draconic, Infernal, Vudrani
SQ possess object, slayer talents (combat trick, fast stealth, rogue crawl), stalker, track +3
Combat Gear potion of inflict serious wounds; Other Gear mwk chain shirt, belt of giant strength +2, cloak of resistance +1
--------------------
Ecology
--------------------
Environment any
Organization solitary
Treasure npc gear (mwk chain shirt, belt of giant strength +2, cloak of resistance +1, potion of inflict serious wounds, other treasure)
--------------------
Special Abilities
--------------------
Channel Resistance +4 +4 bonus to save vs. Channel Energy.
Combat Expertise +/-2 Bonus to AC in exchange for an equal penalty to attack.
Damage Reduction (10/cold iron) You have Damage Reduction against all except Cold Iron attacks.
Damage Reduction (10/magic) You have Damage Reduction against all except Magic attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Drain Psychic Energy (DC 19) (Su) Nat atk deals 1d4 abil drain to highest mental abil score (Will negates), gain temp PE = amt drained.
Energy Resistance, Cold (10) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Fast Healing 5 (Ex) Heal damage every round unless you are killed.
Fast Stealth (Ex) Move at full speed while using the Stealth skill at no penalty.
Immunity to Ability Drain Immunity to ability drain
Immunity to Bleed You are immune to bleed.
Immunity to Death Effects You are immune to death effects.
Immunity to Disease You are immune to diseases.
Immunity to Energy Drain Immune to energy drain
Immunity to Exhausted You are immune to the exhausted condition.
Immunity to Fatigue You are immune to the fatigued condition.
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Nonlethal Damage You are immune to Nonlethal Damage
Immunity to Paralysis You are immune to paralysis.
Immunity to Physical Ability Damage Immune to ability damage to your physical abilities.
Immunity to Poison You are immune to poison.
Immunity to Sleep You are immune to sleep effects.
Immunity to Stunning You are immune to being stunned.
Improved Feint You can make a Bluff check to feint in combat as a move action.
Possess Object (Su) As full-rd act, possess object as object possession{i/i}.
Possession (Su) As full-rd act, take control of helpless living creature as per possession.
Power Attack -2/+4 You can subtract from your attack roll to add to your damage.
Psychic Vampire Weaknesses (Ex) Certain items or actions can ward off a vampire, while others destroy it.
Rogue Crawl (Ex) Can move at 1/2 speed provoking AoO and can 5 ft step while prone.
Sneak Attack +2d6 Attacks deal extra dam if flank foe or if foe is flat-footed.
Stalker (Ex) Studied target bonus applies to Disguise, Intimidate, and Stealth as well.
Studied Target +2 (swift action, 2 at a time) (Ex) Study foe as a Swift action, gain +2 to att/dam & some skills vs. them.
Thoughtsense (60 feet) (Ex) You can detect and locate conscious creatures within range.
Track +3 Add the listed bonus to Survival checks made to track.
Undead Traits Undead have many immunities.

**Comment by adventuremagic123** [comment]
Error message for Hero Lab statblock:

![Capture](https://user-images.githubusercontent.com/50708405/92291714-8550bc80-eedf-11ea-94a7-8e2ca3c92587.JPG)

**Comment by adventuremagic123** [comment]
And this is probably why ... it's a template:

https://www.aonprd.com/MonsterTemplates.aspx?ItemName=Psychic%20Vampire

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
Yeah, sbc seems to be template related. Removing "Psychic" from third line at least lets this one parse.
