### ISSUE TITLE
Can't import Bestiary 5 - Seal (hero lab = yes, aonprd.com = no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#303]
Can't import:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Seal

Error message:

![Capture](https://user-images.githubusercontent.com/50708405/92312067-fb5a2f80-ef82-11ea-94e9-9cbe791ac635.JPG)

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
Fixed in 2.0.7
