### ISSUE TITLE
Can't import Bestiary 5 - Shabti (hero lab = yes, aonprd.com = no)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#304]
Can't import:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Shabti

Error message:

![Capture](https://user-images.githubusercontent.com/50708405/92312237-7708ac00-ef84-11ea-8851-0048b57bcce3.JPG)

**Comment by adventuremagic123** [comment]
Another example:

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Vetala

**Comment by adventuremagic123** [comment]
Great work!  I'm estimating that now about 85% of Bestiary 5 is importing using the latest Foundry VTT, PF1e game system, and your latest module.

**Comment by Lavaeolous** [comment]
Missed a variable name when copy&pasting. Fixed in 2.0.7
