### ISSUE TITLE
Error message when importing statblock

### ISSUE THREAD

**Issue by Loslobos5** [Lavaeolous/PF1-StatBlock-Converter-Module#305]
I get the message "type error: cannot set property "total" of undefined;" when I import a statblock

**Comment by Lavaeolous** [comment]
Hey, could you post a link to the statblock? Then i can take a look

**Comment by Loslobos5** [comment]
[Wang Chung Lee.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/5295770/Wang.Chung.Lee.txt)

**Comment by Loslobos5** [comment]
This is the statblock out of Herolabs. It is for an archtype ranger out of Pirates of the Inner Sea
