### ISSUE TITLE
Conversion Changes Buff is displayed by default

### ISSUE THREAD

**Issue by JustNoon** [Lavaeolous/PF1-StatBlock-Converter-Module#312]
Newly imported actors should default their conversion buff to hidden.

![image](https://user-images.githubusercontent.com/45368472/95251061-9ba0af80-07e0-11eb-9479-3bdbe3bdc5c5.png)

**Comment by Lavaeolous** [comment]
Yep, seen that on my session yesterday. Will be fixed in the next update

**Comment by Lavaeolous** [comment]
Fixed in 2.0.3
