### ISSUE TITLE
Display entire statblock import text on Notes tab

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#314]
The formatted output looks nice but it would be more useful to have the entire imported statblock text displayed -- even if it is not beautified and as long as it's readable (ideally exactly the same as from the source text).

**Comment by adventuremagic123** [comment]
Ideally, I'd like to have the statblock text exactly as it was from the source material.  When we paste the statblock (at least in previous versions if not the current one), the text is already modified by the pasting process.  Normally, the text pasted in would look the same as the original source.

**Comment by adventuremagic123** [comment]
I take part of that back.  The beautified text is very useful.  I'd just like the rest of the text I used to do the import -- even if it isn't beautified.  I think this is just the description text?

**Comment by Lavaeolous** [comment]
Included in v2.0.5
