### ISSUE TITLE
monster with long name getting stuck on creature size

### ISSUE THREAD

**Issue by classicrp** [Lavaeolous/PF1-StatBlock-Converter-Module#319]
So I'm still at bringing the critters in from my Shattered Star modified module and I was bringing in 4 elementals.  "formattedInput" is built perfectly.  Once it gets to "mapGeneralData()" it errs out at "#2440" after hitting "= enumTokenSize[formattedInput.size].w;".
The in-game converter comes back with "TypeError: Cannot read property 'w' of undefined;".
I couldn't get around this one but did notice on "#2439 dataOutput.token.name = dataOutput.token.name = formattedInput.name;" the .name property is being assigned twice to the same object.

![sbc_statblock_converter_message](https://user-images.githubusercontent.com/12385879/97952513-ab71cc00-1d6b-11eb-9677-434346dd3ed3.jpg)
![sbs_js-formattedInput](https://user-images.githubusercontent.com/12385879/97952521-af9de980-1d6b-11eb-9269-f05e730a13c3.jpg)
![sbs_js-line2440](https://user-images.githubusercontent.com/12385879/97952522-b0368000-1d6b-11eb-99b5-6b7d2bde5391.jpg)
[4_Advanced_Medium_Water_Elemental.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/5479402/4_Advanced_Medium_Water_Elemental.txt)

**Comment by Lavaeolous** [comment]
#2439 will be fixed, but should not lead to that error.
I have a hunch that thats another case of Problems i had earlier with "Medium", as thats a Size Category as well as a Class.

**Comment by Lavaeolous** [comment]
I can't replicate that with the elementals found on AoN (e.g. https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Medium%20Water%20Elemental).

Could you send me your statblocks? They look like they were generated by HeroLab or PCGen?

**Comment by classicrp** [comment]
I did send it and yes it was a Hero Lab build.  One thing I have noticed is that SBC doesn't like having the monster templates in the name; Advanced, Fiendish, Celestial, etc... Because of the nature of my Mythic campaign, most of my creatures are beyond the norm.
I'll run it today without Advanced in the name and see if that is tripping it up.
Thanks.

**Comment by classicrp** [comment]
Just noticed that I also have Medium and medium on two different lines.  One for the name, one for the race. I'll scrub that one first and try.

**Comment by classicrp** [comment]
It was in three places, but that was it. I removed the `medium` from the middle one:
`Advanced Medium Water Elemental      CR 6`
`XP 2,400`
`Male advanced medium water elemental (Pathfinder RPG Bestiary 126, p.288)`
`N Medium outsider (elemental, extraplanar, water)`
and it worked.  It also just so happens to be the only lower-case 'medium'.
