### ISSUE TITLE
Doesn't parse deflection bonuses properly, and didn't process skills

### ISSUE THREAD

**Issue by Tristan-Goucher** [Lavaeolous/PF1-StatBlock-Converter-Module#322]
I tried to import a statblock for a ghost with class levels and ran into a few issues.

1. When I processed the statblock's AC section:

AC 19, touch 19, flat-footed 15 (+5 deflection, +3 Dex, +1 dodge)

At first, I thought the +5 Deflection was skipped entirely. I then saw it in the SBC buff, but it was shown as a +4 instead of +5. So that was weird. But I found out why it wasn't applying. The Changes entry for it (and the Dodge bonus) were marked as:

# | Priority 1 | + | AC | **All** | Deflection (or Dodge)

When I tried to change the All part to Generic, it was stuck using the Saving Throws dropdown list and nothing else. The Dodge bonus was fixed by the SBC Importer giving the character the Dodge feat, though.

As for the skills, my skills section was like so:

Skills Acrobatics +14, Bluff +16, Climb +14, Craft (mapmaking) +11, Diplomacy +16, Disable Device +17, Fly +11, Knowledge (local) +9, Knowledge (nature) +9, Perception +19, Profession (sailor) +14, Sense Motive +7, Stealth +11, Survival +6, Swim +9

The Skills section of the preview window was blank, and no ranks were assigned. I tried removing all of the sections in () (and the () marks).

[Also, the ghost has a STR of -, and it seems the SBC Importer treats this as a zero. This imposed a -5 penalty to everything like CMD. Perhaps just putting the STR at 10 so there's no impact could work?)

**Comment by Lavaeolous** [comment]
Could you send me the statblock for testing?

**Comment by Tristan-Goucher** [comment]
For transparency and information, I'm posting here to say I sent the statblock (Raw Input into SBC and original data from PDF) to Lavaeolous over Discord.
