### ISSUE TITLE
For Token Configuration, Character tab, "Display Name", please use "Never Displayed" as the setting.

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#335]
The compendium uses "Never Displayed".  I like that setting because it works better with the Health Monitor module -- I've entered and issue for it to stop revealing actor names to players who should not see them (with "Never Displayed" set, it doesn't do that).

If you prefer to leave it as "Hovered by Owner", please consider providing a control in the UI that allows us to override that default with one of the other settings (I'd be using "Never Displayed" for now).

**Comment by Lavaeolous** [comment]
Oh nice, i'll add Token Settings to the Module Settings planned for 3.x

**Comment by Lavaeolous** [comment]
![Capture](https://user-images.githubusercontent.com/14833806/100458795-a41cb480-30c4-11eb-85e7-f9e7d37ddc44.JPG)
Included in 3.x (which has no release date yet)
