### ISSUE TITLE
Class HD is leaving hit points blank.

### ISSUE THREAD

**Issue by AlphaQup2nite** [Lavaeolous/PF1-StatBlock-Converter-Module#342]
Classes are importing with blank HP, and throwing a red attribute missing error if the actor only has Class HD.   Calculated HP only on Con.

Sometimes works properly when the actor has both racial and class HD.  Suspect issue may be 0 level racial HD?

Just tested with a unit with 0 racial HD, and 2 different classes, neither of them have any HP value. However, unlike the single Class HD, this one had the overall correct on the sheet, fixed via the sbc buff.

Just did another import of class only, HP error, but imported the correct HP.  Sometimes it will, sometimes its Con only.

Based off testing, seems to be biggest issue with Low numbers of HD? (>2) having incorrect HP.  Higher numbers of HD still error, but apply the correct HP. (No)  Just had a 5 HD 2 class fail to import any HP at all.

**Comment by Lavaeolous** [comment]
Fixed in 2.0.14
