### ISSUE TITLE
Iron Gods:  Part 1:  Garmen Ulreth, Khonnir Baine, and Sanvil Trett import with formula errors.

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#343]
These Iron Gods AP, part 1, NPCs import with formula errors.

**Comment by AlphaQup2nite** [comment]
Read the known quirks.  As of now, all class HP is imported as blank, throwing the error, you need to go into classes and change it.  this will occur with everything with class levels until it is fixed.
