### ISSUE TITLE
SBC 2.x Known Quirks

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#344]
**as per Neraidaphobia #9014 (many thanks for that!):**

- THE MOST COMMON ISSUE IS BAD LINE BREAKS DUE TO PDF FORMATING LIMITATIONS.  First transfer to a word processer to remove extra breaks, this fixes 75% of problems.
- A line should never end on a comma.  It is either the sign of a line break or stray punctuation.
- Hard break is required at the end of the entire statblock if it does not end on a "gear," or a non imported section (ecology, special abilities etc.)
- PRCs prevent imports at the moment.  Replace them in the stat block with base classes with the same HD dice size for import, and then change them manually after.
- Hard breaks in the middle of some lines will prevent imports. (Spells/Spell-likes, resistances/immunities, various other stat locations) Copying to a word processor makes it easier to spot missed breaks.
- Bloodline/Domain spell-like abilites almost never import, and must be added in manually.
- Sometimes an import is prevented when a creature only has a fly speed.  Adding a "0 ft.," (0 speed) in front of it can sometimes fix it.
- Other then flying manueverability, often things in parethesis in the speed section, such as limitations on burrow can break imports.
- In the attacks section, everything before the "or" or after must be one continous line without any breaks.
- "Touch" based attacks that have "Touch" after the attack bonus, such as in "Incorporeal Touch +25 Touch" will import as a "+25 touch", as in an attack with +25 enhancement bonus called touch.  Remove the second touch, and manually set it to spell attack melee/ranged.
- Spell-Like usage per day will not import and must be manually edited, exception: At-will is working properly.
- Spells are imported at thier highest available level, and must be adjusted after import to class.
- There should be no breaks at all in the feat section and in the gear section in order for it all to parse properly into the stat block.
- Remove all D (Domain), B(Bonus), M(Mythic), book locations (OH, APG etc) and any other punctuation other than commas from the end of everything, or else they will not link properly to the compendium entry.
- Cleric of XYZ 3 should be changed to Cleric (XYZ) 3 in order to mantain the cleric class tag for some dependancies. This applies to inquistitor as well.
- Alchemist, Mesmerist, Psychic, and many other caster classes will not import their spell/extract list.  Change the class to "Wizard spells prepared" will ensure the will import.  Then fix them manually
- The size catagory must be capitalized.
- Abnormal characters, such as the "1/2" or "1/3" characters can break the import.
- Check for stray punctuation if none of these work.  Even in some printed PDFs typos exist and can break an import.
- Apostrophes do not play nice with the SBC, best to remove them and add them back in later.
- Altering the SBC Buff does nothing, it must be copied first, and the original deleted and then the copy edited to make changed.
- At current version, Class HD is not being calculated, and is being left blank in the HP section under class, and must be manually added.
- Sometimes, but not often, the "Tactic" will break an import if it has too many line breaks in it.  Suspected keywords at the start of lines may be the issue, but it is another potential problem point.  Normally formating does not matter in that section.
- Sometimes cutting out the whole "Spell like ability section" will fix an import that doesnt work.  Just add it in manually later.
- Longer statblocks take longer to parse.
- When you get an error can sometimes tell you what kind of error it is.  If it starts processing for a while, and then stops, its probably an issue in the spells or spell like abilities section.
- When stuck, try taking out all additional information in parathesis except for attacks damage, creature subtypes,caster level information, hitpoint calculations and AC breakdown, and add them back in later.

**Comment by AlphaQup2nite** [comment]
Hp calculation needs to be seperated for multiclassing, even if the HD is the same, so a fighter 1/gunslinger 1 needs to have the hd as 1d10+1d10, not 2d10.  This includes Racial HD as well.

**Comment by AlphaQup2nite** [comment]
Any class names, or keywords in the name will create errors sometimes, so remove them and put them back in after the import.

**Comment by AlphaQup2nite** [comment]
Negative Modifier to attack will throw errors, so take them out before importing, and then add them back in after

**Comment by AlphaQup2nite** [comment]
Archetypes will almost always break the import, so remove them from the class line.

**Comment by AlphaQup2nite** [comment]
Currently there are some issues with importing spell lists for spontaneous casters.  for the present it is better to delete the spells prior to import, and then manually put them in after the import.  The Quick Insert mod makes this a much easier process.

**Comment by Lavaeolous** [comment]
I'll start a new issue to collate "quirks" of 3.x
