### ISSUE TITLE
Skills are not importing

### ISSUE THREAD

**Issue by Absum27** [Lavaeolous/PF1-StatBlock-Converter-Module#346]
Hello, I have tried several different character imports and skills are not importing. Example import below. Thanks.

LADY LUGHNASA CR 14
XP 38,400
CE Large monstrous humanoid
Init +3; Senses darkvision 60 ft.; Perception +14
DEFENSE
AC 31, touch 13, fl at-footed 27 (+8 armor, +3 Dex, +1 dodge, +10 natural, –1 size)
hp 152 (7d10+35 plus 8d6+40 plus 8)
Fort +11; Ref +10; Will +11
DR 2/bludgeoning; Resist fi re 10; SR 25
OFFENSE
Speed 60 ft.
Melee +1 cold iron greatsword +14/+9/+4 (3d6+11/19–20), bite +12 (1d6+3) or bite +17 (1d6+7), 2 claws +17 (1d6+7 plus grab)
Space 10 ft.; Reach 10 ft.
Special Attacks rend (2 claws, 2d6+10)
Spell-like Abilities (CL 15th):
3/day—alter self, fog cloud
Bloodline Spell-like Abilities (CL 8th):
6/day—elemental ray (ranged touch +13, 1d6+4 fire)
Spells Known (CL 8th, 15% chance of arcane spell failure, melee touch +17, ranged touch +13):
4th (3/day)—illusory wall (DC 17)
3rd (6/day)—bestow curse (DC 16), fireball (DC 16), protection from energy
2nd (7/day)—bull’s strength, daze monster (DC 15), eagle’s splendor, scorching ray
1st (7/day)—alarm, burning hands (DC 14), disguise self, identify, ray of enfeeblement, shocking grasp
0 (at will)—acid splash, dancing lights, daze (DC 13), detect magic, detect poison, prestidigitation, read magic, touch of fatigue
Bloodline Elemental (fire)
STATISTICS
Str 25, Dex 16, Con 20, Int 15, Wis 11, Cha 16
Base Atk +11; CMB +19; CMD 33
Feats Alertness, Arcane Armor Training, Blind-Fight, Brew Potion, DodgeB, Eschew MaterialsB, Great Fortitude, Intimidating Prowess, Light Armor Proficiency, Medium Armor Proficiency
Skills Bluff +15, Craft (alchemy) +13, Diplomacy +7, Intimidate +17, Knowledge (arcana) +13, Perception +12, Sense Motive +9, Spellcraft +13, Stealth +6
Languages Common, Giant, Ignan
SQ bloodline arcana (energy damage spells can be changed to fire)
Combat Gear wand of slow (6 charges), potion of cure serious wounds; Other Gear +2 breastplate, +1 cold iron greatsword, bag holding a rotten human head with 2 strings of pearls (250 gp each) stuffed in its mouth.

**Comment by AlphaQup2nite** [comment]
what exactly do you mean?  skills never import to a character sheet (rollable).  The most you will get skills to import atm is to the statblock under notes.

**Comment by Absum27** [comment]
My bad then I thought the total would import, but that makes sense. Thanks.
Respectfully,

Scott Sutton

**Comment by Lavaeolous** [comment]
@Absum27 You are correct, skill parsing is broken currently. Mus have happened in one of the latest system updates.

**Comment by Lavaeolous** [comment]
@Absum27 I've uploaded a new version, please check again if you have the time. Skills should now parse again, but somewhere there's an error in the calculations. So that needs some manual fixing until i've found the source of that.

**Comment by AlphaQup2nite** [comment]
my mistake.  I have hundreds of imports for skills not applying, and as long as i can remember they havent worked.  sorry for the wrong information.

**Comment by Absum27** [comment]
great thank you!
Respectfully,

Scott Sutton

**Comment by Absum27** [comment]
No worries thanks!

Respectfully,

Scott Sutton
