### ISSUE TITLE
Status Update Version 3.x

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#347]
Version 3.x takes longer as planned due to personal reasons - i'm sorry for the delay and the reduced bug fixes and improvements to version 2.x. I'd like to give you a short update to the status on 3.x showcasing some of the new features:

https://user-images.githubusercontent.com/14833806/102714387-7d6e2a00-42ce-11eb-87bd-ac9f441d60ad.mp4

1. The complete code base is new, with just some small regex parts being reused. I could not find another way to reduce the clutter and mess.
2. No more hardcoded templates, yay! I'm grabbing stuff from the system now. As long as it's available in CONFIG.PF1 or in the entity structure, i'll use it. Where no info is available, i still use constants, which are now compartmentalized into a single file. Currently only the descriptions of senses are included there.
3. All Actors and Items are temporary until the import is started. Nonetheless the actors follow all the rules of actor creation in foundry, so it should in theory no longer be so easy to break actors with missing data (e.g. ids) or deprecated key-value pairs.
4. sbc now has a configuration, which allows to set the default actor type, define custom compendiums which should be searched for items as well as the configuration for prototype tokens. If you would like to see something else that should be configurable, let me know.
5. Errors are now logged via a custom error class and, if applicable, highlight the line in which the error occured.

Current Status:
Parsing of Base Data (e.g. everything up until the defense keyword) is mostly done. The only thing missing are classes, genders and races.
Done as well is the Description Data, as that was a low hanging fruit and easy to implement.
All other parsers are still WIP.

I can't give a release date, sorry. Its done when its done, but be sure to let me know of any sbc breaking stuff for v2.x - i'll keep hot fixing that branch until 3.x is ready.

I wish you all happy holidays.

Edit: As seen in the screencast, it seems commas throw of the xp parsing ;)

**Comment by maxipad1991junkmail** [comment]
Thank you for all your hard work on making this. 
2.X is amazingly helpful, and I'm really looking forward to the new enhancements with 3.0.  Keep up the great work!

**Comment by Lavaeolous** [comment]
Happy New Year!

Status Update:

- Base Data now gets parsed completely, including prestige classes and multiclassing
- Work on Statistics Data Parsing started, currently Abilities, BAB, CMB, CMD, Feats and Gear get parsed.
- Gear gets converted into items/placeholders :)

https://user-images.githubusercontent.com/14833806/103437796-22242c00-4c2c-11eb-9dc5-eb805339caf7.mp4
