### ISSUE TITLE
Need a progress bar during import.  Currently, the import is slow and leads people to believe it's not working or already done.

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#352]
When I do an import, I may have aborted several imports that were actually working -- just slow.

While I'd like things to be faster, just knowing the import process is slow but working is enough.

**Comment by Lavaeolous** [comment]
Yeah, that's my experience as well. I *think* the import now is slower than under 2.x as nearly everything now is handled by / pulled from compendia, system data or is using the built in item creation.

From a quick profiling, most of the "slow-ness" comes from item updates after the creation of the actor. As now most features in the statblock get parsed as items (gear, feats, abilities, etc.) the rule may be --> more items, more time to finish stuff. I may need to check if i need all the updates or if i can reduce the impact in another way.

![Screenshot 2021-01-24 222112](https://user-images.githubusercontent.com/14833806/105643832-82f0fe00-5e92-11eb-9ccd-b565fe82ffd6.png)

**Comment by Lavaeolous** [comment]
@adventuremagic123 I've pushed a new version which should in theory reduce loading times by half and which adds partial attack parsing. Feel free to try that again and i'd be happy if you could give me an update if the loading speed changed for you as well.

**Comment by Lavaeolous** [comment]
Added progressbar in 3.2.1
