### ISSUE TITLE
Please support a range of Foundry and PF1e versions

### ISSUE THREAD

**Issue by moorepants** [Lavaeolous/PF1-StatBlock-Converter-Module#353]
I noticed that the tip of master now only supports Foundry 0.7.9. Many of us cannot upgrade Foundry core until all modules we make use of support the latest version. It would be very helpful for users if this module supported a range of Foundry core versions so that we can still obtain improvements and bugfixes without having to be at the latest versions of Foundry. Maybe matching the range of supported versions of the Pf1e system would be good, since that is a dependency of this module.

Thanks for creating this! Saves so much

**Comment by Lavaeolous** [comment]
Hm, i'm not sure how to handle that, as especially the PF1 System Changes with each update more or less break the functionality of SBC. I could include compatibility information for the releases (found under core/releases until i transition to githubs release system), would that help?

**Comment by moorepants** [comment]
> I could include compatibility information for the releases (found under core/releases until i transition to githubs release system), would that help?

I'm not sure exactly what this is proposing (I'm not yet familiar with the details of foundry module development).

From a end-user's perspective, not having to worry at all about module compatibility is the ideal situation. The best way I know to manage that is if all modules try to support a range of versions of their immediate dependencies. This is the "treat as a library" versus "treat as an application" approach to managing version compatability (the later would pin to specific versions but increases the likelihood of version clashes among a set of modules).

On the developer side you have to pollute your code with `if < versionx: do this, else: do that`, which is a burden but it is a burden the developers hold instead of the users. Pinning to specific dependency versions pushes the burden to the user, but the user often doesn't have the ability to solve it easily.

I don't know another way of solving this. It's a problem that is becoming more apparent with Foundry now that the number of modules are growing. I just hit it with this particular module recently.

**Comment by moorepants** [comment]
You can see that PF1e at least is currently supporting 0.7.8-0.7.9: https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/blob/master/system.json#L205. Supporting at least two subsequent Foundry core versions would help.

**Comment by Lavaeolous** [comment]
Yeah, PF1e is supporting 0.7.8-0.7.9, but newer version of PF1e are incompatible to older versions, as changes are not always incremental, but supplemental or are even more in depth. I've pushed a new release using githubs system (v3.0.0-alpha2), which should be more or less usable in FoundryVTT 0.7.8 and 0.7.9, as i included the manifest file and url as well as the zip. The main manifest (which is noted in the readme) should then direct to the latest release.

For upcoming releases i'll generate the binaries and the supporting manifest, save that in the release and keep the main manifest directed to the latest release.

**Comment by Lavaeolous** [comment]
Switched to github releases and updated packages on the foundry package manager.
