### ISSUE TITLE
Add a spell parser

### ISSUE THREAD

**Issue by Ironxxx** [Lavaeolous/PF1-StatBlock-Converter-Module#354]
Hi all, I'd love a spell/power parser that can read spell and power text blocks to enable easy import of spells and powers, e.g., from Ultimate Psionics.

**Comment by Lavaeolous** [comment]
Thats on the to-do list :) Next in line is ranged attacks and other attacks, after that comes spell parsing.

**Comment by Lavaeolous** [comment]
Added as new issue #383
