### ISSUE TITLE
Attacks are too high for monster pulled in.

### ISSUE THREAD

**Issue by dmrickey** [Lavaeolous/PF1-StatBlock-Converter-Module#357]
I pulled in a Glass Wyrm with the stat block pulled from this site I use for quick lookups. http://users.telenet.be/monsteradvancer/PRPG%20Monsters.htm

![image](https://user-images.githubusercontent.com/3664822/107515295-734f0600-6b70-11eb-8359-fd856bd95c2d.png)

Everything looks right but the bonuses on the created attacks are way too high

![image](https://user-images.githubusercontent.com/3664822/107515419-97124c00-6b70-11eb-89ad-55fad0bd1a24.png)

Looking at the image I just pasted in, it looks like it missed the Tail Slap as well

**Comment by Hanhula** [comment]
Current version of SBC doesn't port attacks in. Uninstall your version and reinstall it, there was some mess with 2.x to 3.x

**Comment by Lavaeolous** [comment]
Verified, even in the current version. Seems to be something along the lines of "2+0=20" instead of "2", so i may have forgotten to convert a string to an int somewhere.

**Comment by dmrickey** [comment]
Just a thought, but the bonus says "39", is it somehow taking the values from the improved crit range and adding them together (19-20) and using that for the attack bonus?

**Comment by Lavaeolous** [comment]
Issue still persists for this one. I need to check if its related to primary natural attacks, as its always 5 off.

**Comment by Lavaeolous** [comment]
Yep, this was related to primary and secondary natural attacks. Fixed in 3.0.4
