### ISSUE TITLE
Feature Request: Buff Importing

### ISSUE THREAD

**Issue by maxipad1991junkmail** [Lavaeolous/PF1-StatBlock-Converter-Module#358]
This may fall out of scope since buffs are not part of standard statblocks, but would it be possible to
have the importer look at a compendium(s) designated as buffs and pull in any buffs that match content in the stat block?

Example: Stat block has the feat combat expertise, the spell haste, and a desecration aura as a special ability.

In addition to adding the combat expertise feat, haste to spells (when spells are implemented), and a special ability for desecration aura, the module checks the buff compendium where it finds a buff called combat expertise, a buff called haste, and a buff called desecration?

**Comment by Lavaeolous** [comment]
Uh, i don't think thats possible given my current time restrictions and the variablity involved. As you said, buffs are not noted in the statblocks, so the converted would need to "guess" or derive possible buffs from data given, which would go hand in hand with a lot of uncertainities.

**Comment by maxipad1991junkmail** [comment]
Fair enough.  I was imagining a designated buff compendium(s) where buff names in the compendium would look at the statblock for exact matches of the name of the buff anywhere within the statblock. If it found an exact match (such as a spell name) it would pull that buff and add it to the sheet at the end.

I see how that could get problematic though, especially since a buff could be named anything.

**Comment by Lavaeolous** [comment]
I'll see if any of this is possible when i'm done with 3.x (e.g. sbc is feature complete for standard statblocks)
