### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#364]
Hey, Primer here, the developer of the pf1e statblock converter SBC.

Seeing that i'm currently not able to put as much time into the development of SBC as i would like and as it would need to be called "finished" i'd thought about asking for help. The main part left for the current iteration is the parsing of offensive data, where melee attacks are already implemented and this code can easily be taken for ranged attacks as well. Spell-parsing, special attacks and stuff like that are another story. And overall there are some calculation errors for derived stats and other bugs left for sure as well.

With Foundry 0.8.x on the way and with that the massive changes to the code base, i can't really estimate the work needed to change sbc from the entity-based to the document-based approach.

So, see this as a call to participate: If you are interested in helping, let me know!

**Comment by kmanrulze** [comment]
Might be rather fun if you were able to give a rundown of the codebase and practices used. I'm interested in helping out possibly

**Comment by Lavaeolous** [comment]
Sorry, life got in the way. I'm starting a review of the code with the current system version and will update the issue list accordingly.
