### ISSUE TITLE
Not Importing Racial HD when it has class levels.

### ISSUE THREAD

**Issue by AlphaQup2nite** [Lavaeolous/PF1-StatBlock-Converter-Module#365]
When an NPC has both racial HD and Class levels, the racial HD are not being imported (shows as 0 HD)

**Comment by Lavaeolous** [comment]
Example: https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Amalya

**Comment by Lavaeolous** [comment]
Fixed in v3.1.1
