### ISSUE TITLE
Request - Automatically title case imported names

### ISSUE THREAD

**Issue by dmrickey** [Lavaeolous/PF1-StatBlock-Converter-Module#393]
Most stat blocks have the name as upper case (or at least when they're pulled directly from a PDF). I always rename them so they're title case so my token names aren't "screaming" at me/my players. It would be nice if that could happen automatically

**Comment by Lavaeolous** [comment]
Yeah, i'm running Rappan Athuk currently and there all names are uppercase.
I think i will convert that to Titel Case, but leave words like ["of","the"] etc lowercase.

**Comment by Lavaeolous** [comment]
Added in 3.2.4
