### ISSUE TITLE
A couple of parsing issues off of "Apostle Kyton CR 12"

### ISSUE THREAD

**Issue by dmrickey** [Lavaeolous/PF1-StatBlock-Converter-Module#446]
foundry version - 0.7.10
PF1 - 0.77.24
SC - 3.2.2

https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Apostle%20Kyton

I copy/pasted this stat block as is and it didn't parse the treasure at all
```
Treasure NPC gear (+1 mithral chain shirt, +1 cold iron sickle [2], ring of protection +1, belt of incredible dexterity +2, cloak of resistance +3, other treasure)
```

Also the CMD came in at 35 instead of 33. There are two +1s from the SBC buff. It looks like 1 is from the dodge bonus (that it shouldn't be adding because the Dodge feat is already accounting for that and dodge bonuses stack) and 1 from the deflection bonus (that should have been added in from the ring that was missed above).

 Then it looks like it's adding in 3 "Generic AC - untyped" instead of  "4 Natural AC" to make up for the left over AC

**Comment by Lavaeolous** [comment]
Treasure currently does not get parsed at all.

**Comment by Lavaeolous** [comment]
CMD Validation is calculated wrong
