### ISSUE TITLE
Spell DCs use the total given as DC Modifier instead of calculating the modifier

### ISSUE THREAD

**Issue by dmrickey** [Lavaeolous/PF1-StatBlock-Converter-Module#449]
https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Dybbuk

I imported this creature, checked out the DC for dominate monster, and it was 52 (should be 26(

**Comment by Lavaeolous** [comment]
Spell DCs use the total given as DC Modifier instead of calculating the modifier

**Comment by Lavaeolous** [comment]
Fixed in 3.3.0
