### ISSUE TITLE
Sorry I am so confused

### ISSUE THREAD

**Issue by GrumblyOgre** [Lavaeolous/PF1-StatBlock-Converter-Module#455]
So I am so new to this, and trying to figure out why I can't get any statblock to work.  can anyone help me figure this one out? 

![statblockerrors](https://user-images.githubusercontent.com/84995392/120042636-558e9b00-bfbf-11eb-9d27-d11430f050e6.JPG)

**Comment by Lavaeolous** [comment]
Sure, let me try. You can post the statblock here if you want, than i can take a deeper look.

For starters, there are a lot of linebreaks in the input, try to remove the extra ones, for example:
```
Ulizmila's Cauldron CR 2
XP 600
...
Swallow Whole (Ex) When Ulizmila's Cauldron ...
```

**Comment by Lavaeolous** [comment]
Closed as there are no further questions it seems.
