### ISSUE TITLE
What programs stat blocks is this converter expecting? PCGEN? Herolab? Combat Manager?

### ISSUE THREAD

**Issue by SirDragonClaw** [Lavaeolous/PF1-StatBlock-Converter-Module#460]
What programs stat blocks is this converter expecting? PCGEN? Herolab? Combat Manager?

I cannot find this mentioned anywhere.

**Comment by Lavaeolous** [comment]
SBC parses raw text statblocks as they are found on www.d20pfsrd.com, aonprd.com or in PDFs.  PCGEN, Herolab and Combat Manager should all have an option to export characters/npcs/monsters as statblocks, so these should work as well. In some cases you may need to manually include the section headers paizo uses in their statblock schema, like "Offense", "Defense" and so on.

**Comment by Biscolino** [comment]
For PCGen I recommend to export to the standard > csheet_fantasy_statblock_pathfinder.htm.ftl template. Open it in the browser and copy paste, works for most things.

**Comment by Lavaeolous** [comment]
Closed as no further questions were posted.
