### ISSUE TITLE
Old version module.json problem

### ISSUE THREAD

**Issue by eltosti** [Lavaeolous/PF1-StatBlock-Converter-Module#462]
I'm using Foundry 7.10, and trying to install the module, but because the module. json points to the latest release, it fails.
Is there a plant to change the module. json to point to its specific version?

**Comment by Lavaeolous** [comment]
You can use the release browser here on github to find the latest stable release for the 0.7.x branch, for example
´´´https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/releases/download/v3.2.2/module.json´´´

Foundry in theory should not update to 3.3.0 when the foundry is not in the 0.8.x branch. But to be sure you could lock the module so it's not updated if you hit update all in the module browser.

**Comment by eltosti** [comment]
I tried that, but fail with the error message "Installation Fail: Not Found", I'm not sure why.

**Comment by Lavaeolous** [comment]
Ah, it seems it pointed to the latest release, not the 3.2.2. Could you try again using the manifest link provided above?

**Comment by eltosti** [comment]
It works,Thanks!
