### ISSUE TITLE
Question: What Compendia are checked by default?

### ISSUE THREAD

**Issue by karpana** [Lavaeolous/PF1-StatBlock-Converter-Module#463]
The settings for PF1-SBC indicates seems to indicate that there is a default set of compendia that are checked when importing a stat block.  I want to ensure that I don't add these 'defaults' to the custom compendia (for performance reasons). 

Can you provide a list of which compendia are checked by default?

**Comment by Lavaeolous** [comment]
Good Idea! I'll include this info in the next update in the readme an, if space is available, in the settings.

- pf1.races
- pf1.racialhd
- pf1.classes
- pf1.feats
- pf1.weapons-and-ammo
- pf1.armors-and-shields
- pf1.items
- pf1.class-abilities
- pf1.spells

**Comment by karpana** [comment]
Thank you.

**Comment by Lavaeolous** [comment]
Included in 3.3.1
