### ISSUE TITLE
Parse/Base failed: No creature type found (when using non-english translation for foundry core)

### ISSUE THREAD

**Issue by WiNG-CoMM** [Lavaeolous/PF1-StatBlock-Converter-Module#471]
Greetings,

I am currently using Foundry VTT v. 0.8.7, PF1 v. 0.78.10 and statblock converter v. 3.3.0. At the moment, I can't import any creature. All statblocks, doesn't matter if copied from aonprd or d20pfsrd, fail to import. Error Message is ERROR >> Parse/Base failed: No creature type found.

The preview window shows everything fine, except for the base creature type which is empty. As an example, when trying to parse https://aonprd.com/MonsterDisplay.aspx?ItemName=D%E2%80%99ziriak The preview window just shows "N" on the creature type instead of "N Medium outsider (extraplanar)" as it should

**Comment by WiNG-CoMM** [comment]
I'm doing some tests and it might be related to game language. For our D’ziriak example, if I change input from "N **Medium** outsider (extraplanar)" to "N **Mediano** outsider (extraplanar)" (note, Mediano is spanish for Medium) it does parse its size. Still not the creature type though even if I change it to it's base spanish translation

**Comment by WiNG-CoMM** [comment]
Changed my Foundry back to english and seems to be importing fine again. Something seems odd when using it with Translation: Spanish [Core]

**Comment by Lavaeolous** [comment]
Yeah, had someone on Discord who ran into the same issues. It seems using any language other than english breaks sbc. First guess would be that sheet key names get translated, which leads to sbc no longer finding the correct place to store stuff.

I'll investigate this further!
