### ISSUE TITLE
SBC Can't parse '-' CMB and CMD (like with Swarms)

### ISSUE THREAD

**Issue by Tristan-Goucher** [Lavaeolous/PF1-StatBlock-Converter-Module#474]
I was using the SBC with this statblock:

https://aonprd.com/MonsterDisplay.aspx?ItemName=Undigested%20Swarm

The importer was hanging for the foreseeable future at the "Parsing Statistics" section, so I checked the console. The error is below:

![image](https://user-images.githubusercontent.com/72034470/124228337-ec6bdd00-dac0-11eb-9028-0c3469324040.png)

Setting the CMB and CMD to 10 allowed the monster to import, though I think any number would have worked. Perhaps treat the "-" as "0"?

**Comment by Lavaeolous** [comment]
Fixed in 3.3.1
