### ISSUE TITLE
Broken for all tested inputs as of Foundry 0.8.8 / pf1e 0.78.14

### ISSUE THREAD

**Issue by NorthernTempest** [Lavaeolous/PF1-StatBlock-Converter-Module#475]
Any input I have tried causes the following error, even on a clean world with only sbc as the only module.

Error (from console):
> Uncaught (in promise) TypeError: Cannot read property 'total' of undefined
> &nbsp;&nbsp;at attacksParser.parse (sbcParsers.js:2490)
> &nbsp;&nbsp;at parseOffense (sbcParsers.js:1852)
> &nbsp;&nbsp;at async parseCategories (sbcParsers.js:161)
> &nbsp;&nbsp;at async Function.parseInput (sbcParser.js:212)
> &nbsp;&nbsp;at async Function.prepareInput (sbcParser.js:66)
> &nbsp;&nbsp;at async sbcInput.js:110

**Comment by Lavaeolous** [comment]
Yeah, that issue is known, thanks for including this here i did not have the time.
I'm currently waiting for an update to the system, as there is a broken function sbc uses included there. I may have to revert the dependency on this system function if no solution is available in the near future.

**Comment by Lavaeolous** [comment]
Temporary Actors no longer included all data "normal" actors included. Fixed in 3.3.1

**Comment by NorthernTempest** [comment]
Thanks for posting the fix!
