### ISSUE TITLE
CR and MR not populated

### ISSUE THREAD

**Issue by karpana** [Lavaeolous/PF1-StatBlock-Converter-Module#483]
When a creature with Mythic Ranks is imported, SBC properly parses the SR and MR, but does not populate them into the actor details (`actor.data.data.details.cr` and `actor.data.data.details.mythicTier`).

Attaching an example of a Mythic monster that doesn't work.  ( this was exported from Herolab classic, the "-----" removed and otherwise imports clean)

[Xhamen-Dor.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/7116743/Xhamen-Dor.txt)

**Comment by karpana** [comment]
a bit of fiddling with the statblock reveals that if one removes the slash between CRxx and MRxx (e.g CR26/MR10 -> CR26 MR10), the import tool correctly imports the CR, but not the MR.

Hindsight, I'm not sure if this should or shouldn't be part of Issue #461

**Comment by karpana** [comment]
Attaching another stat block (not from herolab this time) that does the same thing... incorrect population of CR and MR when MR is present. This one is a straight copy-paste from Bestiary 5.

[B5-Anunnaki.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/7116773/B5-Anunnaki.txt)

**Comment by karpana** [comment]
A quick note from the discord community on how this is done via the UI.
https://discordapp.com/channels/170995199584108546/711278873047859201/884460371283423302

**Comment by Lavaeolous** [comment]
SBC currently does not support mythic tiers, i would need to implement that sometime in the future.

**Comment by karpana** [comment]
Thank you for the update.
