### ISSUE TITLE
The module don't work

### ISSUE THREAD

**Issue by Professeur59** [Lavaeolous/PF1-StatBlock-Converter-Module#486]
Hi, i don't know if i have a problem with the version of the module, but when i copy-paste any statblock i have a lot of "error" on the debug screen.
I'm french, i have tried with french and english statblock and ... nothing.
Even i tried to use the bestiary compendium, i click on the button to add the monster on statblock-converter, and have error too.

Anyone can say me why ?

Thank you

**Comment by mkahvi** [comment]
The module seems to work fine (or as fine as it does with english) with different languages in its current state. Is this still a problem? I tested with French and German, if that matters.
