### ISSUE TITLE
Can't import Iron Gods Part 2 - Human Zombie

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#49]
This stat block doesn't import:

Human Zombie      CR 1/2
XP 200
Male human zombie (Pathfinder RPG Bestiary 288)
NE Medium undead
Init +0; Senses darkvision 60 ft.; Perception +0
--------------------
Defense
--------------------
AC 12, touch 10, flat-footed 12 (+2 natural)
hp 12 (2d8+3)
Fort +0, Ref +0, Will +3
DR 5/slashing; Immune undead traits
--------------------
Offense
--------------------
Speed 30 ft.
Melee slam +4 (1d6+4)
--------------------
Statistics
--------------------
Str 17, Dex 10, Con —, Int —, Wis 10, Cha 10
Base Atk +1; CMB +4; CMD 14
Feats Toughness[B]
Languages Common
SQ staggered
--------------------
Ecology
--------------------
Environment any
Organization any
Treasure none
--------------------
Special Abilities
--------------------
Damage Reduction (5/slashing) You have Damage Reduction against all except Slashing attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Staggered (Ex) Make only a single move or a single attack action each round.
Undead Traits Undead have many immunities.
--------------------
*Edit by Lavaeolous: Removed copyrighted content*

**Comment by adventuremagic123** [comment]
All the other stat blocks from Iron Gods Part 2 imported successfully, except for those issues I've posted here.  Congratulations!  Very appreciated!

**Comment by Lavaeolous** [comment]
Thanks for letting me know! I could identify the error here: There is no Entry for Skills (which i up until now used to separate the feats without depending on linebreaks).

Will be fixed soon.

**Comment by Lavaeolous** [comment]
Fixed in 0.3.3
