### ISSUE TITLE
Mark styling is conflicting with all <mark> elements due to lack of specificity

### ISSUE THREAD

**Issue by dmrickey** [Lavaeolous/PF1-StatBlock-Converter-Module#491]
The way SBC is styling marks is pretty non-standard. And since there's no specificity on it, it's breaking all other usages of mark elements

![image](https://user-images.githubusercontent.com/3664822/141824336-34ff07e3-5574-470a-875e-50339feb7678.png)

vs

![image](https://user-images.githubusercontent.com/3664822/141824435-1cb858e8-d702-40f9-bef5-c8cd5eed9b9a.png)

Adding specificity allows your mod to work alongside the default mark stylings
![image](https://user-images.githubusercontent.com/3664822/141825554-7f08afe1-477c-43fb-98f7-2ba05d46f319.png)

**Comment by Lavaeolous** [comment]
Thanks for the feedback, will be integrated in the next release!
