### ISSUE TITLE
Token brightSight recorded as string

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#494]
As per title, not much else to it. They should be numbers instead.

Should be easy fix, just wrap those in parseInt(value, 10)

Offending code:
- https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/blob/10907f24faeeb5046a0b2c6fd498d4adf7411291/statblock-converter/scripts/sbcParsers.js#L794-L795
- https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/blob/10907f24faeeb5046a0b2c6fd498d4adf7411291/statblock-converter/scripts/sbcParsers.js#L822-L823

There might be other instances.

**Comment by Lavaeolous** [comment]
Fixed in 3.3.3
