### ISSUE TITLE
Can't import Iron Gods Part 2 - Hellion

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#50]
This stat block can't be imported for some reason.  It's the most complex in the Iron Gods Part 2 book.

Hellion      CR 6/MR 4
XP 2,400
Hellion
CE Medium artificial intelligence (mythic)
Init +6/-14, dual initiative; Senses Perception +16
--------------------
Defense
--------------------
AC 14, touch 10, flat-footed 14 (+4 natural)
hp 1 (+1)
Fort +2, Ref +2, Will +11
--------------------
Offense
--------------------
Speed 0 ft.
Space 0 ft.; Reach 0 ft.
Special Attacks mythic power (4/day, surge +1d8)
Spell-Like Abilities (CL 8th; concentration +12)
   1/day—align weapon (chaos or evil only), animate rope, chaos hammer (DC 18), command (DC 15), confusion (DC 18), dispel magic, entropic shield, lesser confusion (DC 15), magic circle against good, magic circle against law, minor creation, moonstruck[APG] (DC 18), protection from good, protection from law, rage, stone shape, touch of idiocy, unholy blight (DC 18), wood shape (DC 16)
--------------------
Statistics
--------------------
Str —, Dex —, Con —, Int 14, Wis 17, Cha 19
Base Atk +6; CMB +6; CMD 16
Feats Alertness, Combat Expertise, Improved Initiative[M], Iron Will[M], Technologist
Skills Bluff +15, Disable Device +11, Intimidate +12, Knowledge (engineering) +13, Knowledge (local) +10, Knowledge (religion) +10, Perception +16, Sense Motive +13
Languages Androffan, Orc
SQ impart mythic traits, inherited divinity
--------------------
Special Abilities
--------------------
Combat Expertise +/-2 Bonus to AC in exchange for an equal penalty to attack.
Dual Initiative (Ex) You act a second time each round at -20 from your normal initiative
Impart Mythic Traits (Ex) Hellion has no hit points or natural armor, but when it inhabits a robot, its mythic nature grants the robot a +4 bonus to the robot’s natural armor and an additional 40 hit points. Robots it inhabits do not gain DR/epic, but they do lose their vul
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Inherited Divinity (Su) Hellion can grant divine spells to those who follow its cause, allowing them to select Hellion as their deity for the purposes of determining their spells and domains. Creatures that gain spells from Hellion don’t receive any spells per day of leve
Iron Will [Mythic] Roll Will save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Spell-Like Abilities (Sp) Hellion can cast a few of the spells it grants from its domains as spell-like abilities, provided it has a conduit through which it can manifest the magic. In this adventure, appropriate conduits include its robot chassis and any of the monitors in t
Surge (1d8) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Technologist You are familiar with the basic mechanics of technology.

Benefit: You are considered to be trained in any skill used against a technology-based subject. If the skill in question requires training to use even against non-technological su
--------------------

*Edit by Lavaeolous: Removed copyrighted content*

**Comment by adventuremagic123** [comment]
All the other stat blocks from Iron Gods Part 2 imported successfully, except for those issues I've posted here.  Congratulations!  Very appreciated!

**Comment by Lavaeolous** [comment]
That one is tough, because AIs are weird in pathfinder. I *think* they are not creatures at all but rather a template?

**Comment by adventuremagic123** [comment]
Possibly.  Thanks, again, very much for providing this module.  I couldn't use Foundry VTT without it.

**Comment by adventuremagic123** [comment]
Actually, yes, it's a template that you apply to othet things.  In part 2, this template lives inside a robot.
