### ISSUE TITLE
Manifest download link always points to latest tag

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#501]
I was trying to downgrade to older version since 3.3.3 is broken with Foundry 0.8 but installing the old manifest didn't work.

The cause is that the manifest for all downloads points to the latest tag, which obviously becomes invalid the moment new version

For example:
<https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/releases/latest/download/3.3.1_statblock-converter.zip>

**Comment by Lavaeolous** [comment]
@mkahvi Should be fixed now, for releases 3.3.0 upward. Let me know if anything went wrong!

**Comment by mkahvi** [comment]
Thanks!

3.3.3 wasn't actually broken in 0.8 btw, there was a misunderstanding with my GM. It's still nice to be able to downgrade smoothly.
