### ISSUE TITLE
Reach overwitten by stature

### ISSUE THREAD

**Issue by JAdams0** [Lavaeolous/PF1-StatBlock-Converter-Module#502]
When a monster is imported the reach is correct but it is almost immediately overwritten by stature if they do not match. As an example dire bat has 5 foot reach but is imported as tall instead of long, which immediately sets the reach to 10 feet if you close/open the token or actor. If possible try to import the correct stature for the monsters or set each attack to x feet instead of melee based on reach.

**Comment by Lavaeolous** [comment]
Hm, iirc most statblock contain no info about the stature (long or tall) and the sheet should default to tall i think. I'll try to include a validation of reach in the next version.

**Comment by Lavaeolous** [comment]
Stature now gets "guessed" based on space and reach, with "reach < space" resulting in a `long` stature and everything else in a tall one. Now i'm looking for a place to store contextural reach info (or save it for the validation and then change the reach of a given attack if the name was found in reachContext).
![image](https://user-images.githubusercontent.com/14833806/162751441-9f1559e6-3195-4f86-af0f-cab4abc655db.png)

**Comment by Lavaeolous** [comment]
Partially fixed in 3.3.5
