### ISSUE TITLE
BAB not calculating beyond 1st level

### ISSUE THREAD

**Issue by RobTheDM** [Lavaeolous/PF1-StatBlock-Converter-Module#506]
It seems that when any creature or NPC is imported, the BAB for their class(es) doesn't calculate beyond 1st level despite how many levels or HD they have. The only fix I've found is going in and removing the classes and readding them from the compendium. And I know it wasn't always doing this, the issue seems relatively new. I've ran into the issue now with multiple statblocks, both imported from the statblock library module and directly copy/pasted from aonprd.

**Comment by Lavaeolous** [comment]
I'll check if some of the recent updates to the pathfinder system broke something on my end! Thanks for letting me know

**Comment by RobTheDM** [comment]
Actually now that I've encountered this several more times, it looks like the root issue is it's not counting levels beyond the 1st one. So if you import something with 10 levels of fighter, it just thinks they're level 1. Something with 8 undead HD, nah that's just a 1 HD undead. The last day or two, everything I've imported has had this issue. So something recent must have broken it. It's easy enough to manually fix now that I'm aware of it at least.

**Comment by mkahvi** [comment]
This seems to be because the class records item.data.data.hitDice which is not a thing, deleting that made everything work fine.

**Comment by mkahvi** [comment]
If I had to guess, SBC is currently fetching documents from compendiums and pushing those documents raw for updates, instead of using .toObject() on them to strip derived data and such out.

**Comment by mkahvi** [comment]
Alright, I found the cause.

Item.toObject(false) seems to also include getter values for some reason, which makes it include hitDice getter's value.

**Comment by Lavaeolous** [comment]
Yeah, i think that may be artifacts remaining from the transition to v0.8 of foundry, see #439. It seems to work with `toObject()` now, so the change is fine with me!
