### ISSUE TITLE
Parser fails to find CMB and Concentration bonuses

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#508]
Elder Air Elemental for example fails CMB

Savage Plant Sage fails CMB and concentration

Concentration failure seems to be due to "Conc." string.

CMB failure seems more strange, as testing suggests the source line is altered somewhere for some reason.

For example, input of: `Base Atk +3; CMB +7; CMD 18` becomes `Base Atk +3; CM +7; CMD 18` when it is actually trying to parse CMB, thus never being found.

**Comment by mkahvi** [comment]
CMB issue is caused by this line:  
> .replace(/(APG\b|ACG\b|UE\b|UM\b|HA\b|OA\b|ISWG\b|B\b)/gm, "")

**Comment by Lavaeolous** [comment]
Yeah thats filtering Sourcematerial thats sometimes written in superscript in spells, feats and stuff.

**Comment by mkahvi** [comment]
Simple fix for CMB was this:
> .replace(/(APG\b|ACG\b|UE\b|UM\b|HA\b|OA\b|ISWG\b|[^M]B\b)/gm, "")

**Comment by Lavaeolous** [comment]
Yeah, that should work and leaves only the edge cases of edge cases, where spells/feats are written in caps, end in an `M` and have `B` as source  :) 

But thats totally fine from my side, we can't catch every case of weird formatting.
