### ISSUE TITLE
Can't import Iron Gods Part 2 - Gremlin, Vexgit 

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#51]
The following stat block won't import:

Gremlin, Vexgit      CR 1
XP 400
Male vexgit (Pathfinder RPG Bestiary 2 145)
LE Tiny fey
Init +1; Senses low-light vision; Perception +5
--------------------
Defense
--------------------
AC 15, touch 13, flat-footed 14 (+1 Dex, +2 natural, +2 size)
hp 11 (1d6+5)
Fort +2, Ref +3, Will +3
DR 5/cold iron; SR 12
--------------------
Offense
--------------------
Speed 20 ft., climb 20 ft.
Melee warhammer +0 (1d4-2/×3) or
   bite -2 (1d3-2)
Space 2½ ft.; Reach 0 ft.
Special Attacks speedy sabotage, wrecking crew
Spell-Like Abilities (CL 1st; concentration +1)
   At will—prestidigitation
   1/hour—rusting grasp, snare
--------------------
Statistics
--------------------
Str 6, Dex 13, Con 14, Int 12, Wis 13, Cha 11
Base Atk +0; CMB -1; CMD 7
Feats Skill Focus (Disable Device), Toughness[B], Weapon Finesse[B]
Skills Acrobatics +1 (-3 to jump), Appraise +2, Climb +13, Craft (traps) +3, Disable Device +9, Knowledge (engineering) +2, Perception +5, Stealth +13 (+17 in metal or stony areas, +9 when moving); Racial Modifiers +4 Disable Device, +4 Stealth in metal or stony areas, -4 Stealth when moving
Languages Undercommon
Other Gear warhammer
--------------------
Ecology
--------------------
Environment any underground or urban
Organization solitary, pair, mob (3-12), or infestation (13-20 with 1-3 sorcerers of 1st-3rd level, 1 rogue leader of 2nd-4th level, 2-14 trained dire rats, 2-5 trained venomous snakes, and 1-3 rat swarms)
Treasure standard (warhammer, other treasure)
--------------------
Special Abilities
--------------------
Climb (20 feet) You have a Climb speed.
Damage Reduction (5/cold iron) You have Damage Reduction against all except Cold Iron attacks.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Speedy Sabotage (Su) Vexgits are adept at disassembling machinery, reducing even complex devices to trash with shocking speed. When using the Disable Device skill, these gremlins treat all devices as being one category simpler for the purposes of determining how long it 
Spell Resistance (12) You have Spell Resistance.
Wrecking Crew (Su) A group of up to six vexgits can work together to dismantle a device. This ability functions like the aid another action, but a single vexgit can receive help from up to five other vexgits, granting it up to a +10 bonus on its Disable Device check.

**Comment by adventuremagic123** [comment]
All the other stat blocks from Iron Gods Part 2 imported successfully, except for those issues I've posted here.  Congratulations!  Very appreciated!

**Comment by Lavaeolous** [comment]
Identified Error:  Stealth +13 (+17 in metal or stony areas, +9 when moving)

Multiple Context Modifiers

**Comment by Lavaeolous** [comment]
Fixed in 0.3.3
