### ISSUE TITLE
first time user issues 

### ISSUE THREAD

**Issue by newsies03** [Lavaeolous/PF1-StatBlock-Converter-Module#512]
Estovion Lozarov

CR 9

XP 6,400

Old Male human aristocrat 3/conjurer 7

LE Medium humanoid (human)

Init +7; Senses Perception +2

DEFENSE

AC 23, touch 14, flat-footed 20 (+4 armor, +1 deflection, +3 Dex, +1 natural, +4 shield)

hp 68 (10 HD; 7d6+3d8+27)

Fort +6, Ref +8, Will +12

OFFENSE

Spd 30 ft.

Melee mwk longsword +3 (1d8-3/19-20)

Ranged +1 light crossbow +9 (1d8+1/19-20)

Space 5 ft.; Reach 5 ft.

Arcane School Spell-Like Abilities (CL 7th; concentration +11)
At will—dimensional steps (210 feet/day)
7/day—acid dart (1d6+3 acid)

Conjurer Spells Prepared (CL 7th; concentration +11)
4th—black tentacles, charm monster (DC 18), summon monster IV
3rd—gaseous form, lightning bolt, stinking cloud (DC 17), summon monster III
2nd—darkvision, detect thoughts, dust of twilight* (DC 16), scorching ray, web (DC 16)
1st—expeditious retreat, mage armor, magic missile (2), obscuring mist, shield
0 (at will)—acid splash, detect magic, mage hand, read magic

Prohibited Schools Illusion, Necromancy

TACTICS

Before Combat Estovion casts mage armor every day. If he has the chance, he casts shield and drinks his potion of cat's grace before combat.

During Combat If attacked in the lodge, Estovion screams for help and casts summon monster IV to summon a fiendish dire wolf to protect him. He casts stinking cloud to occupy his foes while he attempts to flee to area D31 (see page 18), using his dimensional steps ability if necessary.

Morale Once in his private office, Estovion disposes of his notes and journals in the fireplace, then uses his dimensional steps ability or scroll of dimension door to teleport outside. Once beyond Ascanor's walls, he immediately flees to the Stairs of the Moon.

Base Statistics Without his spells and potion, Estovion has Init +5; AC 14, touch 13, flat-footed 13; Ref +6; Ranged +1 light crossbow +7 (1d8+1/19-20); Dex 14; CMD 15.

STATISTICS

Str 5, Dex 16, Con 12, Int 18, Wis 14, Cha 12

Base Atk +5; CMB +2; CMD 16

Feats Combat Casting, Craft Wand, Great Fortitude, Improved Initiative, Iron Will, Lightning Reflexes, Scribe Scroll, Toughness

Skills Appraise +9, Bluff +14, Diplomacy +14, Knowledge (arcana) +15, Knowledge (history) +13, Knowledge (local) +13, Knowledge (nature) +11, Knowledge (nobility) +13, Knowledge (planes) +11, Sense Motive +15, Spellcraft +17

Languages Common, Draconic, Elven, Sylvan, Varisian

SQ arcane bond (amulet), summoner's charm (3 rounds)

Combat Gear potion of cat's grace, potion of cure moderate wounds, scroll of dimension door, wand of acid arrow (38 charges); Other Gear +1 light crossbow with 10 bolts, masterwork longsword, amulet of natural armor +1, ring of protection +1, canopic stone (see page 85), master keys to every room in Ascanor Lodge, spell component pouch, spellbook (all prepared spells plus all 0-level spells, acid arrow, dimension door, and four additional spells of levels 1-4), 130 gp

* See the Advanced Player's Guide.

FAILED TO PARCE HUMAN AS RACE

**Comment by Lavaeolous** [comment]
Hey, thanks for the report. I can't seem to reproduce this error. Could you tell me which version of SBC, Pathfinder and Foundry you are using?

**Comment by newsies03** [comment]
I got it, I didn't have everything updated. Thanks for looking at it.  I am
still figuring out Foundry.

**Comment by Lavaeolous** [comment]
No Problem! If you have any problem, feel free to let me know.
