### ISSUE TITLE
SBC mis-converts spell with "Arcane" into "Arcana"

### ISSUE THREAD

**Issue by DrMcCoy** [Lavaeolous/PF1-StatBlock-Converter-Module#515]
When the spells list of a statblock contains the spell "Arcane Eye", the created actor will have a spell "Arcana Eye" instead. Which doesn't exist, so it's a placeholder.

For example: https://www.d20pfsrd.com/bestiary/monster-listings/aberrations/naga/naga-royal/

The same happens for other spells with "Arcane" in them, like "Arcane Lock", "Arcane Sight", ...

**Comment by mkahvi** [comment]
https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/blob/master/statblock-converter/scripts/sbcParser.js#L41

**Comment by DrMcCoy** [comment]
A simple fix, I guess, would be to `s/skills \(.*\)arcane/skills \1arcana/igm` instead (assuming replace() supports backreferences here)? Or does SBC support skills spread out over multiple lines now, which would make this not work?

Or maybe match for `knowledge *( *arcane`, also assuming that at least that isn't going to be spread over two lines.

**Comment by mkahvi** [comment]
The conversion should be only done by skill parser on per-skill basis or whatever uses its result. Not as wholesale conversion on the entire statblock.

**Comment by DrMcCoy** [comment]
That would probably be the proper non-simple fix, yes :P

**Comment by Lavaeolous** [comment]
Will be included in 3.3.5!

**Comment by Lavaeolous** [comment]
Fixed in 3.3.5
