### ISSUE TITLE
SBC no longer parsing Resistances or SR

### ISSUE THREAD

**Issue by Mystara1** [Lavaeolous/PF1-StatBlock-Converter-Module#518]
When converting any actor from compendium, if it has say 'Resist electricity 10; SR 15"
The results are "Resist resist;"
An actor with just SR never gets the SR on import.

If you edit the input to "Resis" it will show the resistances but does not add them to the actor and the SR still doesn't parse

**Comment by Lavaeolous** [comment]
I was on vacation, sorry for the late reply. I'll take a look, most likely the data model of the actor changed.

**Comment by Lavaeolous** [comment]
- Fixed missing SR Info in Preview and Notes Section
- Reverted parsing of Resist back to just looking for "Resist" instead of "Resist" after another keyword.

Issue fixed in 3.5.6
