### ISSUE TITLE
Can't import Iron Gods Part 2 - Rat Swarm

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#52]
The following stat block won't import:

Rat Swarm      CR 2
XP 600
Male rat swarm (Pathfinder RPG Bestiary 232)
N Tiny animal (swarm)
Init +6; Senses low-light vision, scent; Perception +8
--------------------
Defense
--------------------
AC 14, touch 14, flat-footed 12 (+2 Dex, +2 size)
hp 16 (3d8+3)
Fort +4, Ref +5, Will +2
Defensive Abilities swarm traits
--------------------
Offense
--------------------
Speed 15 ft., climb 15 ft., swim 15 ft.
Melee swarm  (1d6 plus distraction and disease)
Space 10 ft.; Reach 0 ft.
Special Attacks distraction (DC 12), filth fever
--------------------
Statistics
--------------------
Str 2, Dex 15, Con 13, Int 2, Wis 13, Cha 2
Base Atk +2; CMB —; CMD —
Feats Improved Initiative, Skill Focus (Perception)
Skills Acrobatics +6 (-2 to jump), Climb +10, Perception +8, Stealth +14, Swim +10
--------------------
Ecology
--------------------
Environment any
Organization solitary, pack (2-5 swarms), or infestation (6-12 swarms)
Treasure none
--------------------
Special Abilities
--------------------
Climb (15 feet) You have a Climb speed.
Disease (DC 12) (Ex) Filth Fever: Swarm attack—injury; save Fort DC 12; onset 1d3 days; frequency 1/day; effect 1d3 Dex and 1d3 Con; cure 2 consecutive saves. The save DC is Constitution-based.
Distraction (DC 12) (Ex) Nauseate foes for 1 rd on failed save. (Fort neg.)
Immunity to Critical Hits You are immune to Critical Hits
Immunity to Flanking You are immune to flanking.
Immunity to Precision Damage You are immune to Precision Damage
Immunity to Staggered Immune to staggered.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Scent (Ex) Detect opponents within 15+ ft. by sense of smell.
Swarm Attack (1d6) Deal listed damage to any creature occupying same space at end of move.
Swarm Traits Imm to effects targeting number of creatures (unless mind affect vs. hive mind).
Swim (15 feet) You have a Swim speed.
--------------------
The clutter of Scrapwall allows for countless hiding places for scavengers, and perhaps the most numerous of those residing in Scrapwall are rats. Nestled in a series of tunnels that run through the mounds of trash is a strange tangle of rats that has achieved a heightened consciousness and now rules a pack of rats. This rat king (Pathfinder RPG Bestiary 4 225) has the ability to bolster the effectiveness of the disease that rats transmit through their bites. The rat king is guarded by a rat swarm (Pathfinder RPG Bestiary 232) and a pair of dire rats (Bestiary 232). The rat king has the ability to speak to the dire rats, and it issues commands that aid the creatures in combat.

**Comment by adventuremagic123** [comment]
All the other stat blocks from Iron Gods Part 2 imported successfully, except for those issues I've posted here.  Congratulations!  Very appreciated!

**Comment by Lavaeolous** [comment]
Identified Error: CMB —; CMD —

**Comment by Lavaeolous** [comment]
Fixed in 0.3.3
