### ISSUE TITLE
When using Wildcard, it breaks a Scene with Actors placed from it

### ISSUE THREAD

**Issue by AndyTheBrave** [Lavaeolous/PF1-StatBlock-Converter-Module#522]
I made a Wildcard Actor without SBC just to be sure--and it worked. However, once I imported a Horse's stats from Pathfinder 1e,  and gave it Wildcard status, I dropped them on to a Scene. At first the Scene works fine, but when refreshed it completely breaks the map, and the Actor must be completely deleted from the Actor tab to fix the Scene.

**Comment by Lavaeolous** [comment]
Could you clarify: Do you mean an actor with a wildcard token image?

**Comment by AndyTheBrave** [comment]
> Could you clarify: Do you mean an actor with a wildcard token image?

Yes, sorry! I was using the wildcard token image feature core to Foundry in combination with sbc.

**Comment by Lavaeolous** [comment]
![image](https://user-images.githubusercontent.com/14833806/170854958-9f9d0d2f-7735-4130-8f3b-a3a528866b3f.png)

I could reproduce that (but not very reliably). I'll have to investigate further, as these errors don't tell me much (apart from starting to look at the resource bars).

**Comment by Lavaeolous** [comment]
Okay, it only happens, when a token using a **new** wildcard image is generated (e.g. this image was not used before by foundry) **and** the actor was created with sbc. Weird.
