### ISSUE TITLE
Senses handling needs to be updated to PF1 0.80.22 compatible state

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#523]
Senses data format was changed significantly with 0.80.22, SBC needs to match this.

**Comment by Lavaeolous** [comment]
Will include this in 3.5.6

**Comment by Lavaeolous** [comment]
Uh, that's a rather large change, sorry that i missed that in my testing!!!

**Comment by Lavaeolous** [comment]
Fixed in 3.3.6, which should be up tomorrow
