### ISSUE TITLE
Some conversions fail to parse

### ISSUE THREAD

**Issue by madmaxamillions** [Lavaeolous/PF1-StatBlock-Converter-Module#524]
Update: Convert only works for some creatures - a reinstall of Foundry itself 'fixed' an issue with the button simply not working from the journal, but it does work for about 2/3 of stat blocks from compendium, and re-importing to journal made the convert button work again but still fail to finish many blocks - not sure if this is something on my end? Apologies if so. Notably: Cizmekris and Grundlescorn (among others) from AP books 99 and 101 fail to ever parse, no "errors" shown in the module info screen about it, it just doesn't ever finish building a stat block. f12 debug info: 
![image](https://user-images.githubusercontent.com/105944581/169674438-d050c0e7-0f96-4751-81c7-affe8e9aa198.png)

Further edit: backed up data files from local and deleted/uninstalled everything, added in just the pf1e system, content (for the ap's), archetypes, and this mod, and it still won't parse specific stat blocks (seems to not like non-humanoids as races? android, hag, devil, vampire all are what are failing to parse, not sure if related or coincidence) -- the strange part, my friend can parse these just fine, which makes no sense from a complete fresh install.

**Comment by Lavaeolous** [comment]
On first glance it seems the button is now deactivated for locked compendiums. That seems to be an issue of the library itself, which is why i opened an issue there: https://github.com/baileymh/statblock-library/issues/15

**Comment by Lavaeolous** [comment]
Seems to be fixed on the side of the statblock library.
