### ISSUE TITLE
Spells are not being imported, though spell-likes seem to work.

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#530]
In general, spells from Hero Lab statblocks don't seem to be importing.  I've tried several over time and none have worked.

The latest example is the statblock for "Pyromaniac Mage" and it's only CR 12:

Pyromaniac Mage      CR 12
XP 19,200
Male human evoker 13
CE Medium humanoid (human)
Init +6; Senses Perception +12
--------------------
Defense
--------------------
AC 19, touch 14, flat-footed 16 (+4 armor, +1 deflection, +2 Dex, +1 dodge, +1 natural)
hp 81 (13d6+33)
Fort +9, Ref +11, Will +12
Resist fire 30
--------------------
Offense
--------------------
Speed 40 ft.
Melee club +6/+1 (1d6)
Special Attacks intense spells (+6 damage)
Arcane School Spell-Like Abilities (CL 13th; concentration +19)
   At will—elemental wall (13 rounds/day)
   9/day—force missile (1d4+6)
Evoker Spells Prepared (CL 13th; concentration +19)
   7th—delayed blast fireball (DC 25), statue (DC 23)
   6th—greater dispel magic, elemental body III, maximized fireball (DC 21), maximized fireball (DC 21)
   5th—passwall, maximized scorching ray, maximized scorching ray, telekinesis (DC 21), waves of fatigue
   4th—maximized burning hands (2, DC 19), greater invisibility, phantasmal killer (DC 20), shout (DC 22), wall of fire
   3rd—dispel magic, explosive runes, fireball (DC 21), flame arrow, fly, protection from energy
   2nd—flaming sphere (DC 20), gust of wind (DC 20), pyrotechnics (2, DC 18), resist energy, scorching ray, web (DC 18)
   1st—burning hands (DC 19), expeditious retreat, grease, mage armor, magic missile, magic missile, ray of enfeeblement (DC 17)
   0 (at will)—bleed (DC 16), dancing lights, mage hand, open/close (DC 16)
   Opposition Schools Divination, Enchantment
--------------------
Tactics
--------------------
Before Combat The wizard casts mage armor, protection from energy (fire), resist energy (fire), and statue.
During Combat The wizard casts greater invisibility, fly, and maximized fireball. He follows up with phantasmal killer, shout, and necromantic rays.
--------------------
Statistics
--------------------
Str 10, Dex 14, Con 14, Int 22, Wis 9, Cha 12
Base Atk +6; CMB +6; CMD 20
Feats Combat Casting, Craft Wondrous Item, Dodge, Greater Spell Focus (evocation), Improved Initiative, Iron Will, Lightning Reflexes, Maximize Spell, Point-Blank Shot, Scribe Scroll, Spell Focus (evocation)
Skills Acrobatics +2 (+6 to jump), Climb +5, Craft (alchemy) +19, Fly +18, Knowledge (arcana) +21, Knowledge (engineering) +19, Knowledge (geography) +14, Knowledge (history) +14, Knowledge (local) +14, Knowledge (planes) +19, Knowledge (religion) +14, Perception +12, Sense Motive +4, Spellcraft +19, Stealth +12, Survival +4
Languages Abyssal, Common, Draconic, Dwarven, Goblin, Ignan, Infernal
SQ arcane bond (ring of protection +1)
Combat Gear fire elemental gem, potion of cure moderate wounds (2), potion of invisibility, scroll of protection from energy (CL 4th) (2), scroll of resist energy (2), wand of burning hands (CL 5th, 20 charges), alchemist's fire (10); Other Gear club, amulet of natural armor +1, boots of striding and springing, bracers of armor +3, cloak of resistance +3, headband of vast intelligence +4, ring of protection +1, spellbook, 1,100 gp
--------------------
Special Abilities
--------------------
Arcane Bond (Ring of protection +1) (1/day) (Sp) Use object to cast any spell in your spellbook. Without it, Concentration required to cast spells (DC20 + spell level).
Combat Casting +4 to Concentration checks to cast while on the defensive.
Divination You must spend 2 slots to cast spells from the Divination school.
Elemental Wall (13 rounds/day) (Sp) Create wall of one chosen energy type, otherwise as wall of fire.
Enchantment You must spend 2 slots to cast spells from the Enchantment school.
Energy Resistance, Fire (30) You have the specified Energy Resistance against Fire attacks.
Evocation Evokers revel in the raw power of magic, and can use it to create and destroy with shocking ease.
Force Missile (1d4+6, 9/day) (Sp) As a standard action, magic missile strikes a foe.
Greater Spell Focus (Evocation) +1 to the Save DC of spells from one school.
Intense Spells (+6 damage) (Su) Evocation spells deal listed extra damage.
Maximize Spell All variable effects of a spell are maximized. +3 Levels.
Point-Blank Shot +1 to attack and damage rolls with ranged weapons at up to 30 feet.
Spell Focus (Evocation) Spells from one school of magic have +1 to their save DC.
--------------------
These mages love to cause collateral damage with fires.
--------------------
Additional Details
--------------------
Base Statistics Without mage armor, protection from energy, and resist energy, the wizard's statistics are AC 15, touch 14, flat-footed 12; Immune none; Resist none.

**Comment by adventuremagic123** [comment]
I'm using the latest releases for FVTT, PF1e game system, and sbc module.

<img width="224" alt="1" src="https://user-images.githubusercontent.com/50708405/173256539-2ff19c2a-1a0c-490e-9e05-ce94c27903e3.png">

<img width="512" alt="2" src="https://user-images.githubusercontent.com/50708405/173256600-d801d7f5-8ab0-497b-a26d-9c15b5d56b97.png">

**Comment by adventuremagic123** [comment]
I've attached the text for the statblock below:

[Pyromaniac Mage.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/8886943/Pyromaniac.Mage.txt)

**Comment by adventuremagic123** [comment]
This is the only major issue I'm aware of.  Fixing it would greatly improve my FVTT experience and I would stop crying in my sleep.  :)

**Comment by Lavaeolous** [comment]
Oh, i don't want you crying in my sleep :D I'll try to replicate that.
