### ISSUE TITLE
Issue parsing attacks.

### ISSUE THREAD

**Issue by Basqueeroni** [Lavaeolous/PF1-StatBlock-Converter-Module#532]
Getting stuck on the offensive section. The only way to get it to parse seems to be to remove the melee and ranged sections of the statblock.

 The issue seems to be happening to multiple users.

The latest PF1e system patch has changed how attacks are generated. (Likely the cause according to a community helper in the Pf1e section of the FVTT Discord.)

**Comment by Lavaeolous** [comment]
Yep, see issue #529

**Comment by Basqueeroni** [comment]
I did not recognize that as a duplicate issue.  

If it adds to the discussion at all, this issue did not arise for me until the latest update for pf1e this week.

**Comment by Lavaeolous** [comment]
Yeah, because the system changed the way it handles attacks significantly.
