### ISSUE TITLE
Babele seems to mess with the converter

### ISSUE THREAD

**Issue by guillaume-gc** [Lavaeolous/PF1-StatBlock-Converter-Module#548]
I'm currently using [Babele](https://gitlab.com/riccisi/foundryvtt-babele) alongside [foundryvtt-pf1-fr-babele](https://github.com/DjLeChuck/foundryvtt-pf1-fr-babele) to automatically translate official compendia, and it seems to mess up with converter.

I'm aware this is not caused by Foundry core, and I'll understand if you have no plan to address those issues. Nonetheless, it doesn't cost anything to point it out, right?

Here is a list of problems I have found: 
- It creates new skills instead of using translated ones
- It has some fatal issues with creature type
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'data')
[Detected 1 package: pf1-statblock-converter]
    at creatureTypeParser.parse (VM7700 sbcParsers.js:716:36)
    at async parseBase (sbcParsers.js:369:63)
    at async parseCategories (sbcParsers.js:161:13)
    at async sbcParser.parseInput (sbcParser.js:207:58)
    at async sbcParser.prepareInput (sbcParser.js:61:13)
    at async sbcInput.js:112:17
```

No idea if there is an easy way to handle that, or perhaps just adding more type safety so that compendia not found / compendium entries not found is less likely to cause a problem.

Anyway great module, cheers!

**Comment by guillaume-gc** [comment]
Here is the monster I tried to import: https://www.d20pfsrd.com/bestiary/monster-listings/vermin/ant/ant-giant-worker/ , it worked perfectly well without Babele.

**Comment by Lavaeolous** [comment]
Yeah i am not sure i can fix that, as sbc works on a keyword basis and i have no idea when and how babele interjects or changes strings. I'll keep this issue up as info for others, but i don't think i can work on this in the near future.
