### ISSUE TITLE
Import Still not working

### ISSUE THREAD

**Issue by Myronnis** [Lavaeolous/PF1-StatBlock-Converter-Module#581]
I'm trying to use Import statblock Jabral Louslik for Hell's Vengeance Adventure Path and it's showing me this error

![image](https://user-images.githubusercontent.com/18298758/192123619-f0e2935f-008d-4d1d-8146-f9dc7914ba98.png)

**Comment by Lavaeolous** [comment]
Which version of Foundry are you using? SBC is not yet compatible to v10.

**Comment by Myronnis** [comment]
Oh I thought you found a workaround, i'll try to revert to 9

**Comment by Lavaeolous** [comment]
Or you can wait like a week, the update should be ready then
