### ISSUE TITLE
Racial modifier is incorrectly doubled up as ranks

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#600]
For example, Hobgoblin: <https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Hobgoblin>  
They have +4 racial modifier to stealth, no stated ranks. The imported sheet has 4 ranks in stealth in the end AND they have +4 racial modifier in the race.

**Comment by Lavaeolous** [comment]
I'm currently not doing anything with racial modifiers (see Changelog v3.1.1), as these are values that should already be known by the total and the changes in the race.

I'll have to investigate, but i think i currently do not check existing race items for skill changes, so these get ignored when calculating how many ranks need to be put into a skill. Which in turn leads to the buff needing to compensate at the end when everything is known.
