### ISSUE TITLE
Missing armor leads to unnecessary adjustment of ACP affected skills

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#601]
For example, Hobgoblin: <https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Hobgoblin>

Studded leather is not added to the sheet, but if it was, it would give 1 ACP that would together with the Dex lead to the correct final modifier, needing no adjustment in the corrective buff.

The above assumes #600 is also fixed.

**Comment by Lavaeolous** [comment]
This seems to be an issue specific for the Hobgoblin, as thats using
```
Treasure NPC Gear (studded leather armor, light steel shield, longsword, longbow with 20 arrows, other treasure)
```
There's issues with that:
*  For Gear, i'm only checking the lines that start with `/(Combat Gear|Other Gear|Gear)\b/`
*  I do not parse treasure at all
*  Treasure is parsed in the `Ecology` section, Gear in the `Statistics` section

In that case, from a technical standpoint of the statblock, the Hobgoblin is not wearing the armor, but just carrying it around as treasure 🗡️ :)

I do not think i have an easy solution for that.

**Comment by mkahvi** [comment]
Could add special case for "Gear"/"NPC Gear" appearing there.

**Comment by Lavaeolous** [comment]
There's no easy fix, sorry. Ecology parsing happens after everything with values was parsed, so i'd need to pull it in front to be parsed after statistics but before defense and offense.

I'll add a info into the error section for users, so they can copy the data to the correct section themselves.

**Comment by Lavaeolous** [comment]
I've added a (quite hacky) workaround for this to v4.0.2


https://user-images.githubusercontent.com/14833806/198870127-c9e4f95b-aa97-4f50-bbb4-4f192ffde03c.mp4
