### ISSUE TITLE
Import is not appearing in Actor directory

### ISSUE THREAD

**Issue by dogstarrb** [Lavaeolous/PF1-StatBlock-Converter-Module#602]
I just got this module as I am trying PF1 in Foundry for the first time. I have enabled the module, but no import button appears. I have another module of statblock journal entries that include an "import through sbc" button, and that isn't working either- however no import option appears even when sbc is the only module installed. Not sure if this is a bug or something I am doing wrong, please advise.

**Comment by Lavaeolous** [comment]
Hey, which version of sbc and foundry are you using? sbc v4.0.0 only works on the v10 version of foundry.

I think the statblock library module is not yet v10 compatible, but i'm not the dev of that module so i dont really know, sorry.

**Comment by Lavaeolous** [comment]
As there was no further feedback, i guess this was relating to the statblock library.
