### ISSUE TITLE
The import window doesn't open when using the "import statblock" button in the statblocks themselves.

### ISSUE THREAD

**Issue by LagiaDOS** [Lavaeolous/PF1-StatBlock-Converter-Module#605]
When I open a statblock journal entry from the compendium and I click in the "Import statblock" button embbeded on it, it doesn't do anything. I can still import manually via copy pasting the statblock and the option in the actors tab, but it's quite inconvenient that it I can't do it in that way.

**Comment by Lavaeolous** [comment]
Hey, the statblock library is a different module thats maintained by someone else. I created a pull request there to bring that module up to v10 compatibility, but the other dev will have to accept and then release a new version.
