### ISSUE TITLE
Vision Settings need to set custom vision rules as well

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#606]
e.g. if vision is disabled but the toggle for custom vision rules is not set, the setting gets ignored.

**Comment by mkahvi** [comment]
Should favor setting proper senses on actor instead of modifying the token. PF1 takes over the token configuration, so what the token has is not so important.

**Comment by Lavaeolous** [comment]
The vision settings are primarily for my personal needs as gm, as i like to have all npcs / creatures with vision activated, just so that i can see everything even if i have a token selected. For that i overwrite the token, but do not change the senses on the actor.
