### ISSUE TITLE
Buff DataModel is probably broken

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#611]
Deleting a conversion buff change always deletes the last change, not the one selected

**Comment by mkahvi** [comment]
It needs `_id` instead of `id`, which is probably the primary problem.

`target` is no longer used, so it's excess data.

PF1 uses `randomID(8)` instead of `randomID(16)` for Change IDs but this is not actually bad.
