### ISSUE TITLE
Make generation of conversion buff optional

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#612]

**Comment by Eagle0600** [comment]
I would say make it off by default. Since it's often wrong, it's unreliable. If you can't trust it worked properly and have to double-check everything anyway, adjusting manually should be the assumed method of dealing with imports.

**Comment by mkahvi** [comment]
Making the numbers correct without the corrective buff is definitely the desired goal.

If there's issues with doing that due to math not working correctly in PF1 should be reported to the game system.

**Comment by Lavaeolous** [comment]
> Making the numbers correct without the corrective buff is definitely the desired goal.
> 
> If there's issues with doing that due to math not working correctly in PF1 should be reported to the game system.

There will never be a complete parity between the values in the statblock and the ones in the system simply because a non-zero number of statblocks has wrong values in them. So the question is do we want the "correct" values as derived by the system, or do we want the values as presented in the statblock. That was one of the reasons i've started using the conversion buff in the first place.

Apart from the conversion buffs (which are created after the actor is complete) a number of adjustments are done while parsing, e.g. attack or damage modifiers.

I'll have to find all these and only invoke them if this future setting "try to validate values and create adjustments and conversion buffs" is set to true.

**Comment by Eagle0600** [comment]
When the derived values in a statblock are clearly miscalculated, they are a mistake. When the publisher has made a mistake, I go with the correct derived values rather than what is written.
