### ISSUE TITLE
Attack and Damage Bonus Doubled

### ISSUE THREAD

**Issue by luminousgrue** [Lavaeolous/PF1-StatBlock-Converter-Module#616]
Converter is parsing the to-hit and damage values from a complete stat block as a bonus _in addition_ to the normally calculated values. For example, given BAB 5 and Str 12 (+1), the attack line "Slam attack +6 (1d6+1)" is parsed by the module as an attack with +12 (BAB + Str + SBC manual adjustment) for 1d6+2 (Str + SBC manual adjustment).

**Comment by Lavaeolous** [comment]
Should be fixed in 4.0.3
