### ISSUE TITLE
[v10] Issues with Immunities and Resistances

### ISSUE THREAD

**Issue by Fair-Strides** [Lavaeolous/PF1-StatBlock-Converter-Module#626]
Using PF1E 0.82.5 and SBC 4.0.3, I've noticed that the Immune and Resist sections in defenses are not being processed correctly.

Using a Thanadaemon as an example (the statblock was pulled from the "Bestiaries 1-3" journal compendium from the statblock library module), none of the immunities or resistances are in the actor, with the sole exception that "death effects" was put in as a custom "Death" text in the Immunities window.

I don't think I've noticed anything glaring after that, though it seems that the SBC buff gets finalized before feats are added; it seems that the +1 Dodge bonus from Dodge is added to the buff, then the Dodge feat is added, resulting in an extra point of AC.

**Comment by Lavaeolous** [comment]
It's been awhile since the last version. I'll take a look now that system development has started again
