### ISSUE TITLE
Question:  Is it possible to update the text of the statblock, and reimport?

### ISSUE THREAD

**Issue by karpana** [Lavaeolous/PF1-StatBlock-Converter-Module#629]
Is there a way to "update the notes" of the a given actor with an updated statblock, and reimport the actor via SBC?

I ask because, my players update their statblocks in Herolab.Online, and when I create a new actor, I have to fight with permissions.  It'd be nice to juste "update and reimport" the existing actor.

**Comment by Lavaeolous** [comment]
SBC only takes input and creates an actor from that. It has no ways to interact with already existing actors. I would propose to simply reimport the actors after level up and set the permission again. The [Permission Viewer](https://foundryvtt.com/packages/permission_viewer/) module can help with that i think.

**Comment by karpana** [comment]
Thank you.
