### ISSUE TITLE
Import [creature] with SBC on journal entries appears to do nothing

### ISSUE THREAD

**Issue by coyoteconscious** [Lavaeolous/PF1-StatBlock-Converter-Module#630]
On journal entries containing creatures/npcs, there is a button labeled "Import [creature] with SBC".

Clicking this button does nothing. Hovering does not change the cursor as would be expected from a link or button. Double-clicking causes it to be selected as if it were normal block text.

Nothing appears to be imported anywhere - it doesn't import to the "SBC | Imported Statblocks" actors folder or anywhere else. It does not copy a statblock for importing via the main dialog. It doesn't look like it does anything at all.

I've tried disabling everything except SBC and the PF1e statblock library. Foundry VTT version 10 Build 291, SBC 4.0.3, and the behavior persists. I can manually copy and paste text and paste it into the manual statblock converter and it works fine, but it won't do an import by clicking the button.

I've also tried copying journal entries out of the compendiums into the main journal entries tab, and then clicking the SBC import from there, and it also does nothing.

**Comment by Lavaeolous** [comment]
Hey, it seems the button is broken in the library module then. I'm not sure if that one is still maintained, you could check the github of that module.

I know that i fixed that issue once before and made a pr for it, but have not actively checked for quite some time.

**Comment by coyoteconscious** [comment]
Thanks! I ended up uninstalling and reinstalling everything from scratch, and now everything's working. Not sure which library module you mean, but I scrubbed and reinstalled everything, so whatever it was, it works now.
