### ISSUE TITLE
Defenses error with pf1 v9.x

### ISSUE THREAD

**Issue by ming17** [Lavaeolous/PF1-StatBlock-Converter-Module#633]
While trying to import any statblock into pf v9.x, energy resistances and DR don't import correctly.

When trying to add them manually via `Attributes`, you get the following error:

`foundry.js:5919 TypeError: Cannot read properties of undefined (reading 'map')
    at ActorResistanceSelector._updateObject (damage-resistance-selector.mjs:153:34)
    at ActorResistanceSelector._onSubmit (foundry.js:5916:18)`

Unrelated, SR is also not parsed, although this can be entered manually.

**Comment by Lavaeolous** [comment]
Hey, the module ownership changed, as i no longer have time to maintain it.
New versions will be released here: https://gitlab.com/foundryvtt_pathfinder1e/pf1-statblock-converter

Please report any issues there!
