### ISSUE TITLE
Can't import Bestiary - Bat Swarm

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#67]
Can't import the following statblock:

Bat Swarm      CR 2
XP 600
Male bat swarm (Pathfinder RPG Bestiary 30)
N Diminutive animal (swarm)
Init +2; Senses blindsense 20 ft., low-light vision; Perception +11 (+15 when using blindsense)
--------------------
Defense
--------------------
AC 16, touch 16, flat-footed 14 (+2 Dex, +4 size)
hp 13 (3d8)
Fort +3, Ref +7, Will +3
Defensive Abilities swarm traits
--------------------
Offense
--------------------
Speed 5 ft., fly 40 ft. (good)
Melee swarm  (1d6 plus distraction)
Space 10 ft.; Reach 0 ft.
Special Attacks distraction (DC 11), wounding
--------------------
Statistics
--------------------
Str 3, Dex 15, Con 11, Int 2, Wis 14, Cha 4
Base Atk +2; CMB —; CMD —
Feats Lightning Reflexes, Skill Focus (Perception)
Skills Acrobatics +2 (-10 to jump), Fly +12, Perception +11 (+15 when using blindsense); Racial Modifiers +4 Perception when using blindsense
--------------------
Ecology
--------------------
Environment any temperate or tropical
Organization solitary, pair, flight (3-6 swarms) or colony (11-20 swarms)
Treasure none
--------------------
Special Abilities
--------------------
Blindsense (20 feet) (Ex) Sense things and creatures without seeing them.
Distraction (DC 11) (Ex) Nauseate foes for 1 rd on failed save. (Fort neg.)
Fly (40 feet, Good) You can fly!
Immunity to Critical Hits You are immune to Critical Hits
Immunity to Flanking You are immune to flanking.
Immunity to Precision Damage You are immune to Precision Damage
Immunity to Staggered Immune to staggered.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Swarm Attack (1d6) Deal listed damage to any creature occupying same space at end of move.
Swarm Traits Imm to effects targeting number of creatures (unless mind affect vs. hive mind).
Wounding (Ex) Any living creature damaged by a bat swarm continues to bleed, losing 1 hit point per round thereafter. Multiple wounds do not result in cumulative bleeding loss. The bleeding can be stopped by a DC 10 Heal check or the application of a cure spell or

**Comment by Lavaeolous** [comment]
Looks like #52 again.

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.
