### ISSUE TITLE
Can't import Bestiary - Balor (Demon)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#69]
Can't import statblock:

Balor (Demon)      CR 20
XP 307,200
Male balor (Pathfinder RPG Bestiary 58)
CE Large outsider (chaotic, demon, evil, extraplanar)
Init +11; Senses darkvision 60 ft., low-light vision, true seeing; Perception +38
Aura flaming body, unholy aura (DC 26)
--------------------
Defense
--------------------
AC 36, touch 20, flat-footed 29 (+4 deflection, +7 Dex, +16 natural, -1 size)
hp 370 (20d10+260)
Fort +29, Ref +17, Will +25
DR 15/cold iron, 15/good; Immune electricity, fire, poison; Resist acid 10, cold 10; SR 31
--------------------
Offense
--------------------
Speed 40 ft., fly 90 ft. (good)
Melee +1 vorpal unholy longsword +29/+24/+19/+14 (2d6+13/19-20 plus 2d6 vs. good), +1 vorpal flaming whip +28/+23/+18 (1d4+7 plus 1d6 fire and entangle) or
   2 slams +31 (1d10+12)
Space 10 ft.; Reach 10 ft. (20 ft. with +1 vorpal flaming whip)
Spell-Like Abilities (CL 20th; concentration +28)
   Constant—true seeing, unholy aura (DC 26)
   At will—dominate monster (DC 27), greater dispel magic, greater teleport (self plus 50 lbs. of objects only), power word stun, telekinesis (DC 23)
   3/day—quickened telekinesis (DC 23)
   1/day—blasphemy (DC 25), fire storm (DC 26), implosion (DC 27), summon (level 9, any 1 CR 19 or lower demon 100%)
--------------------
Statistics
--------------------
Str 35, Dex 25, Con 36, Int 24, Wis 24, Cha 27
Base Atk +20; CMB +33; CMD 54
Feats Cleave, Combat Reflexes, Greater Two-weapon Fighting, Improved Initiative, Improved Two-weapon Fighting, Iron Will, Power Attack, Quicken Spell-Like Ability (telekinesis), Two-weapon Fighting, Weapon Focus (longsword)
Skills Acrobatics +27 (+31 to jump), Bluff +31, Diplomacy +31, Fly +32, Intimidate +31, Knowledge (history) +27, Knowledge (nobility) +27, Knowledge (planes) +30, Knowledge (religion) +27, Perception +38, Sense Motive +30, Stealth +26, Use Magic Device +31; Racial Modifiers +8 Perception
Languages Abyssal, Celestial, Draconic; telepathy 100 ft.
SQ death throes, vorpal strike, whip mastery
Other Gear +1 vorpal flaming whip, +1 vorpal unholy longsword
--------------------
Ecology
--------------------
Environment any (abyss)
Organization solitary or warband (1 balor and 2-5 glabrezus)
Treasure standard (+1 unholy longsword, +1 flaming whip, other treasure)
--------------------
Special Abilities
--------------------
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Combat Reflexes (8 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (15/cold iron) You have Damage Reduction against all except Cold Iron attacks.
Damage Reduction (15/good) You have Damage Reduction against all except Good attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Death Throes (DC 33) (Su) When killed, a balor explodes in a blinding flash of fire that deals 100 points of damage (half fire, half unholy damage) to anything within 100 feet (Reflex DC 33 halves). The save DC is Constitution-based.
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Cold (10) You have the specified Energy Resistance against Cold attacks.
Flaming Body (Su) Foe striking balor with natural weapon takes 1d6 fire damage. Grappling balor inflicts 6d6 fire damage.
Fly (90 feet, Good) You can fly!
Immunity to Electricity You are immune to electricity damage.
Immunity to Fire You are immune to fire damage.
Immunity to Poison You are immune to poison.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -6/+12 You can subtract from your attack roll to add to your damage.
Quicken Spell-Like Ability (Telekinesis) Spell-like ability is cast as a swift action up to 3/day.
Spell Resistance (31) You have Spell Resistance.
Summon (level 9, any 1 CR 19 or lower demon 100%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.
Vorpal Strike (Su) Slashing weapons gain vorpal quality when wielded.
Whip Mastery (Ex) A balor treats a whip as a light weapon for the purposes of two-weapon fighting, and can inflict lethal damage on a foe regardless of the foe's armor.

**Comment by adventuremagic123** [comment]
My guess is that none of the NPCs with "name (something)" pattern are importing, so I will stop reporting these.

**Comment by adventuremagic123** [comment]
No, I'm wrong.  The "Dretch (Demon)" demon imports.

**Comment by Lavaeolous** [comment]
Identified Issue: Creatures with multiple Auras

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
Fixed in 0.3.5
