### ISSUE TITLE
Can't import Bestiary - Ice Devil

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#70]
Can't import the following statblock:

Ice Devil      CR 13
XP 25,600
Male ice devil (Pathfinder RPG Bestiary 77)
LE Large outsider (devil, evil, extraplanar, lawful)
Init +9; Senses darkvision 60 ft., see in darkness; Perception +27
Aura fear (10 ft., DC 22)
--------------------
Defense
--------------------
AC 32, touch 14, flat-footed 27 (+5 Dex, +18 natural, -1 size)
hp 161 (14d10+84); regeneration 5 (good weapons, good spells)
Fort +15, Ref +14, Will +12
DR 10/good; Immune cold, fire, poison; Resist acid 10; SR 24
--------------------
Offense
--------------------
Speed 40 ft., fly 60 ft. (good)
Melee +1 frost spear +21/+16/+11 (2d6+10/×3 plus slow and 1d6 cold) or
   bite +14 (2d6+3), tail slap +14 (3d6+3 plus slow)
Space 10 ft.; Reach 10 ft.
Spell-Like Abilities (CL 13th; concentration +18)
   Constant—fly
   At will—cone of cold (DC 20), greater teleport (self plus 50 lbs. of object only), ice storm, persistent image (DC 20), wall of ice (DC 19)
   1/day—summon (level 4, 2 bone devils, 50%)
--------------------
Statistics
--------------------
Str 23, Dex 21, Con 22, Int 25, Wis 22, Cha 20
Base Atk +14; CMB +21; CMD 36
Feats Alertness, Cleave, Combat Reflexes, Improved Initiative, Iron Will, Power Attack, Weapon Focus (spear)
Skills Acrobatics +22 (+26 to jump), Bluff +22, Diplomacy +22, Fly +14, Intimidate +19, Knowledge (Enter Choice) +21, Knowledge (Enter Choice) +21, Knowledge (Enter Choice) +21, Knowledge (planes) +23, Perception +27, Sense Motive +27, Spellcraft +21, Stealth +18, Survival +23
Languages Celestial, Common, Draconic, Infernal; telepathy 100 ft.
Other Gear +1 frost spear
--------------------
Ecology
--------------------
Environment any (hell)
Organization solitary, team (2-3), council (4-10), or contingent (1-3 ice devils, 2-6 horned devils, and 1-4 bone devils)
Treasure standard (+1 frost spear, other treasure)
--------------------
Special Abilities
--------------------
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Combat Reflexes (6 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (10/good) You have Damage Reduction against all except Good attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Fear Aura (10 feet, DC 22) Foes within radius are affected by the fear spell.
Fly (60 feet, Good) You can fly!
Immunity to Cold You are immune to cold damage.
Immunity to Fire You are immune to fire damage.
Immunity to Poison You are immune to poison.
Power Attack -4/+8 You can subtract from your attack roll to add to your damage.
Regeneration 5 (good weapons, good spells) Heal HP quickly and cannot die.
See in Darkness See perfectly in darkness of any kind, including magical darkness.
Spell Resistance (24) You have Spell Resistance.
Summon (level 4, 2 bone devils, 50%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.

**Comment by Lavaeolous** [comment]
Same as #73

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.
