### ISSUE TITLE
Can't import Bestiary - Lemure (Devil)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#71]
Can't import statblock:

Lemure (Devil)      CR 1
XP 400
Male lemure (Pathfinder RPG Bestiary 79)
LE Medium outsider (devil, evil, extraplanar, lawful)
Init +0; Senses darkvision 60 ft., see in darkness; Perception +0
--------------------
Defense
--------------------
AC 14, touch 10, flat-footed 14 (+4 natural)
hp 13 (2d10+2)
Fort +4, Ref +3, Will +0
DR 5/good or silver; Immune fire, mind-affecting effects, poison; Resist acid 10, cold 10
--------------------
Offense
--------------------
Speed 20 ft.
Melee 2 claws +2 (1d4)
--------------------
Statistics
--------------------
Str 11, Dex 10, Con 12, Int —, Wis 11, Cha 5
Base Atk +2; CMB +2; CMD 12
Skills Acrobatics +0 (-4 to jump)
--------------------
Ecology
--------------------
Environment any (hell)
Organization solitary, pair, gang (3-5), swarm (6-17), or mob (10-40 or more)
Treasure none
--------------------
Special Abilities
--------------------
Damage Reduction (5/good or silver) You have Damage Reduction against all except Good or Silver attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Cold (10) You have the specified Energy Resistance against Cold attacks.
Immunity to Fire You are immune to fire damage.
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Poison You are immune to poison.
See in Darkness See perfectly in darkness of any kind, including magical darkness.

**Comment by Lavaeolous** [comment]
Identified Issue:

"+" or "-" signs in skill context notes, here -4 to jump

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.
