### ISSUE TITLE
Can't import Bestiary - Marilith (Demon)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#72]
Can't import statblock:

Marilith (Demon)      CR 17
XP 102,400
Male marilith (Pathfinder RPG Bestiary 63)
CE Large outsider (chaotic, demon, evil, extraplanar)
Init +4; Senses darkvision 60 ft.; Perception +31
Aura unholy aura (DC 25)
--------------------
Defense
--------------------
AC 32, touch 17, flat-footed 28 (+4 deflection, +4 Dex, +15 natural, -1 size)
hp 264 (16d10+176)
Fort +25, Ref +18, Will +13
DR 10/cold iron, 10/good; Immune electricity, poison; Resist acid 10, cold 10, fire 10; SR 28
--------------------
Offense
--------------------
Speed 40 ft.
Melee +1 longsword +24/+19/+14/+9 (2d6+8/17-20) or
   +1 longsword +24 (2d6+4/17-20) or
   +1 longsword +24 (2d6+4/17-20) or
   +1 longsword +24 (2d6+4/17-20) or
   +1 longsword +24 (2d6+4/17-20) or
   +1 longsword +24 (2d6+4/17-20) or
   6 slams +17 (1d8+3), tail slap +17 (2d6+3 plus grab)
Space 10 ft.; Reach 10 ft.
Special Attacks constrict (2d6+10), multiweapon mastery
Spell-Like Abilities (CL 16th; concentration +23)
   Constant—true seeing, unholy aura (DC 25)
   At will—greater teleport (self plus 50 lbs. of objects only), project image (DC 23), telekinesis (DC 22)
   3/day—blade barrier (DC 23), fly
   1/day—summon (level 5, 1 marilith 20%, 1 nalfeshnee at 35%, or 1d4 hezrous at 60%)
--------------------
Statistics
--------------------
Str 25, Dex 19, Con 32, Int 18, Wis 18, Cha 25
Base Atk +16; CMB +24 (+26 disarm, +28 grapple); CMD 42 (44 vs. disarm, can't be tripped)
Feats Bleeding Critical, Combat Expertise, Combat Reflexes, Critical Focus, Improved Critical (longsword), Improved Disarm, Power Attack, Weapon Focus (longsword)
Skills Acrobatics +23 (+27 to jump), Bluff +26, Diplomacy +26, Fly +18, Intimidate +26, Knowledge (engineering) +20, Perception +31, Sense Motive +23, Stealth +19, Use Magic Device +26; Racial Modifiers +8 Perception
Languages Abyssal, Celestial, Draconic; telepathy 100 ft.
SQ crushing coils, infuse weapon
Other Gear mwk longsword, mwk longsword, mwk longsword, mwk longsword, mwk longsword, mwk longsword
--------------------
Ecology
--------------------
Environment any (abyss)
Organization solitary, pair, or platoon (1 marilith, 1-3 glabrezus, and 3-14 babaus)
Treasure double (6 mwk longswords, other treasure)
--------------------
Special Abilities
--------------------
Bleeding Critical Critical Hits deal 2d6 bleed damage.
Combat Expertise +/-5 Bonus to AC in exchange for an equal penalty to attack.
Combat Reflexes (5 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Critical Focus +4 to confirm critical hits.
Crushing Coils (DC 25) (Ex) Foes damaged by constrict lose consciousness for 1d8 rds (Fort neg).
Damage Reduction (10/cold iron) You have Damage Reduction against all except Cold Iron attacks.
Damage Reduction (10/good) You have Damage Reduction against all except Good attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Cold (10) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Grab: Tail slap (Large) (Ex) You can start a grapple as a free action if you hit with the designated weapon.
Immunity to Electricity You are immune to electricity damage.
Immunity to Poison You are immune to poison.
Improved Disarm You don't provoke attacks of opportunity when disarming.
Infuse Weapon (Su) Wielded weapons bypass DR as chaotic, evil, and cold iron.
Multiweapon Mastery (Ex) The creature never takes penalties on its attack rolls when fighting with multiple weapons.
Power Attack -5/+10 You can subtract from your attack roll to add to your damage.
Spell Resistance (28) You have Spell Resistance.
Summon (level 5, 1 marilith 20%, 1 nalfeshnee at 35%, or 1d4 hezrous at 60%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.

**Comment by Lavaeolous** [comment]
**Identified Issue:**

Missing range in aura string

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.
