### ISSUE TITLE
Can't import Bestiary - Nalfeshnee (Demon)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#73]
Can't import statblock:

Nalfeshnee (Demon)      CR 14
XP 38,400
Male nalfeshnee (Pathfinder RPG Bestiary 65)
CE Huge outsider (chaotic, demon, evil, extraplanar)
Init +5; Senses darkvision 60 ft., true seeing; Perception +31
Aura unholy aura (DC 23)
--------------------
Defense
--------------------
AC 29, touch 13, flat-footed 28 (+4 deflection, +1 Dex, +16 natural, -2 size)
hp 203 (14d10+126)
Fort +22, Ref +9, Will +21
DR 10/good; Immune electricity, poison; Resist acid 10, cold 10, fire 10; SR 25
--------------------
Offense
--------------------
Speed 30 ft., fly 40 ft. (poor)
Melee bite +23 (3d8+11/19-20), 2 claws +23 (2d6+11)
Space 15 ft.; Reach 15 ft.
Special Attacks unholy nimbus
Spell-Like Abilities (CL 12th; concentration +17)
   Constant—true seeing, unholy aura (DC 23)
   At will—call lightning (DC 18), feeblemind (DC 20), greater dispel magic, greater teleport (self plus 50 lbs. of objects only), slow (DC 18)
   1/day—summon (level 5, 1 nalfeshnee 20%, 1d4 hezrous 40%, or 1d4 vrocks 50%)
--------------------
Statistics
--------------------
Str 32, Dex 13, Con 29, Int 23, Wis 22, Cha 20
Base Atk +14; CMB +27 (+29 bull rush); CMD 42 (44 vs. bull rush)
Feats Awesome Blow, Cleave, Improved Bull Rush, Improved Critical (bite), Improved Initiative, Iron Will, Power Attack
Skills Bluff +22, Diplomacy +22, Fly +10, Intimidate +19, Knowledge (arcana) +23, Knowledge (Enter Choice) +20, Knowledge (planes) +23, Perception +31, Sense Motive +23, Spellcraft +23, Stealth +10, Use Magic Device +22; Racial Modifiers +8 Perception
Languages Abyssal, Celestial, Draconic; telepathy 100 ft.
--------------------
Ecology
--------------------
Environment any (abyss)
Organization solitary or warband (1 nalfeshnee, 1 hezrou, and 2-5 vrocks)
Treasure standard
--------------------
Special Abilities
--------------------
Awesome Blow As standard action, damage and move smaller foe 10 ft. +1d6 dam if collide with something.
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Damage Reduction (10/good) You have Damage Reduction against all except Good attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Acid (10) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Cold (10) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Fly (40 feet, Poor) You can fly!
Immunity to Electricity You are immune to electricity damage.
Immunity to Poison You are immune to poison.
Improved Bull Rush You don't provoke attacks of opportunity when bull rushing.
Power Attack -4/+8 You can subtract from your attack roll to add to your damage.
Spell Resistance (25) You have Spell Resistance.
Summon (level 5, 1 nalfeshnee 20%, 1d4 hezrous 40%, or 1d4 vrocks 50%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.
Unholy Aura (Constant, DC 23) (Sp) Defense against good creatures and lesser globe of invulnerability.
Unholy Nimbus (DC 22) (Su) Explosion of light dazes foes for 1d10 rds. (Will neg)

**Comment by adventuremagic123** [comment]
Doing great!  Most of the Bestiary is importing successfully.

**Comment by Lavaeolous** [comment]
**Identified Issue:**
Knowledge (Enter Choice) +20

*Another* edge case for knowledge skills (after "and", "any two", etc)

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.
