### ISSUE TITLE
Can't import Bestiary - Janni Sheikh (Genie)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#77]
Can't import statblock:

Janni Sheikh (Genie)      CR 7
XP 3,200
Male janni sheikh (Pathfinder RPG Bestiary 141)
N Medium outsider (native)
Init +6; Senses darkvision 60 ft.; Perception +14
--------------------
Defense
--------------------
AC 20, touch 13, flat-footed 17 (+6 armor, +2 Dex, +1 dodge, +1 natural)
hp 58 (9d10+9)
Fort +7, Ref +10, Will +5
Resist fire 10
--------------------
Offense
--------------------
Speed 30 ft. (20 ft. in armor), fly 15 ft. (perfect)
Melee scimitar +13/+8 (1d6+4/18-20)
Ranged composite longbow +11/+6 (1d8/×3)
Special Attacks change size
Spell-Like Abilities (CL 12th; concentration +13)
   3/day—augury, detect magic, divination, invisibility (self only), plane shift (willing targets to elemental planes, Astral Plane, or Material Plane only) (DC 18), speak with animals
   1/day—create food and water, ethereal jaunt (for 1 hour)
--------------------
Statistics
--------------------
Str 19, Dex 15, Con 12, Int 18, Wis 15, Cha 13
Base Atk +9; CMB +13; CMD 26
Feats Combat Reflexes, Dodge, Improved Initiative[B], Lightning Reflexes, Mobility, Power Attack
Skills Acrobatics -3 (-7 to jump), Appraise +16, Bluff +13, Craft (weapons) +14, Fly +17, Intimidate +10, Perception +14, Ride +6, Sense Motive +14, Spellcraft +16, Stealth +9
Languages Common; telepathy 100 ft.
SQ elemental endurance
Other Gear chainmail, arrows (20), composite longbow, scimitar
--------------------
Ecology
--------------------
Environment warm deserts
Organization solitary, pair, company (3-6), or band (7-12)
Treasure standard (chainmail, composite longbow [+3 str], scimitar, other gear)
--------------------
Special Abilities
--------------------
Change Size (2/day, DC 15) (Sp) Change a creature's size as enlarge person or reduce person.
Combat Reflexes (3 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Darkvision (60 feet) You can see in the dark (black and white only).
Elemental Endurance (Ex) Can remain on any of the elemental planes up to 48 hrs. at a time.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Fly (15 feet, Perfect) You can fly!
Mobility +4 to AC vs. AoO provoked by moving out of or through a threatened area.
Power Attack -3/+6 You can subtract from your attack roll to add to your damage.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
Same as #78
