### ISSUE TITLE
Can't import Bestiary - Storm Giant

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#78]
Can't import statblock:

Storm Giant      CR 13
XP 25,600
Male storm giant (Pathfinder RPG Bestiary 152)
CG Huge humanoid (giant)
Init +2; Senses low-light vision; Perception +27
--------------------
Defense
--------------------
AC 28, touch 10, flat-footed 26 (+6 armor, +2 Dex, +12 natural, -2 size)
hp 199 (19d8+114)
Fort +17, Ref +8, Will +13
Defensive Abilities rock catching; Immune electricity
--------------------
Offense
--------------------
Speed 50 ft. (35 ft. in armor), swim 30 ft.
Melee mwk greatsword +27/+22/+17 (4d6+21/17-20) or
   2 slams +21 (2d6+7)
Ranged mwk composite longbow +15/+10/+5 (3d6+14/×3)
Space 15 ft.; Reach 15 ft.
Spell-Like Abilities (CL 15th; concentration +17)
   Constant—freedom of movement
   2/day—control weather, levitate
   1/day—call lightning (DC 15), chain lightning (DC 18)
--------------------
Statistics
--------------------
Str 39, Dex 14, Con 23, Int 16, Wis 20, Cha 15
Base Atk +14; CMB +30 (+32 bull rush, +32 sunder); CMD 42 (44 vs. bull rush, 44 vs. sunder)
Feats Awesome Blow, Cleave, Combat Reflexes, Improved Bull Rush, Improved Critical (greatsword), Improved Sunder, Improved Vital Strike, Iron Will, Power Attack, Vital Strike
Skills Acrobatics +18, Climb +17, Craft (Enter Choice) +11, Intimidate +20, Perception +27, Perform (sing) +12, Sense Motive +24, Swim +22
Languages Auran, Common, Draconic, Giant
SQ water breathing
Other Gear mwk breastplate, mwk composite longbow (+14 Str), mwk greatsword
--------------------
Ecology
--------------------
Environment any warm
Organization solitary or family (2-5 plus 1 sorcerer or cleric of 7th-10th level, 1-2 rocs, 2-6 griffons, and 2-8 sharks)
Treasure standard (mwk breastplate,  mwk composite longbow [+14  str bonus] with 20 arrows, mwk  greatsword, other treasure)
--------------------
Special Abilities
--------------------
Awesome Blow As standard action, damage and move smaller foe 10 ft. +1d6 dam if collide with something.
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Combat Reflexes (3 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Immunity to Electricity You are immune to electricity damage.
Improved Bull Rush You don't provoke attacks of opportunity when bull rushing.
Improved Sunder You don't provoke attacks of opportunity when sundering.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Power Attack -4/+8 You can subtract from your attack roll to add to your damage.
Rock Catching (Ex) You can catch rocks that are thrown at you with a successful Reflex save.
Swim (30 feet) You have a Swim speed.
Vital Strike Standard action: x2 weapon damage dice.
Water Breathing You can breathe water as well as air.

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
**Identified Issue:** Context Notes for Base Speed.

**Comment by Lavaeolous** [comment]
Thanks for all the Input @adventuremagic123 ! This one is the only one thats not yet fixed. The other ones should work in 0.3.5

**Comment by adventuremagic123** [comment]
You are absolutely welcome.  I thought I'd help out by trying to import all of the statblocks for the Bestiary.

If you provide the feature where I can import multiple statblocks at once that would help me a lot.  

It took about 6 hours to do them one at a time.

If you provide that feature, I can very quickly test Bestiary 2 through 6 -- after I get the fixes you've made for Bestiary.

Your import module is the critical feature that enables me to use Foundry VTT -- and I very much appreciate it!

⁣--
Mark​ Young (aka Adventure Magic 1, 2, 3 ...)

**Comment by adventuremagic123** [comment]
BTW, PCGen can also be used as a source for statblocks, although their statblocks require simple changes to work because they broke the standard in minor ways.

1. Export with template "csheet_fantasy_statblock_pathfinder.htm.ftl".

2. Copy-and-paste from a web browser.

3. Look at a standard Pathfinder statblock and fix theirs.

⁣--
Mark​

**Comment by Lavaeolous** [comment]
Fixed in the next update, but there is no context field in the sheet for land/swim/burrow/climb speeds.

**Comment by adventuremagic123** [comment]
I don't have steps-to-reproduce.  I've lost any useful data.

Yesterday, all I did was import the NPC for Bestiary 2 to help test your importer module -- and later that day I downloaded and installed about 40 modules at once.

I started the world to configure the modules.  I found that most of the views on the right side weren't rendering.  A message would appear after initially starting the world view that the connection to the server had failed, and a reconnection was being attempted.

I'm technical.  I've developed a scheme for backing up and do so regularly.  I found that my world was responsible for causing all the problems.  Using the prior world from my backup fixed the problems.

Just something to watch for.  I don't know exactly what did it.  The module installer got stuck at "complete".  I closed FoundryVTT with the X button and restarted.  Maybe that did it?

⁣--
Mark​

**Comment by adventuremagic123** [comment]
I found what caused that.  Installing the "Permission Viewer" module creates this problem.  Don't even have to enable it.  Foundry VTT server fails.  UI doesn't populate (mostly).  Remove this module and the problem goes away.  All your data is ok!

⁣--
Mark​
