### ISSUE TITLE
Can't import Bestiary - Clay Golem

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#79]
Can't import statblock:

Clay Golem      CR 10
XP 9,600
Male clay golem (Pathfinder RPG Bestiary 159)
N Large construct
Init -1; Senses darkvision 60 ft., low-light vision; Perception +0
--------------------
Defense
--------------------
AC 24, touch 8, flat-footed 24 (-1 Dex, +16 natural, -1 size)
hp 101 (13d10+30)
Fort +4, Ref +3, Will +4
DR 10/adamantine, 10/bludgeoning; Immune construct traits, immunity to magic
--------------------
Offense
--------------------
Speed 20 ft.
Melee 2 slams +19 (2d10+7)
Space 10 ft.; Reach 10 ft.
Special Attacks berserk, cursed wound, haste
--------------------
Statistics
--------------------
Str 24, Dex 9, Con —, Int —, Wis 11, Cha 1
Base Atk +13; CMB +21; CMD 30
Skills Acrobatics -1 (-5 to jump)
--------------------
Ecology
--------------------
Environment any
Organization solitary or gang (2-4)
Treasure none
--------------------
Special Abilities
--------------------
Berserk (Ex) When a clay golem enters combat, there is a cumulative 1% chance each round that its elemental spirit breaks free and the golem goes berserk. This chance resets to 0% after one minute of inactivity. A berserk golem attacks the nearest living creature
Construct Traits (+30 HP) Constructs have many immunities.
Cursed Wound (Ex) The damage a clay golem deals doesn't heal naturally and resists magical healing. A character attempting to use magical healing on a creature damaged by a clay golem must succeed on a DC 26 caster level check, or the healing has no effect on the inju
Damage Reduction (10/adamantine) You have Damage Reduction against all except Adamantine attacks.
Damage Reduction (10/bludgeoning) You have Damage Reduction against all except Bludgeoning attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Haste (Su) After it has engaged in at least 1 round of combat, a clay golem can haste itself once per day as a free action. The effect lasts 3 rounds and is otherwise the same as the spell.
Immunity to Ability Damage Immunity to ability damage
Immunity to Ability Drain Immunity to ability drain
Immunity to Bleed You are immune to bleed.
Immunity to Death and Necromancy effects You are immune to Death and Necromancy effects.
Immunity to Disease You are immune to diseases.
Immunity to Energy Drain Immune to energy drain
Immunity to Exhausted You are immune to the exhausted condition.
Immunity to Fatigue You are immune to the fatigued condition.
Immunity to Magic (Ex) A clay golem is immune to any spell or spell-like ability that allows spell resistance. In addition, certain spells and effects function differently against the creature, as noted below.

• A move earth spell drives the golem back 120 feet an
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Nonlethal Damage You are immune to Nonlethal Damage
Immunity to Paralysis You are immune to paralysis.
Immunity to Poison You are immune to poison.
Immunity to Sleep You are immune to sleep effects.
Immunity to Stunning You are immune to being stunned.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.

**Comment by adventuremagic123** [comment]
Notice that part of the description of "Immunity to Magic" is incomplete.  Hero Lab truncates some of the descriptions.  Doesn't seem like that should have stopped this import, though.

However, I tried the following statblock from d20pfsrd.com and it imported:

Clay GolemCR 10

XP 9,600
N Large construct
Init –1; Senses darkvision 60 ft., low-light vision; Perception +0

DEFENSE

AC 24, touch 8, flat-footed 24 (–1 Dex, +16 natural, –1 size)
hp 101 (13d10+30)
Fort +4, Ref +3, Will +4
DR 10/adamantine and bludgeoning; Immune construct traits, magic

OFFENSE

Speed 20 ft.
Melee 2 slams +19 (2d10+7 plus cursed wound)
Space 10 ft.; Reach 10 ft.
Special Attacks berserk, haste

STATISTICS

Str 24, Dex 9, Con —, Int —, Wis 11, Cha 1
Base Atk +13; CMB +21; CMD 30

SPECIAL ABILITIES

Berserk (Ex)
When a clay golem enters combat, there is a cumulative 1% chance each round that its elemental spirit breaks free and the golem goes berserk. This chance resets to 0% after one minute of inactivity. A berserk golem attacks the nearest living creature or smashes some object smaller than itself if no creature is within reach. Once it goes berserk, no known method can reestablish control.

Cursed Wound (Ex)
The damage a clay golem deals doesn’t heal naturally and resists magical healing. A character attempting to use magical healing on a creature damaged by a clay golem must succeed on a DC 26 caster level check, or the healing has no effect on the injured creature.

Haste (Su)
After it has engaged in at least 1 round of combat, a clay golem can haste itself once per day as a free action. The effect lasts 3 rounds and is otherwise the same as the spell.

Immunity to Magic (Ex)
A clay golem is immune to any spell or spell-like ability that allows spell resistance. In addition, certain spells and effects function differently against the creature, as noted below.

A move earth spell drives the golem back 120 feet and deals 3d12 points of damage to it (no save).
A disintegrate spell slows the golem (as the slow spell) for 1d6 rounds and deals 1d12 points of damage (no save).
An earthquake spell cast directly at a clay golem stops it from moving on its next turn and deals 5d10 points of damage (no save).
Any magical attack against a clay golem that deals acid damage heals 1 point of damage for every 3 points of damage it would otherwise deal. If the amount of healing would cause the golem to exceed its full normal hit points, it gains any excess as temporary hit points. A clay golem gets no saving throw against magical attacks that deal acid damage.
ECOLOGY

Environment any
Organization solitary or gang (2–4)
Treasure none

A clay golem wears no clothing except for a metal or stiff leather garment around its hips. It stands over 8 feet tall and weighs 600 pounds.

Construction
A clay golem’s body must be sculpted from a single block of clay weighing at least 1,000 pounds, treated with rare oils and powders worth 1,500 gp.

CL 11th; Price 41,500 gp

CONSTRUCTION REQUIREMENTS
Feats Craft Construct; Spells animate objects, bless, commune, prayer, resurrection; Special creator must be caster level 11th; Skill Checks Craft (sculptures) or Craft (pottery) DC 16; Cost 21,500 gp

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
Yeah, as soon as there are missing closing parenthesis it breaks, because the converter uses these currently to separate special abilities and set the type (su, sp, ex).
