### ISSUE TITLE
Can't import Bestiary - Stone Golem

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#82]
Can't import statblock:

Stone Golem      CR 11
XP 12,800
Male stone golem (Pathfinder RPG Bestiary 163)
N Large construct
Init -1; Senses darkvision 60 ft., low-light vision; Perception +0
--------------------
Defense
--------------------
AC 26, touch 8, flat-footed 26 (-1 Dex, +18 natural, -1 size)
hp 107 (14d10+30)
Fort +4, Ref +3, Will +4
DR 10/adamantine; Immune construct traits, immunity to magic
--------------------
Offense
--------------------
Speed 20 ft.
Melee 2 slams +22 (2d10+9)
Space 10 ft.; Reach 10 ft.
Special Attacks slow
--------------------
Statistics
--------------------
Str 28, Dex 9, Con —, Int —, Wis 11, Cha 1
Base Atk +14; CMB +24; CMD 33
Skills Acrobatics -1 (-5 to jump)
--------------------
Ecology
--------------------
Environment any
Organization solitary or gang (2-4)
Treasure none
--------------------
Special Abilities
--------------------
Construct Traits (+30 HP) Constructs have many immunities.
Damage Reduction (10/adamantine) You have Damage Reduction against all except Adamantine attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Immunity to Ability Damage Immunity to ability damage
Immunity to Ability Drain Immunity to ability drain
Immunity to Bleed You are immune to bleed.
Immunity to Death and Necromancy effects You are immune to Death and Necromancy effects.
Immunity to Disease You are immune to diseases.
Immunity to Energy Drain Immune to energy drain
Immunity to Exhausted You are immune to the exhausted condition.
Immunity to Fatigue You are immune to the fatigued condition.
Immunity to Magic (Ex) A stone golem is immune to any spell or spell-like ability that allows spell resistance. In addition, certain spells and effects function differently against the creature, as noted below.

• A transmute rock to mud spell slows a stone golem (
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Immunity to Nonlethal Damage You are immune to Nonlethal Damage
Immunity to Paralysis You are immune to paralysis.
Immunity to Poison You are immune to poison.
Immunity to Sleep You are immune to sleep effects.
Immunity to Stunning You are immune to being stunned.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Slow (DC 17) (Su) A stone golem can use a slow effect, as the spell, as a free action once every 2 rounds. The effect has a range of 10 feet in a burst centered on the golem and a duration of 7 rounds, requiring a DC 17 Will save to negate. The save DC is Constitution

**Comment by adventuremagic123** [comment]
Was able to import the "Wood Golem".

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
Another one where the Special Abilities are formatted incorrectly, thus breaking the converter. The AoN Version works.
