### ISSUE TITLE
Can't import Bestiary - Giant Slug

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#85]
Can't import statblock:

Giant Slug      CR 8
XP 4,800
Giant slug (Pathfinder RPG Bestiary 254)
N Huge vermin
Init -4; Senses blindsight 60 ft., darkvision 60 ft.; Perception +0
--------------------
Defense
--------------------
AC 20, touch 4, flat-footed 20 (-4 Dex, +16 natural, -2 size)
hp 102 (12d8+48)
Fort +12, Ref +0, Will +4
DR 10/piercing or slashing; Immune acid, mind-affecting effects
Weaknesses susceptible to salt
--------------------
Offense
--------------------
Speed 20 ft.
Melee tongue +15 (2d10+12 plus 2d8 acid)
Ranged spit acid +3 (10d6 acid)
Space 15 ft.; Reach 15 ft.
--------------------
Statistics
--------------------
Str 27, Dex 2, Con 18, Int —, Wis 10, Cha 1
Base Atk +9; CMB +19; CMD 25 (can't be tripped)
Skills Acrobatics -4 (-8 to jump)
SQ malleable
--------------------
Ecology
--------------------
Environment temperate and warm marshes and underground
Organization solitary
Treasure none
--------------------
Special Abilities
--------------------
Blindsight (60 feet) (Ex) Sense things and creatures without seeing them.
Damage Reduction (10/piercing or slashing) You have Damage Reduction against all except Piercing or Slashing attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Immunity to Acid You are immune to acid damage.
Immunity to Mind-Affecting effects You are immune to Mind-Affecting effects.
Malleable (Ex) A giant slug's body is very malleable, allowing it to fit into narrow areas with ease.

A giant slug takes no penalty to its speed or checks when squeezing in an area that is one size category smaller than its actual size (10 feet wide for most
Spit Acid (Ex) A giant slug can spit acid at an opponent within 60 feet (no range increment). With a successful ranged touch attack, the target takes 10d6 points of acid damage (no save).
Susceptible to Salt (Ex) Salt deals damage as if it were acid (1d6/use).

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
The special abilities in this one are malformed. The one from AoN works.
