### ISSUE TITLE
Can't import Bestiary - Unicorn

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#89]
Can't import statblock:

Unicorn      CR 3
XP 800
Male unicorn (Pathfinder RPG Bestiary 269)
CG Large magical beast
Init +3; Senses darkvision 60 ft., low-light vision, scent; Perception +10
Aura magic circle against evil
--------------------
Defense
--------------------
AC 15, touch 12, flat-footed 12 (+3 Dex, +3 natural, -1 size; +2 deflection bonus vs. evil)
hp 34 (4d10+12)
Fort +7, Ref +7, Will +6; +2 resistance vs. evil
Immune charm, compulsion, poison
--------------------
Offense
--------------------
Speed 60 ft.
Melee gore +8 (1d8+4), 2 hooves +5 (1d3+2)
Space 10 ft.; Reach 5 ft.
Special Attacks powerful charge (gore, 2d8+8)
Spell-Like Abilities (CL 9th; concentration +16)
   At will—detect evil (as free action), light
   3/day—cure light wounds
   1/day—cure moderate wounds, greater teleport (within its forest territory), neutralize poison
--------------------
Statistics
--------------------
Str 18, Dex 17, Con 16, Int 11, Wis 21, Cha 24
Base Atk +4; CMB +9; CMD 22 (26 vs. trip)
Feats Multiattack, Weapon Focus (gore)
Skills Acrobatics +8 (+20 to jump), Perception +10, Stealth +8, Survival +7 (+10 in forests); Racial Modifiers +4 Stealth, +3 Survival in forests
Languages Common, Sylvan
SQ magical strike, wild empathy +17
--------------------
Ecology
--------------------
Environment temperate forests
Organization solitary, mated pair, or blessing (3-6)
Treasure none
--------------------
Special Abilities
--------------------
Darkvision (60 feet) You can see in the dark (black and white only).
Immunity to Charm You are immune to charm effects.
Immunity to Compulsion You are immune to compulsion.
Immunity to Poison You are immune to poison.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Magic Circle against Evil (Su) This ability continually duplicates the effect of the spell. The unicorn cannot suppress this ability.
Magical Strike (Ex) A unicorn's gore attack is treated as a magic good weapon for the purposes of damage reduction.
Powerful Charge (Gore, 2d8+8) (Ex) Your charge attacks deal additional damage.
Scent (Ex) Detect opponents within 15+ ft. by sense of smell.
Wild Empathy +17 (Ex) Improve the attitude of an animal, as if using Diplomacy.

**Comment by adventuremagic123** [comment]
So that's how the unicorns were lost.  It wasn't the ark.  It was the import module!  :)

**Comment by adventuremagic123** [comment]
I got this statblock from Hero Lab.  You might benefit from retesting with aonprd.com.  Sometimes Hero Lab truncates some of the descriptions.

I used the latest Pathfinder system and your latest module to test this.

**Comment by Lavaeolous** [comment]
Fixed ;)
