### ISSUE TITLE
PCGen for a PC - Can't import "Linguistics (Androffan) +5"

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#94]
The following statblock from PCGen 6.08.00 RC8 for a PC can't be imported due to the text "Linguistics (Androffan) +5".  Seems like that should be valid?

SCALI	CR 4
XP 1,200

Male fetchling ninja 5

CN Medium outsider (native)

Init +6; Senses darkvision 60 ft., low-light vision, Perception +7

DEFENSE
AC 18, touch 14, flat-footed 18 (+4 armor, +4 Dex)

hp 44 (5d8+10)
Fort +3, Ref +8, Will +2
Defensive Abilities uncanny dodge;
OFFENSE
Speed 30 ft.
Melee adamantine/+1 wakizashi +9 (1d6+1/18-20)
Ranged adamantine shuriken +7 (1d2)
Innate Spell-Like Abilities: disguise self ( DC , 1/day)
STATISTICS
Str 11, Dex 18, Con 14, Int 13, Wis 8, Cha 14
Base Atk +3; CMB +3; CMD 17
Feats Armor Proficiency (Light), Exotic Weapon Proficiency (Katana), Iron Will, Simple Weapon Proficiency, Two-Weapon Fighting, Weapon Finesse, Weapon Focus (Wakizashi)
Skills Acrobatics +12 , Appraise +5 , Bluff +10 , Climb +6 , Diplomacy +10 , Disguise +9 , Escape Artist +9 , Intimidate +6 , Linguistics (Androffan) +5 , Perception +7 , Sense Motive +3 , Sleight of Hand +8 , Stealth +19 , Survival +1 , Use Magic Device +10

Languages Androffan, Common, Terran

SQ ki pool, ninja trick, ninja weapon proficiencies, no trace, poison use, shadow blending, shadowy resistance, skilled, sneak attack, spell-like abilities, vanishing trick, weapon training

Combat Gear meal, per day (good) (10), adamantine shuriken (40); Other Gear +1/shadow studded leather armor, adamantine/+1 wakizashi (2), adamantine shuriken (40), quick runner's shirt, bag of holding (type i)
SPECIAL ABILITIES
Darkvision (Ex) Range 60 ft.; Darkvision is the extraordinary ability to see with no light source at all, out to a range specified for the creature. Darkvision is black and white only (colors cannot be discerned). It does not allow characters to see anything that they could not see otherwise-invisible objects are still invisible, and illusions are still visible as what they seem to be. Likewise, darkvision subjects a creature to gaze attacks normally. The presence of light does not spoil darkvision.

Darkvision Fetchlings can see up to 60' in the dark.

Ki Pool (Su) A ninja with this ability has a pool of 4 ki points, supernatural energy she can use to accomplish amazing feats. As long as she has at least 1 point in her ki pool, she treats any Acrobatics skill check made to jump as if she had a running start. By spending 1 point from her ki pool, a ninja can make one additional attack at her highest attack bonus, but she can do so only when making a full attack. In addition, she can spend 1 point to increase her speed by 20 feet for 1 round. Finally, a ninja can spend 1 point from her ki pool to give herself a +4 insight bonus on Stealth checks for 1 round. Each of these powers is activated as a swift action. A ninja can gain additional powers that consume points from her ki pool by selecting certain ninja tricks. The ki pool is replenished each morning after 8 hours of rest or meditation; these hours do not need to be consecutive. The ninja can now use ki points from this pool to power the abilities of every class she possesses that grants a ki pool.

Low-Light Vision Fetchlings can see twice as far as humans in conditions of dim light.

Low-Light Vision (Ex) You can see x2 as far as humans in low illumination. Characters with low-light vision have eyes that are so sensitive to light that they can see twice as far as normal in dim light. Low-Light Vision is color vision. A spellcaster with low-light vision can read a scroll as long as even the tiniest candle flame is next to her as a source of light. Characters with low-light vision can see outdoors on a moonlit night as well as they can during the day.

Ninja Trick As a ninja continues her training, she learns a number of tricks that allow her to confuse her foes and grant her supernatural abilities. Starting at 2nd level, a ninja gains one ninja trick. She gains one additional ninja trick for every 2 levels attained after 2nd. Unless otherwise noted, a ninja cannot select an individual ninja trick more than once. Tricks marked with an asterisk (*) add effects to a ninja's sneak attack. Only one of these tricks can be applied to an individual attack and the decision must be made before the attack is made.

Ninja Weapon Proficiencies Ninja are proficient with all simple weapons, plus the kama, katana, kusarigama, nunchaku, sai, shortbow, short sword, shuriken, siangham, and wakizashi. They are proficient with light armor but not with shields.

No Trace (Ex) The ninja learnt to cover her tracks, remain hidden, and conceal her presence. The DC to track a ninja using the Survival skill increases by +1. In addition, her training gives her a +1 insight bonus on Disguise skill checks and on opposed Stealth checks whenever she is stationary and does not take any action for at least 1 round.

Poison Use At 1st level, a ninja is trained in the use of poison and cannot accidentally poison herself when applying poison to a weapon.

Reactionary You were bullied often as a child, but never quite developed an offensive response. Instead, you became adept at anticipating sudden attacks and reacting to danger quickly. You gain a +2 trait bonus on Initiative checks.

Shadow Blending Attacks against a fetchling in dim light have a 50% miss chance instead of the normal 20% miss chance. This ability does not grant total concealment; it just increases the miss chance.

Shadow Travel When a fetchling reaches 9th level in any combination of classes, it gains shadow walk (self only) as a spell-like ability usable once per day, and at 13th level, it gains plane shift (self only, to the Plane of Shadow or the Material Plane only) usable once per day. A fetchling's caster level is equal to its total Hit Dice.

Shadowy Resistance Fetchlings have cold resistance 5 and electricity resistance 5.

Skilled (Ex) Fetchlings gain a +2 racial bonus on Knowledge (planes) and Stealth checks.

Sneak Attack If a ninja can catch an opponent when he is unable to defend himself effectively from her attack, she can strike a vital spot for extra damage. The ninja's attacks deal extra damage anytime her target would be denied a Dexterity bonus to AC (whether the target actually has a Dexterity bonus or not), or when the ninja flanks her target. This extra damage is 3d6. Bonus damage from sneak attacks is precision damage. Should the ninja score a critical hit with a sneak attack, this precision damage is not multiplied. Ranged attacks count as sneak attacks only if the target is within 30 feet. With a weapon that deals nonlethal damage (such as a sap, whip, or unarmed strike), a ninja can make a sneak attack that deals nonlethal damage instead of lethal damage. She cannot use a weapon that deals lethal damage to deal nonlethal damage in a sneak attack, even with the usual -4 penalty. The ninja must be able to see the target well enough to pick out a vital spot, and must be able to reach this spot. A ninja cannot sneak attack while striking a creature that has concealment.

Spell-Like Abilities (Sp) Fetchlings can use disguise self 1/day to assume the form of any humanoid creature.

Uncanny Dodge (Ex) You can react to danger before your senses would normally allow you to do so. You cannot be caught flat-footed, nor do you lose your Dexterity bonus to AC if the attacker is invisible. You still lose your Dexterity bonus to AC if immobilized. You can still lose your Dexterity bonus to AC if an opponent successfully uses the feint action against you.

Vanishing Trick (Su) As a swift action, the ninja can disappear for 5 rounds. This ability functions as invisibility. Using this ability uses up 1 ki point.

Weapon Training You gain Weapon Focus as a bonus feat.

Worldly You have acquired an unusual breadth of life experience--more than others of your age, race, or culture. Once per day when attempting a skill check for a skill you're untrained in, you can roll twice and take the better result.

**Comment by adventuremagic123** [comment]
Actually, the complete list of skills originally read as the following until I started changing it:

Skills Acrobatics +12 , Appraise +5 , Bluff +10 , Climb +6 , Diplomacy +10 , Disguise +9 , Escape Artist +9 , Intimidate +6 , Linguistics(Androffan) +5 , Perception +7 , Sense Motive +3 , Sleight of Hand +8 , Stealth +19 , Survival +1 , Use Magic Device +10

The "Linguistics(Androffan) +5" seems to be an error on PCGen's part (and they have a few).  I think it should be "Linguistics (Androffan) +5".  BTW, "Linguistics(Androffan) +5" doesn't parse either and probably shouldn't.

The rest of the statblock I provided is unmodified.

**Comment by adventuremagic123** [comment]
This is the entire PCGen character, if you want to play with it.

Choose File -> Export -> csheet_fantasy_statblock_pathfinder.htm.ftl

**Comment by adventuremagic123** [comment]
I'll just restate to be clear.  PCGen is less reliable than Hero Lab, d20pfsrd.com, and aonprd.com.  PCGen has some issues.

**Comment by Lavaeolous** [comment]
Thanks! Fixed in the next update.
