### ISSUE TITLE
Can't import Bestiary 2 - Shield Archon

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#97]
Can't import the following statblock:

Shield Archon      CR 10
XP 9,600
Male shield archon (Pathfinder RPG Bestiary 2 31)
LG Large outsider (archon, extraplanar, good, lawful)
Init +5; Senses darkvision 60 ft., low-light vision; Perception +15
Aura aura of menace (20 ft., DC 18), magic circle against evil (DC 15)
--------------------
Defense
--------------------
AC 29, touch 10, flat-footed 28 (+9 armor, +1 Dex, +4 natural, +6 shield, -1 size; +2 deflection bonus vs. evil)
hp 112 (9d10+63)
Fort +13, Ref +7, Will +8; +4 vs. poison; +2 resistance vs. evil
DR 10/evil; Immune electricity, petrification; SR 21
--------------------
Offense
--------------------
Speed 40 ft. (30 ft. in armor), fly 90 ft. (good) (60 ft. in armor)
Melee +3 shortspear +16/+11 (1d8+10)
Space 10 ft.; Reach 10 ft.
Special Attacks transpose ally
Spell-Like Abilities (CL 9th; concentration +11)
   Constant—magic circle against evil
   At will—aid, greater teleport (self plus 50 lbs. of objects only), message
   1/day—disrupting weapon, divine power, shield other
--------------------
Statistics
--------------------
Str 20, Dex 13, Con 25, Int 14, Wis 16, Cha 15
Base Atk +9; CMB +15; CMD 26 (30 vs. bull rush, 30 vs. trip)
Feats Combat Reflexes, Improved Initiative, Iron Will, Shield Focus, Stand Still, Weapon Specialization (shortspear)[B]
Skills Diplomacy +14, Fly +0, Intimidate +14, Knowledge (religion) +14, Perception +15, Sense Motive +15, Stealth -6, Survival +15
Languages Celestial, Draconic, Infernal; truespeech
SQ spear and shield
Other Gear full plate, +1 tower shield, +3 shortspear
--------------------
Ecology
--------------------
Environment any (heaven)
Organization solitary, pair, or squad (3-5)
Treasure standard (full plate, other treasure)
--------------------
Special Abilities
--------------------
Aura of Menace (20 ft., DC 18) (Su) Hostile creatures must save or take a -2 to attacks, AC, and saves for 24 hours.
Combat Reflexes (2 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (10/evil) You have Damage Reduction against all except Evil attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Fly (90 feet, Good) (60 ft. in armor) You can fly!
Immunity to Electricity You are immune to electricity damage.
Immunity to Petrification You are immune to Petrification.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Poison Resistance +4 (Ex) You have the listed resistance to poison.
Spear and Shield (Su) As a free actions transform either or both hands into +1 tower shields or +3 shortspears.
Spell Resistance (21) You have Spell Resistance.
Stand Still When taking an AoO, you can make a combat maneuver check to end opponent's movement instead of attacking.
Transpose Ally (1/day) (Su) Teleport to switch places with a willing/unconscious ally as a standard action.
Truespeech (Su) Speak with any creature that has a language.

**Comment by adventuremagic123** [comment]
I used Hero Lab to produce this statblock.  For greater accuracy, you might want to use one of the online resources.  Hero Lab can truncate some of the text.  All the other statblocks from Bestiary 2 imported -- a total of more than 96% imported.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this morning.

**Comment by Lavaeolous** [comment]
Identified Issue:
Speed Context Modifier for Fly Speeds, e.g.

**fly 90 ft. (good) (60 ft. in armor)**
