### ISSUE TITLE
Can't import Bestiary 2  - Star Archon

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#98]
Can't import the following statblock:

Star Archon      CR 19
XP 204,800
Male star archon (Pathfinder RPG Bestiary 2 32)
LG Large outsider (archon, extraplanar, good, lawful)
Init +8; Senses darkvision 60 ft., detect evil, low-light vision, true seeing; Perception +29
Aura courage +4 (20 ft.), aura of menace (20 ft., DC 27), magic circle against evil (DC 19)
--------------------
Defense
--------------------
AC 34, touch 11, flat-footed 32 (+9 armor, +1 Dex, +1 dodge, +12 natural, +2 shield, -1 size; +2 deflection bonus vs. evil)
hp 294 (19d10+190); regeneration 10 (evil weapons and effects)
Fort +21, Ref +17, Will +15; +4 vs. poison; +2 resistance vs. evil
Defensive Abilities explosive rebirth; DR 10/evil; Immune charm, compulsion, electricity, fear, fire, petrification; SR 30
--------------------
Offense
--------------------
Speed 40 ft. (30 ft. in armor), fly 90 ft. (good)
Melee +5 holy starknife +30/+25/+20/+15 (1d6+12/×3 plus 2d6 vs. evil)
Space 10 ft.; Reach 10 ft.
Special Attacks smite evil
Spell-Like Abilities (CL 19th; concentration +25)
   Constant—detect evil, magic circle against evil, true seeing
   At will—aid, continual flame, greater teleport (self plus 50 lbs. of objects only), message, sunbeam (DC 23)
   1/day—meteor swarm (DC 25), polar ray, prismatic spray (DC 23), sunburst (DC 24)
Cleric Spells Prepared (CL 19th; concentration +26)
   9th—mass heal, implosion (DC 26), miracle
   8th—dimensional lock, fire storm (DC 25), holy aura
   7th—destruction (2, DC 24), holy word (2, DC 24), resurrection
   6th—mass cure moderate wounds (3), greater dispel magic, heal
   5th—break enchantment (2), breath of life (2, DC 22), flame strike (DC 22)
   4th—cure critical wounds (3), death ward, divine power
   3rd—cure serious wounds (3), dispel magic (2), invisibility purge
   2nd—cure moderate wounds (4), eagle's splendor, status (DC 19)
   1st—cure light wounds (4), divine favor, sanctuary (DC 18)
   0 (at will)—guidance, resistance, stabilize, virtue
--------------------
Statistics
--------------------
Str 24, Dex 19, Con 31, Int 20, Wis 24, Cha 23
Base Atk +19; CMB +27; CMD 42
Feats Blind-fight, Cleave, Combat Reflexes, Dodge, Improved Initiative, Iron Will, Lightning Reflexes, Mobility, Power Attack, Stand Still
Skills Diplomacy +28, Fly +20, Heal +16, Intimidate +28, Knowledge (arcana) +14, Knowledge (engineering) +14, Knowledge (history) +18, Knowledge (nature) +18, Knowledge (religion) +24, Perception +29, Sense Motive +29, Spellcraft +24, Stealth +14, Survival +17
Languages Celestial, Draconic, Infernal; truespeech
Other Gear full plate, heavy steel shield, +5 holy starknife
--------------------
Ecology
--------------------
Environment any (heaven)
Organization solitary or pair
Treasure double (full plate, heavy steel shield, +5 holy starknife)
--------------------
Special Abilities
--------------------
Aura of Courage +4 (20 ft.) (Su) You are immune to Fear. Allies within aura gain a morale bonus to saves vs. fear.
Aura of Menace (20 ft., DC 27) (Su) Hostile creatures must save or take a -2 to attacks, AC, and saves for 24 hours.
Blind-Fight Re-roll misses because of concealment, other benefits.
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Combat Reflexes (5 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (10/evil) You have Damage Reduction against all except Evil attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Explosive Rebirth (DC 29) (Su) Explodes upon death and reincarnates 1d4 rd. later
Fly (90 feet, Good) You can fly!
Immunity to Charm You are immune to charm effects.
Immunity to Compulsion You are immune to compulsion.
Immunity to Electricity You are immune to electricity damage.
Immunity to Fear (Ex) You are immune to all fear effects.
Immunity to Fire You are immune to fire damage.
Immunity to Petrification You are immune to Petrification.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Mobility +4 to AC vs. AoO provoked by moving out of or through a threatened area.
Poison Resistance +4 (Ex) You have the listed resistance to poison.
Power Attack -5/+10 You can subtract from your attack roll to add to your damage.
Regeneration 10 (evil weapons and effects) Heal HP quickly and cannot die.
Smite Evil (1/day) (Su) +6 to hit, +19 to damage, +6 deflection bonus to AC when used.
Spell Resistance (30) You have Spell Resistance.
Stand Still When taking an AoO, you can make a combat maneuver check to end opponent's movement instead of attacking.
Truespeech (Su) Speak with any creature that has a language.

**Comment by adventuremagic123** [comment]
I used Hero Lab to produce this statblock.  For greater accuracy, you might want to use one of the online resources.  Hero Lab can truncate some of the text.  All the other statblocks from Bestiary 2 imported -- a total of more than 96% imported.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this morning.

**Comment by Lavaeolous** [comment]
Identified Issues:

- [ ] Wrong Attack Modifier for Starknife
- [ ] Spell Parsing Errors

Apart from that, it should parse with v0.4.0

**Comment by Lavaeolous** [comment]
Identified Issue:

- [ ] Wrong DamageModifier for Attacks with enhanced weapons

**Comment by Lavaeolous** [comment]
Identified Issue:

- [ ] Generating empty Spells when more than one of the same is prepared, e.g. Cure Serious Wounds (2)
