### ISSUE TITLE
Can't import Bestiary 2 - Purrodaemon (Daemon)

### ISSUE THREAD

**Issue by adventuremagic123** [Lavaeolous/PF1-StatBlock-Converter-Module#99]
Can't import statblock:

Purrodaemon (Daemon)      CR 18
XP 153,600
Male purrodaemon (Pathfinder RPG Bestiary 2 73)
NE Large outsider (daemon, evil, extraplanar)
Init +10; Senses darkvision 60 ft.; Perception +26
Aura fear (15 ft., DC 24), unholy aura (DC 23)
--------------------
Defense
--------------------
AC 35, touch 19, flat-footed 29 (+4 deflection, +6 Dex, +16 natural, -1 size)
hp 294 (19d10+190)
Fort +25, Ref +21, Will +14
DR 10/good, 10/silver; Immune acid, death effects, disease, poison; Resist cold 10, electricity 10, fire 10; SR 29
--------------------
Offense
--------------------
Speed 30 ft.
Melee +2 wounding halberd +32/+27/+22/+17 (2d8+18/19-20/×3 plus 1 bleed) or
   bite +24 (1d8+5)
Space 10 ft.; Reach 10 ft.
Special Attacks weapon steep
Spell-Like Abilities (CL 18th; concentration +23)
   Constant—true seeing, unholy aura
   At will—greater teleport (self plus 50 lbs.)
   3/day—chain lightning (DC 21), cone of cold (DC 20), flame strike (DC 20)
   1/day—summon (level 5, 2 derghodaemons 50%)
--------------------
Statistics
--------------------
Str 32, Dex 23, Con 30, Int 17, Wis 18, Cha 21
Base Atk +19; CMB +31 (+33 sunder); CMD 51 (53 vs. sunder)
Feats Combat Expertise, Combat Reflexes, Greater Vital Strike, Improved Critical (halberd)[B], Improved Initiative, Improved Sunder, Improved Vital Strike, Lunge, Power Attack, Quick Draw, Vital Strike, Weapon Focus (halberd)[B]
Skills Acrobatics +28, Bluff +21, Diplomacy +17, Intimidate +27, Knowledge (planes) +25, Perception +26, Sense Motive +26, Spellcraft +22, Stealth +24, Survival +17
Languages Abyssal, Draconic, Infernal; telepathy 100 ft.
Other Gear +2 wounding halberd
--------------------
Ecology
--------------------
Environment any (abaddon)
Organization solitary, patrol (2-5), or unit (6-12)
Treasure standard
--------------------
Special Abilities
--------------------
Combat Expertise +/-5 Bonus to AC in exchange for an equal penalty to attack.
Combat Reflexes (7 AoO/round) Can make extra attacks of opportunity/rd, and even when flat-footed.
Damage Reduction (10/good) You have Damage Reduction against all except Good attacks.
Damage Reduction (10/silver) You have Damage Reduction against all except Silver attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Cold (10) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Electricity (10) You have the specified Energy Resistance against Electricity attacks.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Fear Aura (15 feet, DC 24) Foes within radius are affected by the fear spell.
Immunity to Acid You are immune to acid damage.
Immunity to Death Effects You are immune to death effects.
Immunity to Disease You are immune to diseases.
Immunity to Poison You are immune to poison.
Improved Sunder You don't provoke attacks of opportunity when sundering.
Lunge Can increase reach by 5 ft, but take -2 to AC for 1 rd.
Power Attack -5/+10 You can subtract from your attack roll to add to your damage.
Quick Draw Draw weapon as a free action (or move if hidden weapon). Throw at full rate of attacks.
Spell Resistance (29) You have Spell Resistance.
Summon (level 5, 2 derghodaemons 50%, 1/day) (Sp) Summon creatures as though with summon monster spell but with limited chance of success.
Telepathy (100 feet) (Su) Communicate telepathically if the target has a language.
Vital Strike Standard action: x2 weapon damage dice.
Weapon Steep (Su) A purrodaemon can sheathe a weapon in its flesh as a swift action. This does no damage to the daemon. If a weapon remains sheathed in its body for at least 24 hours, the weapon absorbs some of its essence and gains magical enhancements. A purrodaemon

**Comment by adventuremagic123** [comment]
I used Hero Lab to produce this statblock.  For greater accuracy, you might want to use one of the online resources.  Hero Lab can truncate some of the text.  All the other statblocks from Bestiary 2 imported -- a total of more than 96% imported.

**Comment by adventuremagic123** [comment]
Used your latest module that was available as of this morning.

**Comment by Lavaeolous** [comment]
Should import with v0.4.0 apart from

- [ ] Spell-Parse Errors (i'm entering these separately)
